import { Section } from '@/types';

export const sections: Section[] = [
  {
    id: 'personality',
    title: 'How You Move Through the World',
    subtitle: 'These questions explore your core personality patterns — how you typically think, act, and engage with life.',
    questions: [
      { id: 'o1', type: 'likert', text: 'I love exploring unfamiliar ideas, places, and experiences.', dimension: 'O', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'o2', type: 'likert', text: 'I often get lost in my imagination or creative thoughts.', dimension: 'O', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'o3', type: 'likert', text: 'I prefer routines and familiar environments over novelty.', dimension: 'O', reverse: true, minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'o4', type: 'likert', text: 'I enjoy abstract or philosophical discussions about big ideas.', dimension: 'O', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'c1', type: 'likert', text: 'I finish what I start, almost without exception.', dimension: 'C', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'c2', type: 'likert', text: 'I plan things out carefully before starting.', dimension: 'C', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'c3', type: 'likert', text: 'I sometimes leave things to the last minute.', dimension: 'C', reverse: true, minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'c4', type: 'likert', text: 'Details matter to me — I notice things others miss.', dimension: 'C', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'e1', type: 'likert', text: 'I come alive in social situations and feel energized by people.', dimension: 'E', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'e2', type: 'likert', text: "I'd rather spend a Friday night at home than at a large gathering.", dimension: 'E', reverse: true, minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'e3', type: 'likert', text: 'I tend to take charge in group situations naturally.', dimension: 'E', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'e4', type: 'likert', text: 'I find small talk draining rather than energizing.', dimension: 'E', reverse: true, minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'a1', type: 'likert', text: 'I naturally tune into how people around me are feeling.', dimension: 'A', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'a2', type: 'likert', text: 'I find it hard to say no, even when I should.', dimension: 'A', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'a3', type: 'likert', text: 'I can be blunt or critical when I think it is necessary.', dimension: 'A', reverse: true, minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'a4', type: 'likert', text: 'I genuinely enjoy helping people, even when there is nothing in it for me.', dimension: 'A', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'n1', type: 'likert', text: 'I get stressed by uncertainty or things outside my control.', dimension: 'N', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'n2', type: 'likert', text: 'I tend to worry about things that might go wrong.', dimension: 'N', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'n3', type: 'likert', text: 'I bounce back quickly from setbacks.', dimension: 'N', reverse: true, minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
      { id: 'n4', type: 'likert', text: 'I get irritated fairly easily when things do not go as expected.', dimension: 'N', minLabel: 'Not at all like me', maxLabel: 'Very much like me' },
    ],
  },
  {
    id: 'connection',
    title: 'How You Connect',
    subtitle: 'These scenarios reveal how you relate in close relationships — your patterns with intimacy, conflict, and closeness.',
    questions: [
      {
        id: 'att1', type: 'choice', text: 'Someone you love becomes distant without explanation. Your instinct is to:',
        dimension: 'attachment',
        options: [
          { value: 'anxious', label: 'Reach out immediately and try to reconnect — the distance feels urgent.', scores: { anxious: 3, secure: 0, avoidant: 0, disorganized: 1 } },
          { value: 'secure', label: 'Give them space and trust it will work out — you feel steady.', scores: { anxious: 0, secure: 3, avoidant: 1, disorganized: 0 } },
          { value: 'avoidant', label: 'Feel some relief — closeness can feel like a lot sometimes.', scores: { anxious: 0, secure: 0, avoidant: 3, disorganized: 1 } },
          { value: 'disorganized', label: 'Feel completely unsettled — unsure whether to reach out or pull back.', scores: { anxious: 1, secure: 0, avoidant: 1, disorganized: 3 } },
        ],
      },
      {
        id: 'att2', type: 'choice', text: 'After a meaningful conflict with a close friend, that night you:',
        dimension: 'attachment',
        options: [
          { value: 'anxious', label: 'Feel anxious until you can talk it through and know you are okay.', scores: { anxious: 3, secure: 0, avoidant: 0, disorganized: 1 } },
          { value: 'secure', label: 'Feel sad but trust the friendship is solid enough to handle it.', scores: { anxious: 0, secure: 3, avoidant: 0, disorganized: 0 } },
          { value: 'avoidant', label: 'Move on fairly quickly — conflict is part of life.', scores: { anxious: 0, secure: 1, avoidant: 3, disorganized: 0 } },
          { value: 'disorganized', label: 'Feel confused about what you even want from the relationship.', scores: { anxious: 1, secure: 0, avoidant: 0, disorganized: 3 } },
        ],
      },
      {
        id: 'att3', type: 'choice', text: 'In your closest relationships, love tends to feel:',
        dimension: 'attachment',
        options: [
          { value: 'anxious', label: 'Urgent — you need regular reassurance that things are okay.', scores: { anxious: 3, secure: 0, avoidant: 0, disorganized: 1 } },
          { value: 'secure', label: 'Stable — it is there even without constant confirmation.', scores: { anxious: 0, secure: 3, avoidant: 0, disorganized: 0 } },
          { value: 'avoidant', label: 'Complicated — closeness sometimes makes you want to pull back.', scores: { anxious: 0, secure: 0, avoidant: 3, disorganized: 1 } },
          { value: 'disorganized', label: 'Confusing — you are not sure what you need or what to expect.', scores: { anxious: 1, secure: 0, avoidant: 1, disorganized: 3 } },
        ],
      },
      {
        id: 'att4', type: 'choice', text: 'When someone you care about is clearly upset, your natural first response is to:',
        dimension: 'attachment',
        options: [
          { value: 'anxious', label: 'Feel anxious yourself until they feel better.', scores: { anxious: 3, secure: 0, avoidant: 0, disorganized: 1 } },
          { value: 'secure', label: 'Listen, be present, and offer support without absorbing their emotion.', scores: { anxious: 0, secure: 3, avoidant: 0, disorganized: 0 } },
          { value: 'avoidant', label: 'Give them space — you trust they can work through it.', scores: { anxious: 0, secure: 0, avoidant: 3, disorganized: 0 } },
          { value: 'disorganized', label: 'Feel overwhelmed and unsure what would actually help.', scores: { anxious: 1, secure: 0, avoidant: 0, disorganized: 3 } },
        ],
      },
      {
        id: 'conflict1', type: 'choice', text: 'When a disagreement comes up, your default approach is to:',
        dimension: 'conflictStyle',
        options: [
          { value: 'assertive', label: 'Address it directly, even when it is uncomfortable.', scores: { assertive: 3, avoidant: 0, accommodating: 0, reactive: 0 } },
          { value: 'avoidant', label: 'Let it pass and hope it resolves on its own.', scores: { assertive: 0, avoidant: 3, accommodating: 1, reactive: 0 } },
          { value: 'accommodating', label: 'Smooth it over to preserve harmony.', scores: { assertive: 0, avoidant: 1, accommodating: 3, reactive: 0 } },
          { value: 'reactive', label: 'Stand your ground strongly in the moment, sometimes more than intended.', scores: { assertive: 1, avoidant: 0, accommodating: 0, reactive: 3 } },
        ],
      },
      {
        id: 'conflict2', type: 'choice', text: "Your partner or close friend is upset with you. You are fairly sure you didn't do anything wrong. You:",
        dimension: 'conflictStyle',
        options: [
          { value: 'accommodating', label: 'Apologize anyway to end the tension — the peace matters more.', scores: { assertive: 0, avoidant: 0, accommodating: 3, reactive: 0 } },
          { value: 'assertive', label: 'Ask what is wrong and have an honest, calm conversation about it.', scores: { assertive: 3, avoidant: 0, accommodating: 0, reactive: 0 } },
          { value: 'avoidant', label: 'Wait it out — you are not going to engage if you know you are not at fault.', scores: { assertive: 0, avoidant: 3, accommodating: 0, reactive: 0 } },
          { value: 'reactive', label: 'Feel defensive and push back immediately.', scores: { assertive: 0, avoidant: 0, accommodating: 0, reactive: 3 } },
        ],
      },
    ],
  },
  {
    id: 'inner-architecture',
    title: 'Your Inner Architecture',
    subtitle: 'These statements explore the deeper structures of your personality — how your mind is organized beneath the surface.',
    questions: [
      { id: 'enn1', type: 'likert', text: 'I have a powerful inner critic — a voice that holds me to very high standards.', dimension: 'enneagram_1', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'enn2', type: 'likert', text: 'My deepest drive is to be genuinely useful and needed by the people I love.', dimension: 'enneagram_2', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'enn3', type: 'likert', text: 'I often measure my worth by what I achieve or how successful I appear to others.', dimension: 'enneagram_3', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'enn4', type: 'likert', text: 'I have a persistent sense that something is missing — a longing I cannot fully name.', dimension: 'enneagram_4', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'enn5', type: 'likert', text: 'I need significant time alone to think and recharge — my inner world feels rich and complex.', dimension: 'enneagram_5', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'enn6', type: 'likert', text: 'I often scan for danger, hidden problems, or what could go wrong — even in good situations.', dimension: 'enneagram_6', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'enn7', type: 'likert', text: 'I keep myself busy and moving — stopping or sitting with difficult feelings is hard.', dimension: 'enneagram_7', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'enn8', type: 'likert', text: 'I care deeply about having control over my environment, choices, and life direction.', dimension: 'enneagram_8', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'enn9', type: 'likert', text: 'I naturally mediate between people — being a peacemaker feels core to who I am.', dimension: 'enneagram_9', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'jung1', type: 'likert', text: 'When making big decisions, I trust my gut instincts more than logical analysis.', dimension: 'jungian_NF', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'jung2', type: 'likert', text: 'I prefer having a rich big-picture understanding over mastering technical details.', dimension: 'jungian_N', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'jung3', type: 'likert', text: 'When evaluating ideas, I naturally think about the impact on people first.', dimension: 'jungian_F', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'jung4', type: 'likert', text: 'I process information better by talking it out than by thinking alone first.', dimension: 'jungian_E', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
    ],
  },
  {
    id: 'motivation',
    title: 'What Moves You',
    subtitle: 'What you care about most — and what truly drives your choices.',
    questions: [
      {
        id: 'values1',
        type: 'ranking',
        text: 'Rank these from most to least important to you personally. Drag to reorder — most important at the top.',
        dimension: 'values',
        items: [
          'Freedom & Autonomy',
          'Achievement & Success',
          'Deep Connection & Love',
          'Security & Stability',
          'Creativity & Expression',
          'Knowledge & Learning',
          'Impact & Contribution',
          'Fairness & Justice',
          'Adventure & Novelty',
          'Wealth & Comfort',
        ],
      },
      { id: 'mot1', type: 'likert', text: 'I am more motivated by the fear of failure than by excitement about success.', dimension: 'motivation_fear', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'mot2', type: 'likert', text: 'I often act to gain recognition or approval from others.', dimension: 'motivation_external', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'mot3', type: 'likert', text: 'My deepest motivation comes from genuine curiosity and love of learning.', dimension: 'motivation_intrinsic', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'mot4', type: 'likert', text: 'I feel most alive when working toward something that feels deeply meaningful.', dimension: 'motivation_purpose', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'mot5', type: 'likert', text: 'I push harder when I feel someone doubts me.', dimension: 'motivation_reactive', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
    ],
  },
  {
    id: 'mind-pressure',
    title: 'Your Mind Under Pressure',
    subtitle: 'How your thinking and emotions behave when things get difficult.',
    questions: [
      { id: 'cd1', type: 'likert', text: 'I jump to worst-case scenarios when something goes wrong.', dimension: 'distortion_catastrophizing', minLabel: 'Rarely', maxLabel: 'Almost always' },
      { id: 'cd2', type: 'likert', text: 'I can sense how people feel about me, even without direct evidence.', dimension: 'distortion_mindreading', minLabel: 'Rarely', maxLabel: 'Almost always' },
      { id: 'cd3', type: 'likert', text: 'For me, things tend to be either a success or a failure — rarely in between.', dimension: 'distortion_allornone', minLabel: 'Rarely', maxLabel: 'Almost always' },
      { id: 'cd4', type: 'likert', text: 'I sometimes attribute bad events to permanent flaws in myself.', dimension: 'distortion_personalization', minLabel: 'Rarely', maxLabel: 'Almost always' },
      { id: 'cd5', type: 'likert', text: "I feel responsible for other people's emotions.", dimension: 'distortion_responsibility', minLabel: 'Rarely', maxLabel: 'Almost always' },
      { id: 'cd6', type: 'likert', text: 'I downplay or dismiss my own achievements and positive experiences.', dimension: 'distortion_discounting', minLabel: 'Rarely', maxLabel: 'Almost always' },
      { id: 'er1', type: 'likert', text: 'When I feel strong negative emotions, I tend to suppress them rather than express them.', dimension: 'er_suppression', minLabel: 'Rarely', maxLabel: 'Almost always' },
      { id: 'er2', type: 'likert', text: 'I can sit with difficult emotions without needing to immediately fix or escape them.', dimension: 'er_tolerance', minLabel: 'Rarely', maxLabel: 'Almost always' },
      { id: 'er3', type: 'likert', text: 'My mood is significantly affected by what the people around me are feeling.', dimension: 'er_contagion', minLabel: 'Rarely', maxLabel: 'Almost always' },
      { id: 'er4', type: 'likert', text: 'When I am in a negative state, I can usually identify exactly what I am feeling.', dimension: 'er_awareness', minLabel: 'Rarely', maxLabel: 'Almost always' },
    ],
  },
  {
    id: 'decisions',
    title: 'How You Decide',
    subtitle: 'Your decision-making style, risk tolerance, and your relationship with control.',
    questions: [
      { id: 'dec1', type: 'likert', text: 'When facing a big decision, I trust my gut instincts more than data or analysis.', dimension: 'decision_intuitive', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'dec2', type: 'likert', text: 'I sometimes commit quickly, even without all the information I would ideally want.', dimension: 'decision_decisive', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'dec3', type: 'likert', text: 'I tend to feel regret more sharply when things go wrong after I acted than when I failed to act.', dimension: 'decision_lossaversion', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'loc1', type: 'likert', text: 'The outcomes of my life are largely in my own hands.', dimension: 'locus_internal', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'loc2', type: 'likert', text: 'Luck and timing play a bigger role in success than most people admit.', dimension: 'locus_external', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'risk1', type: 'likert', text: 'I would rather miss a good opportunity than risk a significant loss.', dimension: 'risk_averse', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'risk2', type: 'likert', text: 'I feel comfortable expressing unpopular opinions in group settings.', dimension: 'risk_social', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'risk3', type: 'likert', text: 'I enjoy exploring ideas that might be wrong or that challenge accepted wisdom.', dimension: 'risk_intellectual', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
    ],
  },
  {
    id: 'strengths',
    title: 'Your Strengths Signature',
    subtitle: 'What you are genuinely good at — and how clearly you see yourself.',
    questions: [
      {
        id: 'str1',
        type: 'ranking',
        text: 'Which of these best describe your genuine strengths? Rank them — most characteristic of you at the top.',
        dimension: 'strengths',
        items: [
          'Creativity — finding original solutions, thinking differently',
          'Curiosity — loving to learn, always asking why',
          'Judgment — thinking critically, weighing all sides',
          'Perspective — seeing the big picture others miss',
          'Bravery — facing difficulty without shrinking',
          'Honesty — valuing truth and authenticity above comfort',
          'Kindness — genuinely caring for and helping others',
          'Social Intelligence — reading people and situations well',
          'Leadership — organizing and motivating groups effectively',
          'Fairness — treating people equitably, valuing justice',
          'Humility — knowing your limits, staying grounded',
          'Perseverance — finishing what you start despite obstacles',
        ],
      },
      { id: 'scc1', type: 'likert', text: 'My sense of who I am shifts depending on who I am around.', dimension: 'scc_low', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'scc2', type: 'likert', text: 'I have a clear, stable sense of my values and who I am.', dimension: 'scc_high', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'scc3', type: 'likert', text: 'Sometimes I am not sure what I actually believe versus what I think I am supposed to believe.', dimension: 'scc_low', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
      { id: 'scc4', type: 'likert', text: 'I know what I stand for, even in situations that pressure me to change.', dimension: 'scc_high', minLabel: 'Disagree strongly', maxLabel: 'Agree strongly' },
    ],
  },
  {
    id: 'story',
    title: 'Your Story',
    subtitle: 'These open-ended questions are the most important part of your analysis. Take your time — the more honest and specific you are, the more accurate your report will be.',
    questions: [
      {
        id: 'story1', type: 'text',
        text: 'Describe a chapter of your life — a year, a season, a period — that fundamentally shaped who you are. What happened, and what did it make you believe about yourself?',
        dimension: 'openEnded',
        subtext: 'Be specific. A real story tells us more than a general summary.',
      },
      {
        id: 'story2', type: 'text',
        text: 'What do people who know you well consistently say about you? Both the compliments and the patterns they have noticed.',
        dimension: 'openEnded',
        subtext: 'Include the uncomfortable observations — those are the most useful.',
      },
      {
        id: 'story3', type: 'text',
        text: "What is the gap between who you are and who you're trying to become? What do you think is getting in the way?",
        dimension: 'openEnded',
        subtext: 'Be honest about what you actually believe, not what sounds good.',
      },
      {
        id: 'story4', type: 'text',
        text: 'Describe a decision you deeply regret. What does that choice reveal about how you were thinking at the time?',
        dimension: 'openEnded',
        subtext: 'There are no wrong answers here — only honest and dishonest ones.',
      },
    ],
  },
];
