export const blindspotSeeds: Record<string, Record<string, string>> = {
  low: {
    'Your Blind Spot Profile':
      "You relate to yourself differently depending on context — and the differences aren't small. Who you are at work isn't just a different version of who you are at home; it can feel like a different person entirely. Your values, your confidence, your opinions about yourself — all of these shift with the environment you're in, with who's in the room, with what's being asked of you. Psychologists call this low self-concept clarity, and it doesn't mean you're shallow or inconsistent as a person. It means that your sense of self hasn't fully coalesced into something stable enough to stay recognizable across situations. That has real consequences for how you move through the world — for what you want, who you attract, and how much of your inner life is actually available to you versus being constructed on the fly.",

    'The Pattern You\'re In':
      "The pattern at this level of self-concept clarity is one of identity malleability. You absorb the expectations and emotional climate of the people around you more readily than most. Walk into a confident room and you feel capable; walk into a critical one and your self-assessment collapses. In close relationships, you're susceptible to something called identity capture — where the other person's view of you starts to become your view of you, especially if they hold it with enough certainty. You may find yourself agreeing with assessments of yourself that you wouldn't have generated on your own, or realizing months later that what you wanted was actually what someone around you wanted. The thing you're most in the dark about is your own baseline — what you actually think, want, and believe when no one is doing the organizing for you.",

    'How Others Experience This':
      "From the outside, you can read as chameleon-like — adaptable, easy to be around, socially fluent. People who don't know you well tend to like you; you mirror back enough of what they offer that the interaction feels comfortable. But the people who do know you well often hit a frustrating wall. They're not always sure what you actually think. They can have a conversation with you where you seem to agree entirely, and then discover later that you disagreed but didn't say so — or that you weren't sure what you thought until after the conversation, when someone else weighed in. The experience of being close to you can sometimes feel like trying to get a clear signal through static. You're there, you're warm, but the picture keeps shifting. That's not a personal failure. It's what low self-concept clarity looks like from the outside.",

    'The Cost of Not Seeing It':
      "The cost is significant and often invisible until it accumulates into something impossible to ignore. Without a clear sense of what you actually want and value, you can spend years on paths that were chosen more by drift than decision — jobs, relationships, places — things that made sense in context but that don't connect to anything you can genuinely call yours. You're also at higher risk of exploitation, not because you're naive but because the internal alarm that should tell you 'this isn't right for me' is unreliable. By the time you notice you're in the wrong situation, you may be deeply embedded in it. There's also an emotional cost: the chronic low-grade confusion about who you are produces an anxiety that doesn't have a clear name, which makes it hard to address directly.",

    'Getting Eyes on Your Blind Spots':
      "The work at this level starts with creating conditions for self-knowledge rather than trying to manufacture it. That means spending deliberate time alone — not lonely, but alone — outside of the social contexts that are doing your identity work for you. Journaling, if you're not already doing it, is surprisingly powerful not because writing down your thoughts is inherently useful but because the act of having to commit to a sentence forces you to locate what you actually think. Notice the moments after social interactions where your sense of yourself or your view of a situation has shifted, and ask what produced the shift — information or influence. Over time, you're building a more stable internal reference point. Not a rigid identity, but a thread back to yourself that holds even when the room changes.",
  },

  medium: {
    'Your Blind Spot Profile':
      "You have a reasonably solid sense of who you are — but it's context-dependent in ways you've probably noticed. In situations you know well, you're clear: clear on what you value, what you want, how you come across. Put you somewhere unfamiliar, or under sustained pressure, or into a role that doesn't quite fit, and the clarity softens into something more provisional. You know yourself in the comfortable register. What you're working with is a self-concept that has good architecture but incomplete coverage — strong in the middle, fuzzier at the edges. The blind spot that tends to come with this territory isn't that you don't know yourself at all; it's more specific than that. It's the gap between how you think you land with other people and how you actually land.",

    'The Pattern You\'re In':
      "The pattern here is one of selective clarity. You have well-developed self-knowledge in your areas of confidence and familiarity, and genuinely poor self-knowledge in the territories you haven't had to examine. You may have a fairly accurate picture of your technical competence, your communication style in low-stakes situations, your values in simple cases. What goes offline under pressure is the accurate read on impact. When you're stressed, or excited, or in conflict, your sense of how you're coming across diverges from reality in ways you don't catch in the moment. You might think you sounded measured when you sounded dismissive. You might think you were being direct when you were being abrasive. The feedback would surprise you, not because you lack self-awareness but because your self-awareness tends to be most accurate exactly when you need it least.",

    'How Others Experience This':
      "People who know you moderately well tend to find you self-aware and easy to be with. You understand yourself enough to make sense of your behavior, which makes you easier to read and trust than someone with low self-concept clarity. The surprise, for people who know you well, tends to come in specific moments — moments where you did something that didn't match your self-image and seemed not to notice. A comment that landed harder than you realized. A pattern of behavior in conflict that you describe as calm but others experience as cold. A habit of underestimating your own influence in group dynamics. These aren't character flaws; they're the edges of your self-model. The people close to you learn to navigate those edges, but they sometimes wish they could just say something without it being harder than it needs to be.",

    'The Cost of Not Seeing It':
      "The medium-SCC blind spot is sneaky because it doesn't feel like a blind spot — it feels like self-awareness. You do have self-awareness. You have more of it than most people. That's actually what makes this particular gap hard to address: when someone offers you feedback that doesn't match your self-image, your first and most natural response is to evaluate it against what you already know about yourself rather than to genuinely sit with it. That evaluative reflex — reasonable in most cases — can make you selectively resistant to exactly the information that would close the gap. The cost is in the relationships and situations where that gap creates real friction, and you're the last person to see the pattern clearly. Professional opportunities can slip; relationships can sour in slow ways that feel like the other person's issue.",

    'Getting Eyes on Your Blind Spots':
      "For you, the most direct route to closing the gap is structured feedback in contexts that matter to you. Not vague 'how am I doing' conversations, but specific questions: What's one thing I do that you'd want me to do differently? What does it feel like to disagree with me? Where do you think I underestimate my own impact? These questions are uncomfortable precisely because they're useful — they're asking for exactly the information your self-model doesn't generate on its own. Outside of formal feedback, start noticing the moments where your internal experience of a situation and someone else's description of that same situation don't line up. That gap is your curriculum. The goal isn't to adopt everyone's perception of you; it's to have a more accurate and complete picture of the full range of how you land.",
  },

  high: {
    'Your Blind Spot Profile':
      "You know who you are. That's not nothing — for a lot of people it's the work of years, and you've done it. You have a coherent, stable sense of your values, your personality, your strengths and limitations. You don't get knocked sideways by other people's opinions of you the way more identity-diffuse people do. You can hold a position under pressure. You know what you care about and why. High self-concept clarity correlates with lower anxiety, better decision-making, and stronger psychological wellbeing. So yes — this is genuinely good. But there's a version of it that tips from clarity into rigidity, and that's where the blind spot lives. When you're very certain about who you are, it becomes increasingly difficult to update that picture — not because you're arrogant, but because the certainty itself acts as a filter.",

    'The Pattern You\'re In':
      "The pattern at high self-concept clarity is one of defensive authenticity. When you behave in a way that produces friction, your most ready explanation is that you were being yourself — that the problem is the other person's discomfort with your honesty, directness, or high standards. And sometimes that's accurate. But the pattern becomes a trap when 'being authentic' becomes a reason not to investigate whether a behavior is actually working the way you intend. High-SCC people can be resistant to feedback in a particular way: they don't dismiss it outright, they process it through their existing self-model and it doesn't quite stick. You might hear that you come across as dismissive in a certain context and think, 'I understand why they'd say that, but that's not really who I am' — which is technically true and also functionally irrelevant to the problem.",

    'How Others Experience This':
      "People tend to experience you as competent, consistent, and reliable in the sense of being predictable. You're not a wildcard. You show up the same way across contexts, which earns trust and reduces the cognitive load of having to re-figure you out every time. The friction, when it happens, tends to be specific: it happens when someone has something difficult to tell you. Your internal coherence can read as self-assurance that closes off conversation. People learn, sometimes without fully articulating it, that certain feedback about you is not a productive conversation to have. Not because you've been hostile — you may have been entirely pleasant. But because the conversation had a quality of going nowhere, of the feedback meeting a finished self-model rather than a genuinely open one. That learned silence is costly, and you don't see it forming.",

    'The Cost of Not Seeing It':
      "The cost is that your self-model becomes increasingly accurate about who you were and less accurate about who you are becoming — or who you need to become. Contexts change. Relationships evolve. The strengths that carried you to a certain point can become liabilities at the next one. High self-concept clarity without corresponding flexibility means you continue confidently down a path that has subtly changed beneath you. There's also a specific cost in leadership or any role where you have significant influence: the people around you calibrate to what you're willing to hear. If your clarity reads as closedness, the information that reaches you gets filtered before it arrives. You become less informed over time, not because the information isn't there but because the people around you have learned to present you with a version of reality they think you can use.",

    'Getting Eyes on Your Blind Spots':
      "For you, the work is less about gaining self-knowledge and more about creating genuine conditions for your self-model to be updated. That starts with distinguishing between being challenged and being threatened. Feedback that contradicts your self-image isn't an attack on who you are — it's potentially new data about how you function in the world, which is worth knowing. The practice is sitting with disconfirming feedback longer than feels natural before reaching for your explanation. Not abandoning your self-knowledge, but holding it more lightly in those moments. Ask yourself occasionally: what would I need to see to update this belief about myself? If the answer is 'nothing I can imagine,' that's the rigidity speaking, not the clarity. The distinction between knowing yourself well and having closed the book on yourself is the most important edge to manage.",
  },
};
