export const decisionPatternSeeds: Record<string, Record<string, string>> = {
  intuitive: {
    'Your Decision Profile':
      "Your decision profile is built on fast pattern recognition — the cognitive equivalent of reading a room the moment you walk in. You process situational cues rapidly, match them against a large internal library of prior experience, and arrive at a judgment before you've fully articulated the reasoning behind it. This isn't guessing. It's a legitimate cognitive process that psychologists call Type 1 thinking — fast, automatic, and in the right conditions, remarkably accurate. What you experience as a gut feeling or instinct is often your brain's pattern-matching system surfacing a conclusion that it reached through unconscious but real computation. The challenge is that the process is opaque to you. You know what you think before you know why you think it, which makes your decisions hard to explain and also hard to interrogate. You can't always reconstruct the reasoning because it didn't happen consciously — which means you also can't always tell when the pattern-match was accurate and when it was overconfident. Your profile produces people who are fast, decisive, and often right. It also produces people who are occasionally very wrong in ways they don't see coming, because the same confidence that comes from accurate pattern-matching also attaches to inaccurate pattern-matching. Learning to distinguish between the two is the core work of your decision style.",

    'How You Actually Make Decisions':
      "Here's what actually happens when you make a decision, regardless of what the official process looks like. A situation presents itself and your brain starts running against its stored experience immediately — not sequentially but in parallel, activating multiple associations at once. Within seconds, often faster, a preferred direction is starting to form. You might not have consciously chosen it yet. You might still be listening to the briefing or reading the proposal. But something in you has already started leaning. From there, you tend to gather information selectively — you're looking for confirmation or disconfirmation of the direction that's already forming, not conducting an open-ended survey of all possibilities. This means that additional information often reinforces your initial read rather than genuinely updating it, because you're filtering it through a hypothesis already in progress. When you've gathered enough to feel confident — a threshold that varies by context and stakes — you make the call and move. The move itself tends to be decisive and clear rather than hedged or conditional. You'd rather be wrong and clear than uncertain and verbose. What doesn't happen: you rarely sit with a decision in extended deliberation, rarely feel the need to exhaust all options before choosing, and rarely experience the kind of analysis paralysis that slows down more deliberate processors.",

    'Where the Algorithm Breaks':
      "Your decision process breaks down in a specific set of situations that are worth knowing cold. Novel situations — where the surface features resemble something familiar but the underlying dynamics are genuinely different — are your most consistent failure mode. Your pattern-matching system sees the similarity and activates the familiar response, but the similarity is superficial. The new situation has different rules, different constraints, different second-order effects. You've misapplied a pattern from one domain to another where it doesn't hold, and because the recognition felt solid, you carried a confidence into the decision that the situation didn't warrant. High-stakes decisions that require extended deliberation are another breakdown zone. Not because you're incapable of deliberating, but because the intuitive system generates a confident answer early, and sustained deliberation after that point feels like it's working against a conclusion you've already reached. You may go through the motions of deliberation while the original read is quietly anchoring everything. Decisions in genuinely ambiguous situations — where the data is sparse, the domain is unfamiliar, and no prior experience maps cleanly — are also costly for your style, because there's no existing pattern to match and your system has to slow down in ways that feel unnatural.",

    'Your Most Dangerous Decision Type':
      "The most dangerous decision type for your profile is the one that feels familiar but isn't. This is worth understanding in concrete terms. You've made a lot of decisions. You've built a large library of patterns, and many of them are accurate. This is genuinely valuable. But the same library that serves you well in familiar territory produces overconfidence in territories that look familiar but operate by different rules. A market that looks like one you've seen before. A relationship dynamic that has the surface features of something from your past. A technical problem that maps onto something you've solved, except the one degree of difference is the degree that matters. The feeling of recognition is the same whether the pattern-match is accurate or not — and that feeling is where your confidence comes from. You can't feel the difference between a good match and a bad one in the moment. You have to develop other signals: noticing when you're unusually confident and asking why, noticing when the situation has features that are genuinely novel even if the overall shape is familiar, and building in a deliberate pause specifically for high-stakes decisions that feel obvious — because obvious is where you're most likely to have stopped checking.",

    'Upgrading Your Process':
      "Upgrading your decision process doesn't mean slowing everything down — that would discard the genuine asset that is your pattern-recognition speed. It means building a targeted intervention for the specific failure modes. The highest-leverage change is developing a pre-mortem habit for significant decisions. Before you commit, spend five minutes assuming the decision was wrong and generating the most plausible explanation for how it went badly. This isn't pessimism — it's a mechanism for surfacing the things your pattern-matching may have missed, particularly in the novel-looks-familiar category. The second upgrade is building a deliberate pause before high-confidence calls. When you notice you're very sure, very quickly, about something consequential, that confidence is a signal to pause rather than a signal to act. The certainty is data about your nervous system's state, not about the accuracy of your read. Slowing down specifically when you're most confident is counterintuitive for your style but specifically corrective for your failure mode. Third, find a deliberate thinker whose judgment you respect and whose process is different from yours, and build a practice of running significant decisions through them. Not to outsource the decision, but to surface the considerations your process skips.",
  },

  deliberate: {
    'Your Decision Profile':
      "Your decision profile is built on systematic processing — the cognitive equivalent of reading the manual before you operate the equipment. You gather information, structure the considerations, weigh the options, and move when you feel you have a sufficient understanding of the landscape. This is Type 2 thinking: slow, conscious, effortful, and in the right conditions, excellent. The quality of decisions made by deliberate processors tends to be higher in complex, novel situations with clear criteria than the quality produced by intuitive snap judgments. You bring a rigor to decision-making that prevents the pattern-matching overconfidence that trips up faster processors. You notice things that intuitive thinkers miss because you're actually reading the full brief rather than pattern-matching off the first paragraph. The cost is time and sometimes momentum. Your profile produces people who make fewer catastrophic errors of overconfidence and more errors of over-deliberation — staying in analysis past the point where more information would actually help, or optimizing a decision so carefully that the moment for action has passed. Understanding your profile means understanding the genuine value of your process and also the specific ways it can work against you.",

    'How You Actually Make Decisions':
      "When you make a decision, here's what actually happens. A situation presents itself and you start gathering — information, perspectives, context, criteria. You have a genuine appetite for completeness: you want to understand the full picture before you commit to a direction. As information accumulates, you organize it. You might do this explicitly through lists, pros and cons, or frameworks, or internally, but the structuring instinct is real. You're building a model of the decision space, not just a preference. From there, you weigh. Different considerations get different importance, different options get evaluated against the criteria, and the preferred direction emerges from the weighting rather than from a sudden recognition. The move, when it comes, tends to be preceded by a sense that you've done your due diligence — that you've given the decision the consideration it deserves. This produces a kind of confidence that's different from the intuitive processor's confidence: yours is earned through process rather than felt through recognition. What doesn't happen: snap calls, shooting from the hip, committing before you're ready. You can feel premature commitment as a kind of wrongness, a sense that you're moving without adequate ground beneath you. That feeling is usually right. It's also occasionally wrong in situations where adequate ground isn't coming and waiting for it is its own decision.",

    'Where the Algorithm Breaks':
      "Your process breaks down in a specific cluster of situations. Time-pressure is probably the clearest one: when a decision needs to happen faster than your process can run, you either produce something that feels poorly constructed and you're uncomfortable with, or you slow the decision down past the point where the opportunity is still available. The pressure to decide before you're ready is genuinely uncomfortable for your style, and it shows. Ambiguous situations where more data won't actually help are another breakdown zone. There's a kind of decision where you're looking for the information that will resolve the uncertainty, and it doesn't exist. The uncertainty is structural, not informational. More time spent gathering won't reduce it. Your process, designed to reduce uncertainty through information, doesn't have a natural off-ramp in these situations. This is where deliberation becomes avoidance — where the continued gathering is functioning as a way not to commit rather than as genuine preparation. This is probably the most important failure mode to recognize: the difference between productive deliberation and productive-looking avoidance. They feel similar from the inside. They produce different outcomes.",

    'Your Most Dangerous Decision Type':
      "The most dangerous decision type for your profile is the one where analysis has become a substitute for decision. This is subtle and worth taking seriously. Deliberation is genuinely valuable, and your instinct to gather and weigh before committing is usually the right instinct. But there's a version of this process that has tipped into something else: gathering that isn't oriented toward deciding but toward delaying, weighting that isn't helping you choose but helping you avoid choosing, criteria that keep expanding because no existing information base quite feels sufficient. The danger here is that it can look and feel like rigor while functioning as avoidance. You're doing the work of a careful decision-maker. You're just not arriving at a decision. The situations where this dynamic is most likely to emerge are ones with high stakes, significant uncertainty, or where any choice involves a real loss — giving up options, committing to a path that forecloses others, accepting that you might be wrong. These are exactly the conditions where your deliberate instincts are most warranted, and also the conditions where they're most likely to tip into paralysis.",

    'Upgrading Your Process':
      "Upgrading your process means adding interventions at the back end — where you tend to get stuck — rather than the front. The most direct thing you can do is build a decision deadline into your process at the start. Not an arbitrary one, but a considered one: given what I know about this decision, how long should the deliberation take? Then hold yourself to it. The deadline isn't about rushing — it's about preventing the deliberation from running indefinitely. A second upgrade is developing a better signal for when more information would actually help versus when you're in genuinely irreducible uncertainty. The practical test: if you got the next piece of information you're looking for, would you decide? If the honest answer is 'I'd feel better but probably still not quite ready,' you're past the point of genuine deliberation. Third, practice what might be called reversibility thinking: for a given decision, how bad is being wrong, and specifically, how reversible is a bad outcome? Many decisions that feel high-stakes are actually more reversible than your process treats them. Calibrating your deliberation time to actual reversibility — rather than to your felt sense of uncertainty — tends to move you faster on low-reversibility decisions that need speed, and gives you appropriate time on the genuinely irreversible ones.",
  },
};
