export const emotionalTriggerSeeds: Record<string, Record<string, string>> = {
  secure: {
    'Your Trigger Blueprint':
      "Your emotional trigger profile is one of the more functional ones out there, and that's not empty praise — it's a specific thing worth understanding. You have triggers. Everyone does. But yours tend to be proportionate responses to real violations rather than nervous system misfires looking for a reason to go off. When you feel activated, something has usually actually happened: trust got broken, a line got crossed, someone treated you or someone else unfairly. The signal is connected to the event, which means your anger and hurt are useful data rather than noise. What makes this profile distinct is that you're not constantly in low-grade threat-scanning mode. You can be fully present in a relationship or situation without bracing for impact, which frees up a lot of cognitive and emotional bandwidth. You move through most days without your nervous system quietly cataloguing danger. That's rarer than people realize. The flip side is that when genuine violations do occur, you feel them clearly and directly. You're not someone who talks yourself out of legitimate hurt. But you're also not someone who amplifies it past what the situation warrants. The challenge, if there is one, is that this proportionality can be misread by people around you who expect either more reactivity or more suppression. You might seem unaffected when you're actually just regulated, and your real reactions — when they come — can catch people off guard precisely because they don't come constantly.",

    'The Tripwires (What Sets You Off)':
      "Your triggers cluster around a specific set of genuine violations rather than a broad, ambient threat landscape. Broken trust is probably the most consistent one — not just being lied to in the obvious sense, but the subtler version where someone's actions and words stop matching over time and you can feel the gap widening. You notice inconsistency early, and when it accumulates without acknowledgment, that's when your system lights up. Unfairness is another one, and this extends beyond situations that affect you personally. You can get activated by watching someone else get treated unfairly, especially when the person doing it seems unaware of or indifferent to the impact. There's a moral dimension to your trigger profile that isn't present in every attachment style. Exclusion — feeling genuinely left out of something that mattered, particularly when it seemed intentional — also registers. This isn't about needing to be included everywhere. It's about the deliberate version, the kind where someone chose not to bring you in and it had real consequences. What's notable about your tripwires is what isn't on the list. Ambiguous texts, someone seeming a little off today, a conversation that didn't go quite as expected — these don't tend to send you spiraling. You have a fairly high threshold for tolerating uncertainty in relationships without reading catastrophe into it.",

    'The Internal Sequence (What Happens Inside)':
      "Your sequence is probably the cleanest of the four profiles, which doesn't mean painless — just functional. When a trigger fires, the first thing that happens is that you feel it. Not in a dramatic way, but the emotion arrives and you're aware of it. There isn't a long delay between the event and your internal response, and there isn't an immediate rush to suppress or perform. You feel, and then fairly quickly you can name what you're feeling — not as a practiced cognitive exercise but as something that happens more or less naturally. From there, the sequence moves toward response rather than rumination. You might take some time, you might not, but you're generally oriented toward doing something with the feeling rather than cycling through it on repeat. That might mean having a conversation, setting a limit, or simply deciding something has changed. The sequence rarely spirals. You don't tend to get stuck in a loop where the original event keeps generating new emotional material hours or days later. Once you've processed something, it's processed. The main variation in your sequence is whether you name what you're feeling to yourself first or go straight to response — and that probably depends on the stakes and the relationship. In high-trust situations, you might skip the internal naming and just engage directly. In lower-trust situations, you're more deliberate.",

    'Why These Hit So Hard':
      "Even for a secure attachment profile, the things that actually land hit hard for specific reasons worth understanding. Your triggers are tied to your values rather than your fears, which sounds like a strength — and it is — but it also means the things that activate you feel important, not just uncomfortable. When trust gets broken, it's not just an interpersonal inconvenience. It bumps up against something you genuinely believe about how people should treat each other. When someone is unfair, you're not just annoyed — something in you registers it as a kind of small injustice, and that has weight. The hits also land harder in relationships where you've genuinely invested. You don't carry a constant low-level wariness about people, which means when you do trust someone and they violate that trust, the gap between expectation and reality is significant. You weren't braced for it. There's also something worth naming about the hits that come from being misread — having your regulated response interpreted as indifference, or having your directness interpreted as aggression. These sting not because you're fragile, but because accuracy matters to you. Being seen clearly is something you value, and being systematically misread by someone you care about is its own kind of trigger, quieter but persistent.",

    'Getting Ahead of the Pattern':
      "The strategic question for your profile isn't how to calm down faster — you're already reasonably good at that. The more useful question is how to stay honest about what's actually activating you before it accumulates. Your triggers are real and proportionate, but because you don't react dramatically, it's easy to let things slide longer than you should. Small violations compound. Trust erodes incrementally. And because you're not in constant threat-detection mode, you can miss the point at which a pattern has become a pattern. The practice here is naming things earlier, not necessarily to the other person but at least to yourself. Building in the habit of checking in: what's actually happening here, and have I said so? The other edge of your profile is how you handle people who operate from very different trigger landscapes. Someone who is anxious or avoidant may read your groundedness as unavailability, and your direct responses as threats. Being aware of this mismatch doesn't mean managing them — it means knowing that your neutral is their scary, and adjusting how you enter hard conversations accordingly. You don't need to become less regulated; you need to become more legible about what regulated actually looks like on you.",
  },

  anxious: {
    'Your Trigger Blueprint':
      "Your trigger profile is one of the most exhausting ones to live inside, and if you've felt that — the constant low-grade vigilance, the way a single unanswered text can pull your whole attention, the way you can be fine and then suddenly not fine because of something that barely registered on the other person — then this section is about explaining the mechanics of that experience rather than pathologizing it. Your triggers aren't random. They have a specific architecture: they're organized almost entirely around connection, presence, and the fear that the people who matter most are about to disappear, withdraw, or stop caring. This isn't a character flaw. It's a nervous system that learned very early that relationships are uncertain, that presence isn't guaranteed, and that it needed to be constantly scanning for signs of withdrawal. The alert system worked — or at least felt like it worked — at some point. The problem is that it's still running on that old calibration, which means it's sensitive to inputs that the situation doesn't actually warrant. Understanding your trigger profile means understanding that the threat you're responding to is usually real in some emotional register, even when the specific event that sparked it is genuinely small. The text that didn't come back for four hours probably isn't evidence of impending abandonment. But your nervous system has a different read, and knowing that distinction is the beginning of working with it rather than being run by it.",

    'The Tripwires (What Sets You Off)':
      "The tripwires in your profile cluster tightly. Slow or absent communication — the delayed text, the vague response, the conversation that felt normal until it suddenly went quiet — these are probably your most consistent activators. The thing about this tripwire is that it doesn't require malicious intent to fire. The other person could be busy, distracted, in a different headspace, or just a slow responder by temperament. None of that matters much to your nervous system, which reads absence as a signal. Tone ambiguity is another major one. A message that could be read as warm or could be read as distant — and you'll read it as distant. A conversation that felt a little off, where you couldn't quite identify why but something seemed wrong, where the other person seemed slightly less engaged than usual. You're picking up on real micro-signals, but the interpretation gets catastrophized: something is wrong, and it's probably about you, and it's probably serious. Being last in someone's priorities — real or perceived — is a third tripwire. Canceling plans, making you wait, putting other things first repeatedly without acknowledgment. And underneath all of these is the same root: anything that feels like the beginning of withdrawal, like the distance between you and someone important is growing.",

    'The Internal Sequence (What Happens Inside)':
      "The sequence inside your profile is specific and it moves fast. First, a threat signal arrives — something in the environment that your nervous system flags as potentially dangerous to your connection with someone. It doesn't need to be dramatic. The signal can be something most people would process and forget in thirty seconds. But the flag goes up, and from there the sequence runs almost automatically. Catastrophizing comes next: your mind starts generating explanations for the signal, and the explanations that win aren't the neutral ones. They're the ones that confirm the threat. The slow text becomes evidence of fading interest. The slightly flat tone becomes evidence of unspoken resentment. The explanation isn't chosen — it arrives. It feels like reading the situation accurately rather than interpreting it anxiously. Then activation: the emotional intensity comes up, the urgency to do something about the threat. This is when the reaching-for-reassurance impulse shows up. A check-in text, a question about whether everything is okay, a bid for connection disguised as something else. Sometimes it works — the reassurance arrives, the alarm settles. But it doesn't fix the underlying calibration, so the next trigger fires the same sequence again. The part of the sequence that's most important to understand is the gap between the signal and the catastrophizing — because that's where you actually have room to work.",

    'Why These Hit So Hard':
      "The reason these triggers land with the force they do isn't weakness. It's that they're aimed directly at something that feels essential rather than optional. For your nervous system, connection isn't a nice-to-have — it's a foundational resource that regulates your sense of safety in the world. When something threatens that connection, even ambiguously, even improbably, the emotional response is sized to the perceived threat, which is enormous. It also hits hard because the pattern is self-reinforcing in a specific way: the more activated you get, the more likely you are to do something that actually does create distance — the check-in text that comes across as demanding, the question that puts the other person on the defensive, the urgency that makes them feel like they're failing you even though nothing was actually wrong. The threat of disconnection can produce the very disconnection you were afraid of, which then becomes evidence that the threat was real. Understanding why it hits so hard is also about understanding the timeline: these reactions aren't just about what's happening right now. They're about every time something similar happened before, which is a much longer list than the current situation warrants.",

    'Getting Ahead of the Pattern':
      "Getting ahead of your pattern is genuinely possible, but it requires working at the level of the sequence, not just the outcome. The place with the most leverage isn't after you've already reached for reassurance — it's in the gap between the threat signal and the catastrophizing, which is narrow but real. Building the habit of pausing in that gap and asking a specific question: what are the other explanations for this signal, and am I giving them a fair hearing? Not to dismiss your read, but to hold it lightly enough that you can check it before acting on it. The other piece is reducing the cognitive load on your threat-detection system. Some of that is environmental — being more selective about which relationships you invest in at this level of intensity, so your nervous system isn't running the same high-alert protocol across everything. Some of it is relational — building agreements with people you're close to about how they communicate, so your nervous system has fewer ambiguous inputs to interpret. The reassurance-seeking behavior itself is worth examining specifically. Not because it's bad, but because it often reinforces the pattern: you learn that reaching out works as a regulation strategy, which makes you more likely to reach out earlier in the sequence next time. Finding other ways to regulate the activation — physical movement, distraction, a time limit before responding — can slowly recalibrate the default.",
  },

  avoidant: {
    'Your Trigger Blueprint':
      "Your trigger profile is almost the mirror image of the anxious one, and understanding that inversion is useful. Where anxious attachment gets activated by the threat of too much distance, your system fires on too much closeness. The threat your nervous system has learned to watch for is encroachment: someone needing too much, getting too close too fast, demanding emotional access that feels like it costs more than you can afford. This isn't about being cold or not caring — though it can look that way from the outside. It's about a nervous system that learned early that emotional demands are costly, that dependency is risky, that the safest configuration is one where you remain functional and self-sufficient regardless of what anyone else does. The trigger system that resulted from that learning is finely tuned to threats against your autonomy, your internal space, and your sense of being able to manage your own experience without assistance. What makes your profile genuinely tricky is that the coping strategy feels like self-regulation but functions as avoidance. Going cold, increasing distance, finding reasons to be less available — these feel like restoration, and in some sense they are. But they also prevent the kind of relational work that could actually change the underlying calibration. Knowing your trigger blueprint means knowing that your default moves are protection strategies with real costs, not just neutral preferences.",

    'The Tripwires (What Sets You Off)':
      "Your tripwires have a specific shape. Being needed more than you can comfortably give — a partner who wants daily emotional check-ins, a friend who calls in crisis repeatedly, anyone who treats your attention as a resource they can draw on without limit — this fires reliably. It's not that you don't care. It's that the demand activates something that feels like being consumed, like your internal resources are being depleted faster than they can replenish. Criticism is another strong one, particularly when it comes in the form of someone analyzing your emotional responses or pointing out patterns in your behavior. There's something about being seen through that feels exposing in a way that you don't have a comfortable response to. The typical response is withdrawal rather than engagement, which then gets read as defensiveness, which then generates more feedback about your emotional unavailability, which is itself a trigger. Intimacy that moves faster than you can track — the relationship that escalates to emotional depth before you've had time to orient — is a third tripwire. You may be fine with intellectual closeness, with shared activities, even with physical connection. But the moment someone wants to really know what's going on inside you, or starts assuming emotional access they haven't earned in your internal accounting, the distance-creating behaviors start.",

    'The Internal Sequence (What Happens Inside)':
      "Your sequence is distinctive because it runs so quietly. A threat signal arrives — something that reads as encroachment or demand or exposure — and the first response isn't emotional intensity. It's shutdown. The emotional volume goes down rather than up. You may not even notice it happening in the moment; it registers more as a feeling of wanting to be somewhere else, a flattening of engagement, a slight increase in the effort it takes to be present in the conversation. From there, the sequence moves toward withdrawal. This might be physical — finding a reason to end the interaction — or it might be internal, a kind of going-through-the-motions while your attention retreats somewhere private. Distance arrives and the system registers something like relief. Not happiness, exactly, but a sense of the pressure reducing, of being able to breathe again. What doesn't happen in your sequence is the kind of activation that's visible from the outside. You go cold rather than hot. You become less available rather than more insistent. This makes your trigger responses hard for other people to read and hard for you to examine — because they don't feel dramatic. They feel like preference, like just needing space, like being independent. The absence of emotional fireworks is part of what makes the pattern hard to see.",

    'Why These Hit So Hard':
      "Your triggers hit hard for a reason that has almost nothing to do with the person triggering you and almost everything to do with what emotional demands came to mean at an earlier point in your life. For your nervous system, someone needing too much isn't just inconvenient — it's threatening in a specific way, as if responding fully would cost you something you can't afford to lose. There's an underlying belief operating here: that your emotional resources are finite, exhaustible, not renewable through the act of giving. That belief is worth questioning, but it's running in the background of every activation, which is why the response is so automatic. The triggers also hit hard because your coping moves are genuinely effective at reducing the immediate pressure, which makes them reinforcing. Going cold works — the demand reduces, the space opens up, you feel better. But it works in the same way that not eating works when you're stressed about your weight: it produces short-term relief and long-term cost. The relief is real, which is why the pattern persists. And the cost — relationships that don't get to deepen, people who eventually stop trying, the loneliness that can sit underneath self-sufficiency — tends to be invisible until it's accumulated significantly.",

    'Getting Ahead of the Pattern':
      "The strategic leverage point in your profile is the space between the shutdown impulse and the withdrawal behavior. Your system will still go quiet — that's a nervous system response, not a character choice, and fighting it directly doesn't usually work. But the behavior that follows the shutdown is more plastic than it feels. The question to get curious about is this: can you stay in the room — physically, conversationally — even when the withdrawal impulse has fired, even for longer than feels comfortable? Not as a performance of availability but as an experiment in what actually happens if you don't increase the distance. The data your nervous system is working from says that closeness is threatening and distance is relief. The only way to update that data is to test it in low-stakes situations and find out if the prediction is accurate. The other piece is developing more granular vocabulary for what you're actually experiencing when the shutdown happens. 'I need space' is a broad category that covers everything from genuine depletion to reflexive avoidance. Getting more specific — even just to yourself — about which is which in a given moment gives you more options than the binary of engage or withdraw.",
  },

  disorganized: {
    'Your Trigger Blueprint':
      "Your trigger profile is the most complex of the four, and complexity here isn't a euphemism — it's a literal description of what's happening in your nervous system. Both closeness and distance can activate you, which puts you in a bind that the other three profiles don't face: there's no consistently safe direction. Moving toward connection can feel dangerous. Moving away can feel just as dangerous. The nervous system is running two contradictory programs simultaneously — approach and avoid — and the result is behavior that can look chaotic from the outside and feel out of control from the inside. This profile typically develops in relational contexts where the source of safety was also a source of threat — where the person you needed to go to when frightened was also sometimes the source of the fright. The nervous system didn't get to build a coherent strategy for managing relationships because no single strategy was reliably safe. What you have instead is a system that's exquisitely sensitive to threat from every direction, with response patterns that don't always make sense even to you. Understanding this as a blueprint — as a logical adaptation to an illogical situation — is different from resignation. It's the beginning of working with your nervous system rather than being baffled by it.",

    'The Tripwires (What Sets You Off)':
      "Your tripwires come from both directions, which is what makes them so exhausting. On the intimacy side: genuine closeness, vulnerability in others, someone wanting to know you deeply, being needed, being depended on — these can all fire the system. The threat here is about exposure, about letting someone in and losing control over what they do with the access. On the distance side: withdrawal, perceived rejection, someone becoming less available, feeling left behind — these fire the system from the other angle. The same relationship can trigger you for being too close and then trigger you again for creating distance. This isn't inconsistency in the moral sense. It's a nervous system that can't find a stable configuration. Specific situations that tend to be particularly activating: conflict that feels like it's spiraling, moments of high emotional intensity in either direction, transitions in relationships (things getting more serious, things cooling off), and situations where the other person's emotional state is unpredictable or volatile. Your system is scanning for threat constantly, and because the threat can come from closeness or distance, the scanning never fully turns off.",

    'The Internal Sequence (What Happens Inside)':
      "Your sequence is different from the other profiles because it doesn't follow a clean directional logic. The threat signal arrives, and then what happens is something like an approach-avoidance conflict firing simultaneously — you're pulled toward and away from the source at the same time. This creates the dysregulation that's characteristic of your profile: the nervous system is getting contradictory instructions and producing behavior that reflects both. Sometimes the approach wins first — you move toward, reach out, get close — and then the avoidance kicks in as a correction: you pull back, get cold, create distance. Sometimes it runs the other way. Sometimes it runs in rapid alternation. The unpredictability of your own responses can be one of the most distressing parts of this profile, because you can't always predict what you'll do in a situation even when you know your history. The dysregulation in the middle of the sequence — the stretch between threat signal and behavioral response — is where the most intense subjective experience lives: the feeling of being out of control, of wanting incompatible things, of being unable to get your system to settle. This is real, and it's physiological, not a failure of willpower.",

    'Why These Hit So Hard':
      "Your triggers hit hard because the conflict they produce isn't just emotional — it's architectural. When a threat fires and the response system can't settle on a direction, the whole nervous system goes into overdrive trying to resolve an irresolvable contradiction. That's exhausting in a way that's qualitatively different from the exhaustion of anxious activation or avoidant shutdown. It's not just intensity. It's the specific pain of not being able to find relief in either direction. The hits are also compounded by the unpredictability of your own responses, which generates a secondary layer of distress: shame, confusion about yourself, worry that you're too much or too broken or too inconsistent to sustain relationships. These aren't accurate assessments — they're the predictable byproduct of a nervous system that was shaped by unpredictable experiences. The other reason hits land so hard is that your threat-detection system is finely tuned to interpersonal signals, which means you're picking up on a lot — tone shifts, energy changes, micro-expressions — in a way that gives you genuine perceptual accuracy but also means you're processing more emotional data than most people. The sensitivity is real. The interpretive lens is running hot.",

    'Getting Ahead of the Pattern':
      "Getting ahead of your pattern is slower work than it is for the other three profiles, and that's worth naming directly rather than papering over it with optimism. The disorganized profile developed under conditions that the other patterns didn't, and updating the nervous system's calibration takes longer and requires more support — ideally including a therapist who understands attachment specifically. That said, there are things that genuinely move the needle. The first is building body-based regulation skills rather than cognitive ones. Because your dysregulation is physiological, cognitive reframing tends to be too slow and too rational to help in the moment. What helps more is direct intervention on the nervous system: breathing, movement, temperature, grounding in the physical present. The second is identifying your earliest signal — the very first moment when activation begins — and using that as the trigger for a pause rather than waiting until you're in full dysregulation. The earlier in the sequence you intervene, the more options you have. The third is finding relationships and contexts that provide genuine consistency over time, because your nervous system updates through accumulated experience of safety more than through insight.",
  },
};
