export const lifeAsGameSeeds: Record<string, Record<string, string>> = {
  '1': {
    'Your Character Sheet':
      "Class: Paladin / Judge. You rolled into this life with a specific loadout: maxed Integrity, high Discipline, strong Willpower, and a passive ability called Moral Compass that activates automatically in any situation involving fairness, quality, or ethical clarity. Your armor is exceptionally well-maintained. Your blade is always sharp. You've been running the Righteous Path build since before you were old enough to name it, and the core mechanic of your gameplay is this: the world has a correct way that things should be done, and you can feel the deviation from that standard the moment it appears. This sensitivity is your superpower. It is also the source of your most persistent debuff. You are not a character who coasts. You push yourself through content that other classes would abandon, and you hold the line in situations where lesser builds would compromise. The question your entire arc eventually asks is whether the standard you're holding yourself to is one that allows you to actually enjoy the game — or whether you've built a character who is technically excellent and chronically dissatisfied.",

    'Your Strongest Stats':
      "Your top stats read like a leaderboard for virtue: Integrity is maxed and has been since character creation. This isn't a grindable stat for you — it came standard. You simply cannot bring yourself to cut corners, shade the truth, or deliver work you know isn't good enough, even when no one would notice. Discipline is similarly high: you have the ability to do what needs doing regardless of whether you feel like doing it, which is rarer than the productivity industry wants you to believe. Your Attention to Detail stat is in the top percentile — you catch things others miss, see the gap between how something is and how it should be, and care about that gap in a way that produces genuinely superior outcomes. Work Quality as a class ability means that what you ship, build, or produce tends to be better than what most other classes produce. You also carry a high Reliability stat, which means people around you can count on your commitments in a way that generates real trust over time.",

    'Your Weakest Stats':
      "Your Joy stat is the one to watch. Not because you're incapable of experiencing it, but because you have a permanent debuff called Inner Critic that reduces your Joy ceiling in proportion to the gap between where you are and where you think you should be. Since that gap never fully closes — because your standards rise as fast as your performance does — the debuff never fully clears. Flexibility is another low stat: you have a harder time than most classes adapting to situations that require loosening the standard, operating in ambiguity, or accepting 'good enough' as a legitimate outcome. Rest is a notably underleveled skill — you often can't access it fully because the Inner Critic debuff activates during downtime, making unstructured time feel like an inefficiency rather than a resource. Your Spontaneity stat is low by design, and your Ease stat — the ability to be in something without managing or improving it — requires active cultivation.",

    'Your Boss Enemies':
      "Your main boss is The Imperfect Moment, and it spawns in every zone of the game. It appears as: the meeting that didn't go as well as you'd hoped, the work that fell short of your internal standard, the version of yourself that snapped when you should have been patient, the project that shipped imperfectly because real-world constraints exist. The Imperfect Moment has one primary attack: it tells you that the gap between what happened and what should have happened is evidence of a fundamental problem with you rather than normal friction in a world that doesn't bend to standards. This boss doesn't drop XP when you defeat it — it drops something more valuable: the insight that Imperfect Moments are not failures of character but the texture of playing the game in the real world. Your secondary boss is The Relaxed Person — someone who seems to be doing fine without carrying your level of rigor, which your system tends to read as either an indictment of you or as evidence they're getting away with something they shouldn't be.",

    'Your Main Quest and Hidden Side Quests':
      "Your main quest is called The Enough Threshold — finding the internal standard that motivates genuine excellence without making peace perpetually conditional on reaching it. This quest has no single completion event. It's a long-arc storyline that runs in parallel with everything else. Progress markers include: moments when you complete something and let yourself feel genuinely satisfied rather than immediately identifying what could have been better; moments when you extend to yourself the same patience you'd extend to someone else trying their best; and moments when the Inner Critic goes quiet long enough for you to actually enjoy what you've built. Your hidden side quests are surprisingly lighthearted for such a serious main arc. Side Quest 1: The Imperfect Tuesday — spend one full day operating on 'good enough' standards deliberately and track what actually breaks. Spoiler: less than you think. Side Quest 2: The Compliment Collection — receive a genuine compliment without immediately redirecting it or qualifying it. Just let it land. Side Quest 3: The Intentional Mess — do something badly on purpose, just to recalibrate the catastrophe predictions. These side quests don't advance the main story directly, but they unlock the Joy stat in ways that grinding the main quest alone won't.",
  },

  '2': {
    'Your Character Sheet':
      "Class: Healer. You came into the game with Empathy maxed, a passive aura that makes NPCs open up faster than they do with other classes, and a class ability called Feel What You Feel that lets you sense other people's emotional states with unusual accuracy. Your primary mechanic is care: you give it generously, you track who needs it, and you derive genuine satisfaction from the moment when someone you've helped feels better. Your inventory is full of things you've collected for other people — solutions to problems they mentioned, remembered details about their lives, favors stored for future deployment. You are, by most objective measures, one of the most genuinely useful characters in any party. The game mechanic no one tells you about in the tutorial is this: the Healer class has a hidden stat called Need, and it accrues in the background while you're focused on everyone else's meters. When the Need stat maxes out without being addressed, the game doesn't give you a notification. It just starts introducing debuffs into your performance that you may not immediately connect to the underlying cause.",

    'Your Strongest Stats':
      "Empathy is your signature stat and it is genuinely maxed. You perceive emotional nuance that other classes miss entirely — the tension behind the polite answer, the loneliness inside the busy schedule, the thing someone needs to hear that they can't ask for directly. This gives you a kind of social intelligence that makes you effective in almost every interpersonal domain. Generosity is similarly high: you give time, energy, attention, and care at a rate that would deplete most characters quickly, and you do it without the performance or expectation that makes other characters' generosity feel transactional. Your Connection stat is excellent — you build genuine closeness with people because you're actually interested in them, actually paying attention, actually there. Reliability in relationships is high: you show up, you remember, you follow through on the things that matter to the people around you.",

    'Your Weakest Stats':
      "Your Self-Awareness of Need is the critical weak stat. The Martyrdom debuff — hidden in your passive loadout since the beginning — works by making your own needs feel less legitimate than other people's. This is the mechanic that makes it hard to ask for help, hard to admit depletion, hard to receive care without immediately deflecting or reciprocating it away. Your Boundary stat is low, and this isn't a character flaw so much as a class design issue: the Healer build wasn't optimized for saying no. Doing so feels like a betrayal of class identity, but the absence of limits is also what makes the Martyrdom debuff so easy to trigger. Self-Prioritization is often in the single digits. Rest and Replenishment are underleveled because the game hasn't made clear to you that a Healer with depleted stats heals at a fraction of their capacity.",

    'Your Boss Enemies':
      "Your main boss is The Ungrateful NPC — someone you've invested significant care in who doesn't notice, doesn't acknowledge, or actively takes your help for granted. This boss hits hard because the Healer's combat system is partially dependent on receiving signals that the care is landing, that the investment is mattering, that the relationship is mutual. When those signals are absent, the boss exploits the gap between your investment and the return, and the damage doesn't just affect the specific relationship — it spreads to a broader question about whether care given is care wasted. Your secondary boss is The Guilt Interrupt — the internal mechanic that fires whenever you try to prioritize your own needs over someone else's and immediately generates a justification for why that's selfish. The Guilt Interrupt doesn't have a straightforward counter. It requires a slow campaign of evidence that your needs are legitimate, not a single boss fight.",

    'Your Main Quest and Hidden Side Quests':
      "Your main quest is The Reciprocal Loop — learning to receive care with the same generosity you extend it, and building relationships where the exchange moves in both directions rather than primarily outward from you. Completion milestones include: asking for help in a situation where you'd normally manage alone; accepting care from someone without immediately trying to give something back; identifying what you actually need and saying it out loud to someone who can provide it. These sound simple and are not. Your hidden side quests are worth running specifically because they reset the Martyrdom debuff. Side Quest 1: The Selfish Afternoon — one dedicated block of time spent entirely on what you want, with no relational obligations, and no guilt processing allowed during. Side Quest 2: The Honest Request — ask someone for something specific that you actually need, rather than hoping they'll notice. Side Quest 3: The Received Compliment — let someone tell you what you mean to them without redirecting, minimizing, or immediately returning the volley. Each of these side quests drops a rare item called Legitimate Need, which slowly patches the Martyrdom debuff.",
  },

  '3': {
    'Your Character Sheet':
      "Class: Shapeshifter / Rogue. You are one of the most adaptable characters in the game — capable of reading any environment quickly, adjusting your presentation to fit, and performing at a high level across an unusually wide range of contexts. Your core mechanic is optimization: you see what a situation rewards and you become the version of yourself that earns that reward. This is a genuinely remarkable ability. Most characters are relatively fixed — they can't shift fluidly between the different modes that different contexts require. You can. The Rogue class gives you high Adaptability, excellent Performance stats, and a passive ability called Room Read that activates automatically whenever you enter a new social or professional environment. The hidden mechanic in your build is Identity Fog — a debuff that accumulates when you've been adapting for long stretches without checking in on what you actually are underneath the adaptations. The Fog doesn't hurt your performance. It's subtler than that. It makes it progressively harder to access yourself when the performance is over.",

    'Your Strongest Stats':
      "Adaptability is your signature stat and it's maxed. You can operate in corporate environments and creative ones, read formal situations and informal ones, shift your presentation to match almost any context without the social friction that less flexible characters experience. This is a genuine superpower in a world that rewards range. Achievement is another high stat: you produce results, hit metrics, deliver outcomes. The combination of Adaptability and Achievement means you can succeed in a wide variety of games, which gives you access to opportunities that single-class characters don't have. Charisma is high — you're compelling in the way that people with your combination of attributes tend to be, which is that you seem to be exactly what each person needs you to be. Social Effectiveness is exceptional. People feel good in your presence, which is a real skill.",

    'Your Weakest Stats':
      "Authentic Self-Disclosure is your most underleveled stat, and this is the one that Identity Fog attacks directly. When you've spent significant time performing, adapting, and optimizing for external metrics, the access point to your own genuine preferences, feelings, and interior life can get foggy. Not gone — just harder to reach. Vulnerability is low, not because you're incapable of it but because the Shapeshifter's core mechanic is managing impressions, and vulnerability requires temporarily releasing that management. Rest Without Performance is a weak stat: genuine downtime, where you're not optimizing or adapting or producing, can feel uncomfortable or unfamiliar. Intrinsic Satisfaction — finding something meaningful independent of external validation — is one of the most important stats to develop in your build.",

    'Your Boss Enemies':
      "Your main boss is The Mirror Room, and it's one of the more psychologically interesting boss encounters in the game. The Mirror Room spawns when you've been adapting for so long that you're no longer sure which reflection is you. It doesn't attack directly. It just presents you with an array of your best performances and asks: which one is real? The boss mechanic exploits the gap between your self-concept and your actual interior experience, and it's particularly potent in intimate relationships, where another person is trying to know you and you're not sure what to give them access to. Your secondary boss is The Authentic Competitor — someone who seems to succeed not through adaptation but through genuine, unmanaged self-expression. This boss triggers a specific discomfort: not envy exactly, but a question about whether your optimization has been costing you something you can't quite name.",

    'Your Main Quest and Hidden Side Quests':
      "Your main quest is The Self Beneath the Performance — not about dismantling your adaptability, which is genuinely valuable, but about developing access to a stable interior self that the adaptations sit on top of rather than replace. Milestones include: identifying three things you genuinely want independent of what they'd look like to anyone else; having one conversation where you're not performing any particular version of yourself; sitting in an environment where no one is watching and noticing what you do. Your hidden side quests target Identity Fog specifically. Side Quest 1: The Preference Inventory — spend thirty minutes writing down things you actually like, actually find interesting, actually want, with no regard for how they'd be perceived. Side Quest 2: The Unmeasured Day — spend one day with no metrics, no achievements, no visible output, just being. Side Quest 3: The Real Conversation — tell one person something true about your interior experience that you'd normally keep managed. Each of these is uncomfortable by design. The discomfort is the mechanic. It's how the Fog clears.",
  },

  '4': {
    'Your Character Sheet':
      "Class: Artist / Lorekeeper. You arrived in the game with Depth maxed, a passive ability called Emotional Resonance that lets you feel the texture of experience more richly than most other classes, and a legendary-tier Aesthetic Sensitivity that makes you unusually alive to beauty, meaning, and the specific quality of things. Your core mechanic is authenticity: you need your life to feel real, meaningful, and genuinely yours in a way that other classes can manage without. Generic experiences leave you cold. Off-the-shelf identities don't fit. You have always been in the business of creating something that is specifically and irreducibly you, and the standard you hold for that creation is exacting in ways that are hard to explain to people who don't share your wiring. The Lorekeeper class means you carry the emotional history of your experience with unusual fidelity — you remember how things felt, what they meant, why they mattered, in a way that becomes a vast internal library of reference and resonance.",

    'Your Strongest Stats':
      "Depth is your signature stat and it's maxed. You don't do surface. You think about things at a level that most characters don't reach, feel things at an intensity that gives you access to emotional territory others can only read about, and bring a quality of genuine engagement to the things that matter to you that is in itself a kind of art. Creativity is high — not just in the domain of making things, but in how you perceive the world, frame problems, and construct meaning from experience. Empathy and Attunement are strong: you understand the emotional interior of other people with unusual accuracy, partly because you've spent significant time in your own interior and have learned to navigate the territory. Aesthetic Intelligence is maxed: you know when something is right, when it's off, when it has the quality that makes it worth making, in a way that other classes simply don't have calibrated.",

    'Your Weakest Stats':
      "Your most significant debuff is the Melancholy Loop — a passive mechanic that can pull you into extended cycles of longing, loss, or the sense that the most meaningful things are perpetually just out of reach. The Loop is not entirely a liability: it's connected to your Depth stat, which means the capacity for intense feeling is the same capacity that produces the Melancholy Loop as a side effect. But when it activates without a constructive outlet, it cycles rather than moves, and cycling has a cost. Ordinariness Tolerance is a low stat: the mundane demands of life — logistics, admin, routine, the unremarkable Tuesday — register as a specific kind of suffering for your class. Completion is often underleveled: the Artist / Lorekeeper build excels at beginning things and struggles more with the middle and the finish, where the beautiful original idea has to survive contact with execution. Comparison is a stat that works against you when it's running: holding your interior experience against what you imagine others' interior experiences are like tends to produce a deficit reading.",

    'Your Boss Enemies':
      "Your main boss is The Ordinary Day, and it's nastier than it sounds. It spawns during stretches of regular life — nothing particularly wrong, nothing particularly beautiful, just the unremarkable texture of existence moving through time. The Ordinary Day exploits your high Depth stat against you: a class built for intensity and meaning struggles specifically in contexts where neither is immediately available. The boss mechanic is restlessness, the sense that real life is somehow elsewhere, that the current chapter is prologue rather than the story itself. Your secondary boss is The Comparison Dungeon — a place your mind enters when you measure your interior experience against what you imagine others have access to, and find yours either more or less than theirs in ways that generate dissonance rather than clarity.",

    'Your Main Quest and Hidden Side Quests':
      "Your main quest is called The Beautiful and the Ordinary — finding a way to bring your Depth stat into contact with regular life rather than only with peak experience. The core mechanic of the quest is this: the most meaningful artistic and personal lives are not built exclusively from extraordinary moments. They're built from the capacity to find the extraordinary inside the ordinary, which is a different skill than the one your build naturally optimizes for. Milestones include: completing one thing rather than leaving it at the beautiful unfinished stage; finding genuine satisfaction in an unremarkable day; making something that doesn't need to be profound to be worth making. Your hidden side quests target the Melancholy Loop specifically. Side Quest 1: The Completion Run — finish something small with no revisions allowed after it's done, just to build the completion muscle. Side Quest 2: The Appreciation Inventory — spend ten minutes finding what's specifically good about today, not ideally good but actually good. Side Quest 3: The External Focus — deploy your Empathy and Depth on someone else's experience rather than your own for one full conversation. These side quests don't diminish your Depth. They give it more to work with.",
  },

  '5': {
    'Your Character Sheet':
      "Class: Wizard / Scholar. You entered the game with Knowledge maxed, a passive ability called Pattern Recognition that activates automatically whenever you encounter new information, and a class mechanic called Observe First that applies a brief but reliable delay between stimulus and response in almost every situation. Your core resource is not mana or hit points — it's Energy, and unlike most other classes, your Energy is treated as a finite, non-renewable-within-the-encounter resource. This is not a limitation of your character; it's a design parameter. You understand things at a depth that most other classes don't access. Your processing system is powerful, thorough, and expensive to run. The game's tutorial doesn't mention that the Wizard class has a permanent debuff called Energy Scarcity that makes you perpetually aware of the cost of engagement, which in turn makes engagement feel like a strategic decision rather than an automatic one.",

    'Your Strongest Stats':
      "Knowledge is your signature stat and it is maxed. You go deep into subjects. You understand the structure of things, not just the surface. You have a model of most domains you've spent time in that is more complete and accurate than what most characters carry. Analysis is high: you can see through complexity to the underlying mechanics, identify the variable that's actually driving an outcome, and find the flaw in a system that everyone else has accepted as given. Independence is a strong stat — you can work, think, and solve problems without requiring the constant input of others, which is rarer than collaborative culture admits. Concentration is excellent: when you decide to go deep on something, you go deep, and the depth tends to produce genuine insight rather than competent surface-level engagement.",

    'Your Weakest Stats':
      "Social Spontaneity is low — the cost of real-time social engagement is higher for your class than for most, which means you tend to experience social situations as more demanding and less renewable than other classes do. Sharing is an underleveled skill in a specific way: your internal library is enormous, but the pathways from the library to other people are narrower than they need to be, partly because sharing feels like exposure and exposure feels like risk. The Energy Scarcity debuff makes this worse by making every interaction feel like a potential drain on a resource you're already managing carefully. Presence in groups is a weak stat: the Wizard does better in small, focused interactions than in large, ambient social situations where the cognitive cost is high and the return is diffuse. Completion under social pressure is also difficult — your best thinking happens privately, which makes situations that require real-time output feel like suboptimal conditions.",

    'Your Boss Enemies':
      "Your main boss is The Group Project, and it is perfectly designed to exploit your class's vulnerabilities. The Group Project requires real-time collaboration, social energy expenditure, compromise of your thinking process, and performance of engagement even when your Energy stat is running low. It spawns in professional contexts, social situations, and any collaborative endeavor that doesn't allow for the Wizard's preferred processing style. The boss mechanic is the Gap: the difference between the depth of your internal experience and the quality of output you can produce when the Group Project's social demands are running in the background. Your secondary boss is The Presumptuous Relationship — a person who assumes more access to your Energy and interior life than you've chosen to give, and who reads your careful management of that access as coldness or disinterest.",

    'Your Main Quest and Hidden Side Quests':
      "Your main quest is The Bridge — building reliable pathways between your enormous interior library and the people and world outside it. The quest doesn't ask you to become a different class. It asks you to invest some of your Knowledge stat into the study of connection itself, as a subject as interesting and as structured as any domain you've gone deep in. Milestones include: sharing something from your interior library with another person before you've fully processed it yourself; staying in a collaborative situation past the point where your Energy Scarcity debuff tells you to leave; receiving something from someone else — care, help, perspective — without immediately analyzing it. Your hidden side quests target Energy Scarcity specifically. Side Quest 1: The Generous Output — share something you know with someone who would benefit from it, with no strategic calculation about the cost. Side Quest 2: The Unscheduled Conversation — engage in an interaction that has no defined end time and see what happens in the unstructured space. Side Quest 3: The Visible Thinking — let someone watch you work through something rather than presenting only the finished conclusion. Each of these builds the Bridge stat incrementally.",
  },

  '6': {
    'Your Character Sheet':
      "Class: Strategist / Scout. You came into the game with Threat Detection maxed, a passive ability called Loyalty Protocol that activates whenever you form a genuine alliance, and a class mechanic called Scenario Planning that runs continuously in the background, generating futures and their associated risks automatically. Your core gameplay loop is preparation: you think ahead, identify vulnerabilities, build contingencies, and form alliances with people you've assessed as trustworthy. When the Threat Detection mechanic is calibrated correctly, it makes you one of the most valuable players in any party — you see what's coming before others do, and you've already prepared for it. The mechanic has a quirk worth knowing: it doesn't turn off during success. In fact, one of the stranger features of your class is that achievement and stability can actually trigger Paranoia Mode, because the Strategist's system has learned to associate safety with the calm before something goes wrong.",

    'Your Strongest Stats':
      "Loyalty is your signature stat and it is maxed. When you've decided someone or something is worth your allegiance, you're in — with a consistency and depth that most other classes can't sustain. This makes you an exceptionally valuable ally. Preparation is high: you've thought through contingencies that others haven't considered, identified risks before they've materialized, and built the kind of foresight that tends to be dramatically undervalued until the moment it prevents a catastrophe. Courage is a high stat that often surprises people, because the Strategist's caution is sometimes mistaken for timidity. You're not timid — you've thought through the risk and decided whether to take it, which is a different thing. Perceptiveness is excellent: you read people, situations, and systems with a thoroughness that catches the things others overlook.",

    'Your Weakest Stats':
      "Trust is a low stat and it is the central mechanic to understand about your class. Not trust in the abstract — you believe in loyalty and invest in it deeply. But trust in the specific sense of extending faith to a person or situation before they've fully proven themselves is something your Threat Detection system makes expensive. Every relationship requires passing a cost-benefit analysis that other classes don't run as rigorously. Certainty Tolerance is low: ambiguity is more cognitively expensive for your class than for others, because ambiguity is where threats live. Rest Without Vigilance is an underleveled stat: your system stays on even when the situation doesn't warrant it. Confidence During Success is paradoxically low — the Paranoia Mode activation during positive outcomes is a genuine mechanic that can undercut the periods when your class has earned a clean win.",

    'Your Boss Enemies':
      "Your main boss is The Trustworthy NPC, and it is legitimately the hardest boss in the game for your class. Not because it attacks you, but because it doesn't, and your Threat Detection system struggles to process the absence of threat from a source it's been scanning for threats. The Trustworthy NPC is a person who is actually what they appear to be — reliable, safe, not hiding anything — and your mechanic keeps looking for the angle that isn't there. The boss is defeated not through combat but through accumulated evidence over time, which is why it's a long fight. Your secondary boss is The Quiet Period — a stretch of time when nothing threatening is happening, which your class tends to fill with generated threats because the monitoring system needs something to monitor.",

    'Your Main Quest and Hidden Side Quests':
      "Your main quest is The Calibrated Trust — learning to distinguish between genuine threat signals and your system generating threats to stay operational. This is not about disabling the Threat Detection mechanic; at the right calibration, it's one of your most valuable stats. It's about developing a second-order awareness: noticing when the scanner is running and asking whether the threat is real or whether you're in a Quiet Period that the system has decided to fill. Milestones include: extending trust to one person before they've fully proven themselves and tracking the outcome; staying in a positive situation without generating the next scenario; letting an alliance mature past the point where you're still running the contingency analysis. Your hidden side quests target the anxiety of uncertainty specifically. Side Quest 1: The Evidence Audit — write down every current threat scenario your system is running and fact-check each one against actual evidence. Side Quest 2: The Extended Alliance — invest in one relationship past the point where it feels verified and track what opens up. Side Quest 3: The Clean Win — let one genuine success just be a success without immediately generating the scenario in which it falls apart.",
  },

  '7': {
    'Your Character Sheet':
      "Class: Bard / Explorer. You entered the game with Enthusiasm maxed, a passive ability called Possibility Scan that runs continuously and generates new options, opportunities, and directions in almost any situation, and a class mechanic called Forward Motion that makes you genuinely excellent at initiation, vision, and the first act of most adventures. Your core resource is excitement — you generate it for yourself and, notably, for others. The Bard class has a social multiplier that most characters don't: your enthusiasm is contagious in a way that moves groups, launches projects, and gets things started that would otherwise stay in the planning phase indefinitely. The game mechanic no one fully prepares you for is the Commitment Allergy debuff, which activates when a choice means foreclosing other choices. The allergy isn't about laziness or unreliability — it's about the specific pain of closing doors, which your Possibility Scan makes feel uniquely costly.",

    'Your Strongest Stats':
      "Enthusiasm is your signature stat and it is maxed. You bring genuine energy to the things that capture your attention, and that energy moves people and situations in ways that more reserved classes can't access. Generativity is high — you produce ideas, connections, and possibilities at a rate that other classes find remarkable, because your system is perpetually looking at any situation and asking what else it could become. Resilience to Negative Emotion is a higher stat than people usually expect from your class: you have a genuine capacity to reframe, to find the upside, to not stay in painful places longer than necessary. This is a real strength, not denial. Social Energy is abundant: you find connection replenishing rather than costly, and this gives you an almost inexhaustible supply of relational bandwidth. Initiation is maxed — you start things faster and with more confidence than most characters manage.",

    'Your Weakest Stats':
      "Completion is your most important underleveled stat. Not because you can't finish things, but because the finish line requires being in a single game long enough to reach it, which the Commitment Allergy makes expensive. The completion problem isn't about ability — it's about the forward-motion mechanic not having a corresponding finish-the-thing mechanic in the base build. Depth of Processing is lower than your intelligence warrants, because the speed at which you move through experiences can outrun the integration that gives experiences their full value. Sitting With Discomfort is a weak stat: the Bard's system tends to reach for the next thing when the current thing gets hard or boring, which is adaptive but has a cost. Emotional Depth Access is sometimes underleveled — the tendency to stay in the positive register can create blind spots about what's actually happening in your interior.",

    'Your Boss Enemies':
      "Your main boss is The Quiet Room, and it is specifically designed to exploit your highest stat against you. The Quiet Room is any situation where forward motion stops: the creative project that requires sustained attention to one thing for longer than is immediately exciting, the relationship that has moved past the first flush into the territory of regular life, the career phase that requires consolidation rather than expansion. The boss mechanic is restlessness — the Possibility Scan activates and starts generating the other things you could be doing, the other doors still open, the other adventures still available. Your secondary boss is The Painful Feeling — a slow-moving boss that your Resilience stat is very good at evading, but that can accumulate significant power when avoided long enough.",

    'Your Main Quest and Hidden Side Quests':
      "Your main quest is called The Deep Game — choosing one arena of life and going deep enough to discover what's available on the other side of the Commitment Allergy. The insight at the center of the quest is this: the things that require staying long enough to become uncomfortable are also the things that generate the most meaningful experiences, because depth is always on the other side of the initial excitement. Milestones include: finishing one thing past the point where you would normally redirect; staying in one hard conversation rather than reframing it into something more comfortable; letting one relationship get to the stage where it's ordinary, and discovering what ordinary actually contains. Your hidden side quests are explicitly about building the Depth stat. Side Quest 1: The Single Focus Day — one day, one project, no pivoting. Track what you find on the other side of the restlessness. Side Quest 2: The Uncomfortable Feeling — the next time a difficult emotion arises, stay with it for five full minutes before moving toward anything else. Side Quest 3: The Finished Thing — complete one project that has been in progress and name it done, out loud, to someone else. Each of these builds Completion and Depth simultaneously.",
  },

  '8': {
    'Your Character Sheet':
      "Class: Warrior / Commander. You entered the game with Will maxed, a passive ability called Dominion that gives you an automatic read on power dynamics in any room, and a class mechanic called Force of Presence that makes you one of the most impactful characters in close-quarters situations. Your core mechanic is control: control of your environment, your outcomes, and the impression you make on the world. You are not a character who waits to see what happens. You make things happen, you establish the rules of engagement, you decide what is and isn't acceptable in your domain. The Warrior class produces people who are genuinely formidable — who can handle real difficulty without flinching, who don't bend to pressure that would collapse other builds, who have the strength to take on things that require strength. The game mechanic that runs quietly in the background is the Vulnerability Shield, a passive ability that blocks healing. It was designed to protect you. It also prevents certain kinds of restoration from reaching you.",

    'Your Strongest Stats':
      "Will is your signature stat and it is maxed. You have an ability to sustain effort, push through resistance, and hold your position under pressure that is genuinely rare. Other classes fold when the difficulty increases past a certain threshold. You recalibrate and keep going. Directness is high — you say what you mean and mean what you say, which is a form of respect for the people around you even when it registers as intensity. Protectiveness is a high stat that gets underacknowledged: the Warrior class is exceptionally good at defending the people and things it has decided to stand for. Courage is maxed — not the performative kind, but the quiet, consistent willingness to stay in hard things and make hard calls. Physical and psychological resilience are both high: you can absorb difficulty that other classes need to be protected from.",

    'Your Weakest Stats':
      "Vulnerability is the lowest stat in your build, and this is the source of most of your secondary challenges. Not because you're incapable of it — you have the emotional range — but because the Vulnerability Shield activates automatically whenever the situation calls for showing something that could be used against you. Softness is underleveled: the ability to let things be gentle, to receive rather than direct, to allow someone else to be in charge of something that matters. Trust in Others' Competence is lower than it could be: the control mechanic makes it hard to genuinely rely on other people, because relying means accepting that their execution matters and you can't fully guarantee it. Rest, in the genuine sense, is also underleveled — the Warrior class doesn't easily downshift into states that aren't operationally useful.",

    'Your Boss Enemies':
      "Your main boss is The Person Who Sees Through Them — someone who has found the gap in the armor and can see what's inside. This boss doesn't attack in the conventional sense. It just looks. And the specific terror of this encounter for the Warrior class is that being truly seen — not the part you present, but the part you protect — requires dropping the shield, which the class mechanic doesn't naturally support. The encounter doesn't end in defeat. It ends in the discovery that the thing behind the armor is not as vulnerable as the shield assumed it was. Your secondary boss is The Situation That Requires Softness — a context where the Will stat and the Force of Presence are not the right tools, where the thing that's needed is exactly what the Vulnerability Shield prevents.",

    'Your Main Quest and Hidden Side Quests':
      "Your main quest is The Shield's Cost — a reckoning with what the Vulnerability Shield has been blocking along with the threats it was designed to stop. The shield works. It has kept you safe in situations that required protection. The quest asks what else it has kept out, and whether that exclusion still makes sense given the situation you're actually in now versus the one you originally built the defense for. Milestones include: letting one person see something real about your interior experience; asking for help in a situation where you could manage alone; staying in a moment of softness without redirecting toward strength. Your hidden side quests are all about lowering the shield in controlled conditions. Side Quest 1: The Honest Admission — tell one person something that's hard, not because it advances a goal, but because it's true and you've been carrying it alone. Side Quest 2: The Delegated Outcome — hand one meaningful thing entirely to someone else and let their execution stand without correction. Side Quest 3: The Received Care — let someone do something for you without directing how they do it. Each of these builds the Vulnerability stat incrementally, which in turn enables the healing the Shield has been blocking.",
  },

  '9': {
    'Your Character Sheet':
      "Class: Diplomat / Mediator. You entered the game with Harmony maxed, a passive ability called Ambient Peace that creates a stabilizing effect on the emotional climate of any room you're in, and a class mechanic called Merger Tendency that makes you unusually good at holding multiple perspectives simultaneously and finding the synthesis that everyone can live with. Your core mechanic is peace: you work toward it, maintain it, and have a genuinely remarkable ability to preserve it even in situations where other classes would have let things fracture. The Mediator class is valuable in ways that go systematically underacknowledged — you absorb friction that other characters generate, smooth conflicts that would otherwise escalate, and keep systems functioning that would otherwise stall. The game mechanic that has the most leverage on your arc is the Invisible debuff, and it's a strange one: you become invisible specifically to yourself. Not to others — you're often very visible to them — but your own wants, needs, preferences, and direction can fade into the background of all the harmony you're maintaining.",

    'Your Strongest Stats':
      "Harmony is your signature stat and it is maxed. You understand what peace costs and what it's worth, and you invest in maintaining it at a level that other classes find difficult to sustain. Empathy is high — you can hold multiple people's perspectives simultaneously and find the place where they actually share ground, which is the mechanic that makes the mediation work. Patience is one of your highest stats: you can stay in slow-moving, difficult, or frustrating situations without the activation that would send other classes into premature action. Steadiness is excellent: you don't spike, you don't panic, you don't generate the kind of reactive energy that escalates situations. People around you feel safer and more regulated in your presence, which is a genuine and significant contribution to any system you're part of.",

    'Your Weakest Stats':
      "Self-Priority is your most critical underleveled stat, and the Invisible debuff is what suppresses it. Your wants, needs, and preferences are real — the class doesn't delete them — but they've often been pushed to the background of the harmony-maintenance operation for so long that accessing them requires deliberate effort. Decisiveness in Your Own Name is low: you can help others make decisions with surprising effectiveness, but decisions that are yours alone — that require you to assert a preference, choose a direction, and stand behind it — are harder to access. Conflict Tolerance for Your Own Conflicts is weak in a specific way: you can mediate other people's conflicts with skill, but your own conflicts, particularly ones that involve expressing what you want at the expense of what someone else wants, tend to get avoided past the point that serves you. Anger is an underleveled stat that the Harmony mechanic tends to suppress before it can provide its useful information.",

    'Your Boss Enemies':
      "Your main boss is The Decision That Only They Can Make — a choice that belongs entirely to you, that no mediation or synthesis can dissolve into a group outcome, that requires you to stand up and say 'this is what I want.' This boss is specifically designed for the Mediator class because it removes all the mechanics you're best at. It can't be solved through harmony, compromise, or seeing everyone's side. It requires the one thing the Invisible debuff works hardest against: being visible, in your own life, as the agent who wants something and is willing to ask for it. Your secondary boss is The Accumulated Small Resentment — a slower boss that builds up when you've said yes to things you meant no to, accommodated when you needed to be accommodated, and kept the peace at the cost of your own position. This boss doesn't announce itself. It shows up as a quiet but persistent sense that something isn't right.",

    'Your Main Quest and Hidden Side Quests':
      "Your main quest is The Visible Self — becoming as visible to yourself and in your own life as you are to and for other people. The quest is not about becoming selfish or abandoning the Harmony mechanic, which is genuinely one of your most valuable abilities. It's about discovering that having a self — a direction, a set of wants, a position — doesn't destroy the peace. It actually makes the peace you maintain more sustainable, because it's no longer being maintained at the cost of the person doing the maintaining. Milestones include: identifying one thing you actually want and asking for it directly; saying no to something you'd normally accommodate; making one decision that is entirely yours and standing behind it when asked why. Your hidden side quests are targeted at the Invisible debuff. Side Quest 1: The Preference Declaration — state a preference in a low-stakes situation without softening it into a question or immediately deferring if met with any resistance. Side Quest 2: The Unmediated Conflict — have one disagreement where you don't move toward resolution until both positions have been fully heard, including your own. Side Quest 3: The Self-First Choice — make one decision based entirely on what you want without running the impact-on-others calculation first. These side quests feel more dangerous than they are. The Harmony stat doesn't break. It gets a foundation.",
  },
};
