export const mentalEnergySeeds: Record<string, Record<string, string>> = {
  low: {
    'Your Mental Energy Profile':
      "Your mental energy profile is organized around a fundamental fact about how your nervous system works: social interaction is a resource expenditure, not a resource replenishment. This isn't shyness, and it's not social anxiety, and it's not that you don't like people — though it can be misread as any of those. It's a neurological reality. When you spend extended time in social environments, you're running a cognitive process that's expensive for you: managing impressions, tracking conversational dynamics, monitoring tone and reception, staying responsive to others. You do this capably. You may even do it well. But it costs something that solitude restores and more interaction depletes. The upshot of this wiring is that your cognitive horsepower is most available when it's not being split between social processing and whatever else you're trying to think about. You think better alone. You process more deeply in quiet. You make better decisions after time to yourself. This isn't a limitation that needs correcting — it's a resource allocation pattern that, if you design around it, gives you genuine advantages in depth of thought, quality of attention, and sustained focus. The people who do the most interesting intellectual work often have this wiring. The challenge isn't the wiring itself; it's living in a world that frequently misreads it.",

    'When Your Mind Works Best':
      "Your mind works best in conditions that most people underestimate: uninterrupted, relatively quiet, with enough time that you don't have to rush the depth. You're not someone who does their best thinking in a brainstorming session or an open office or a meeting with twelve people talking over each other. The cognitive state you're after requires a settling period — a transition from the social demands of the day into something more interior and focused — and that settling period gets constantly interrupted in environments designed for extroverted work styles. When you get the conditions right, what becomes available is something worth protecting: the ability to follow a line of thought all the way to its end, to notice the second and third-order implications of something rather than just the surface, to sit with a problem long enough that it starts to reveal its actual structure. This is genuinely rare. Most people jump to solutions before they've fully understood the problem. You, given the right conditions, will actually think it through. The timing matters too — some introverts do their deepest thinking in the early morning before the social demands of the day begin; others are better late at night after the day has wound down. Knowing your window and protecting it is more valuable than almost any other productivity strategy you could adopt.",

    'What Drains You':
      "The drain sources in your profile are specific and consistent. Extended social time without recovery breaks is probably the biggest one — not a single conversation but the sustained, hours-long presence in social environments that leaves you feeling hollowed out by the end. The duration matters as much as the intensity; an hour of intense conversation is often less depleting than four hours of moderate social demands. Open-plan environments, where you're constantly available to interruption and ambient social stimulation, are a chronic drain that's easy to underestimate precisely because it's constant rather than acute. You adapt to it, but you're paying a tax the whole time. Meetings — particularly long ones, or ones where your primary role is to listen and respond rather than to do focused work — are high on the drain list. The specific cost there is being required to be socially present at a high level for a sustained period without the ability to retreat. Unexpected demands on your social attention, particularly when you were mentally in a deep-focus state, are disproportionately costly — the interruption doesn't just cost the time of the interruption, it costs the recovery time needed to get back into the state you were in. That's why your reaction to being interrupted can feel bigger than the interruption seems to warrant.",

    'Your Cognitive Rhythm':
      "Your cognitive rhythm tends toward longer cycles than the typical work environment assumes. You need more ramp-up time to reach peak focus, but you also sustain that focus longer once you get there, and you produce better output in the sustained stretch than you would in a series of shorter sprints. This means the standard advice about working in 25-minute Pomodoro blocks may be somewhat wrong for you — you might find that 25 minutes is just when you're actually getting somewhere, and breaking there costs more than it saves. A rhythm that works better is likely: longer protected blocks of 90 minutes to two hours, real recovery time between them that involves genuine solitude rather than passive social media consumption, and deliberate sequencing of your most cognitively demanding work into the periods after you've had recovery time. The recovery piece is worth taking seriously. For you, a lunch break that involves socializing doesn't function as a break. A walk alone, a period of quiet, something that restores rather than expends — this is what makes the afternoon cognitive block possible. Without genuine recovery, your later hours are producing work at a fraction of your actual capacity.",

    'Designing Your Environment for Peak Thinking':
      "Designing your environment is probably the highest-leverage thing you can do for your cognitive output, and the changes don't need to be dramatic. The most important thing you can do is create reliable access to uninterrupted blocks — which means being honest and specific with yourself and others about what you need and when. This isn't a preference to be worked around; it's an infrastructure requirement. If you work in an environment that doesn't give you protected time, the work of advocacy for that time is worth doing. Noise is worth taking seriously as a design variable. Ambient conversation is particularly costly because your brain will try to process the language whether you intend it to or not, which means open-plan environments with talking are running a background drain that silence or even music doesn't produce. Headphones help but don't fully solve it. Private space, or the option of it, is genuinely different. The transition design matters too — you need a ritual that reliably bridges from social-mode to deep-focus-mode, and the specific ritual matters less than its consistency. Some people use a walk, some use a specific playlist, some use a cup of coffee made in a particular way. What you're doing is giving your nervous system a reliable cue that it's safe to go deep now, that no one is about to need something from you. Once that cue is established, the settling time shortens.",
  },

  medium: {
    'Your Mental Energy Profile':
      "Your mental energy profile sits in the contextually flexible middle, which sounds like a bland place to be but is actually one of the more interesting configurations. You're not strongly energized by social interaction, and you're not strongly drained by it. You can work well in collaborative environments and you can work well alone. You can do extended social time without the depletion that would hit an introvert, and you can do extended solitude without the cognitive stagnation that an extrovert might experience. This flexibility is real, and it's genuinely useful. But it comes with a less-discussed complication: because you don't have a strong, clear signal pulling you toward either solitude or social engagement, you can end up in neither state optimally. You're the person who can work in a coffee shop or in a quiet office, which means you may not have thought carefully enough about which is actually better for which kind of work. The chameleon quality is an asset, but only if you develop enough self-knowledge to direct it deliberately. The medium profile tends to produce people who are good at a wide range of tasks but whose peak performance is more domain-dependent than wiring-dependent. The question isn't introvert or extrovert. It's: what are you trying to think about, and what does that specific task actually need?",

    'When Your Mind Works Best':
      "For you, the answer to when your mind works best is more nuanced than it is for the high or low ends of the spectrum — and also more interesting. Your peak thinking isn't primarily determined by the social temperature of your environment. It's determined by how interested you are in what you're working on and what the stakes are. Put you on something that genuinely captures your attention, and you'll find focus in a wide variety of conditions. Put you on something that doesn't, and no amount of environmental engineering will produce your best work. This stakes-and-interest sensitivity means that engagement is your primary performance variable rather than solitude-versus-stimulation. You might notice that your best thinking happens in bursts that correspond to moments of genuine curiosity — when you've encountered a problem that actually puzzles you, when the stakes feel real, when there's something at the end of the cognitive effort that you actually want. The implication is that the most useful question for you when you're trying to do good thinking isn't 'where should I work?' It's 'am I actually engaged with this, and if not, what would make me?' Finding ways to manufacture genuine interest in the work — or structuring your work so that the engaging parts get your best hours — gives you more return than redesigning your physical environment.",

    'What Drains You':
      "Your drain sources are less predictable than they are for the clear ends of the spectrum, which means they require more self-observation to map. What drains you is less about social volume and more about things like: sustained engagement with work that you find meaningless, long stretches in roles or tasks that don't use your actual capabilities, social interactions that feel performed rather than genuine, and the specific exhaustion of being in environments where you have to be someone slightly different from who you actually are. The adaptability that's central to your profile can become its own drain source: because you're flexible and can show up adequately in most contexts, you may spend significant energy showing up adequately in contexts that don't actually suit you, rather than advocating for the ones that do. The drain accumulates slowly and can be hard to attribute accurately because no single environment is obviously wrong for you. You're not depleted after every social interaction the way a strong introvert might be. But you might notice a deeper exhaustion that builds over weeks in a role or environment that's using your flexibility as a workaround rather than giving you room to operate at your actual level.",

    'Your Cognitive Rhythm':
      "Your cognitive rhythm is probably more variable than you've given yourself credit for, because it tracks interest and engagement more than time of day or social context. You may have attributed inconsistency in your focus and output to willpower or discipline when it was actually a signal about engagement levels. The days when your thinking is sharp and connected and feels effortless tend to be days when you're working on something that actually has your attention. The days when you're slow and distracted and can't quite get traction tend to be days when you're working on something that doesn't. This isn't a character issue. It's information. The strategic implication is that learning to identify what genuinely engages you — not what you think should engage you, not what you're supposed to find interesting, but what actually pulls your attention — is more valuable than developing better focus habits. Your rhythm responds to the right material more than to the right conditions. Finding more of the right material, or reframing existing material to find the genuine puzzle in it, is your highest-leverage cognitive strategy.",

    'Designing Your Environment for Peak Thinking':
      "Designing your environment well means resisting the templates designed for either end of the spectrum. You don't need to protect yourself from social exposure the way an introvert does, and you don't need to surround yourself with stimulation and conversation the way an extrovert might. What you need is something different: flexibility, options, and the ability to match the environment to the task. For focused, deep work, you'll probably do better in quieter conditions — not because social stimulation drains you dramatically, but because it's an unnecessary distraction that you don't need the way an extrovert does to think. For generative, exploratory work — brainstorming, problem-framing, working through something that's stuck — you may actually benefit from the light stimulation of other people and ambient activity. The design challenge is building enough variability into your work context that you can move between these modes. If you're locked into one environment all day, you're making a compromise that neither serves your deep-work needs nor your collaborative ones. The investment in flexibility — a quiet space available when you need it, the ability to work somewhere with more energy when that's useful — pays more dividends for your profile than almost any other environmental change.",
  },

  high: {
    'Your Mental Energy Profile':
      "Your mental energy profile is organized around a fact that's the inverse of the introverted wiring: social interaction restores you rather than depleting you, and extended solitude is what actually costs energy. This sounds like a simple advantage in a world built largely on meetings and collaboration, but it's more nuanced than that. The restoration you get from social engagement is real and neurological — you genuinely think better, feel more alive, and generate more ideas when you're around people than when you're isolated. But the flip side is that environments designed for focused solo work — the quiet office, the long uninterrupted project, the work that requires you to be alone with your thoughts for extended periods — can feel like cognitive slow-motion. Not impossible, but working against your wiring rather than with it. Understanding this as a profile means understanding where you get your best output and designing accordingly, rather than assuming that the quiet-and-focused model is the correct one because it's what productivity culture tends to celebrate. Your best thinking happens in dialogue. Your ideas sharpen in conversation. The version of something you develop alone is often not the version you'd produce if you got to talk it through with someone else first.",

    'When Your Mind Works Best':
      "Your mind works best when there's another person or group in the circuit. This isn't about needing permission or validation — it's about how ideas develop for you. You probably notice that you understand what you think about something more clearly after you've said it out loud to someone else than you do when you've only thought it internally. The act of articulating something to another person — and having them respond, push back, or build on it — is actually part of your thinking process rather than the performance of a completed thought. This means the standard solo-work model, where you develop your ideas privately and then share the finished product, is probably not your best sequence. You'd do better to get into conversation early — even before you feel ready — because the conversation is where your thinking actually comes together. Collaborative environments, brainstorming sessions, working alongside other people even when the work isn't technically collaborative — these give your mind the stimulation it needs to perform at its best. The specific structure matters less than the human presence. Working in a coffee shop where you don't know anyone still gives you something that working in an empty apartment doesn't.",

    'What Drains You':
      "The drains in your profile are the inverse of what the introvert experiences, but they're equally real. Extended isolation — days of solo work, working remotely without social contact, tasks that require you to be alone with your thoughts for hours with no outlet — is your primary energy leak. You may not notice it as depletion in the moment, but you'll notice it as a creeping flatness, a difficulty generating the kind of energy and enthusiasm that usually come naturally, a sense that your thinking is somehow less sharp than usual. Repetitive, low-stimulation tasks that require sustained solo focus are particularly costly. The energy drain here isn't just about missing social contact — it's that without the stimulation and feedback of other people, your cognitive system doesn't have the inputs it needs to perform at full capacity. Another significant drain source is environments where you can't speak, respond, or engage — passive consumption contexts, one-way communication, situations where you're receiving information but not permitted to process it out loud. And the quiet, unacknowledged drain of performing the introvert ideal: making yourself work alone in silence for long stretches because that's what productive people are supposed to do, while your actual wiring is running against you the entire time.",

    'Your Cognitive Rhythm':
      "Your cognitive rhythm is more synchronous than asynchronous — meaning you tend to hit peaks when you're in active exchange with other people or ideas rather than in the quiet between interactions. This runs counter to how most knowledge work is structured, which assumes that deep work happens in solitude and collaboration happens in the cracks between it. For you, that sequence often needs to be inverted: the live thinking happens in interaction, and the solitary time that follows is for consolidation, refinement, and production — not for initial generation. Your rhythm also tends to be responsive to others' energy in a way that can be a genuine asset. You're not on a fixed schedule of alertness that ignores what's happening around you. You can be activated by an interesting conversation at 4 p.m. in a way that an introvert, who's been running their social battery down all day, simply can't. This makes you well-suited to work that is genuinely collaborative rather than performatively so, and to roles where responsiveness and real-time synthesis are valued over extended solo output.",

    'Designing Your Environment for Peak Thinking':
      "Designing your environment means being honest about what you actually need rather than what the productive-person aesthetic suggests you should need. The quiet, minimalist, isolated work setup is an introvert's ideal, and optimizing your environment to look like that is optimizing for the wrong person. What you need is proximity to people, access to conversation, and environments with enough ambient energy to keep your system activated. This doesn't mean you need noise or chaos — it means you need human presence, which is a different thing. Shared offices, cafes, co-working spaces, and even just working in a room where other people are doing other things can make a real difference in your cognitive performance relative to strict isolation. Building conversational touchpoints into your work structure is valuable: brief check-ins, working-through-it-aloud moments with a colleague, even a five-minute conversation before sitting down to solo work can prime your thinking in ways that an hour of quiet preparation doesn't. The meetings and collaborations that feel like interruptions to your real work may actually be generating the conditions under which your real work is possible. Recognizing that — and scheduling accordingly — lets you stop fighting your wiring and start using it.",
  },
};
