export const motivationSourceSeeds: Record<string, Record<string, string>> = {
  'fear of failure': {
    'Your Motivation Profile':
      "What gets you out of bed and into the work is, at its core, a desire to avoid a particular outcome. Not failure in the abstract — something more specific: the version of yourself that didn't try hard enough, that let something slip, that gave someone grounds to conclude you weren't as capable as they thought. That fear is a remarkable engine. It produces output, follow-through, and a kind of reliability that genuinely impresses people. The problem — and you have probably felt it without being able to name it — is that the fuel is avoidance. You're running away from something rather than toward it. The achievement is real. The sense of safety that the achievement was supposed to produce is much more elusive.",

    'The Engine Running Your Life':
      "Fear of failure as a primary motivator works through a specific psychological mechanism: the threat of a negative outcome activates your stress response, which activates effort. The work gets done. The deadline gets met. The performance is strong. But because the engine is threat-based, it never actually switches off. There's no arrival point where the fear resolves. Success postpones it rather than eliminating it. Which means that your high output exists on a permanent treadmill — each achievement buys you a temporary reprieve before the next threshold looms. You may have noticed that you don't celebrate your wins for very long, or that the feeling of relief after completing something important is brief and followed quickly by the weight of whatever comes next. That's the engine doing exactly what it was built to do.",

    'Where This Fuel Works':
      "This motivation source is exceptionally effective in environments with clear stakes, defined metrics, and external accountability. You perform well on deadlines. You perform well when something matters. You show up reliably when others are depending on you, partly because letting someone down carries enough weight to override fatigue or doubt. You are also — and this is worth naming — genuinely good at things. The output your fear produces has compounded into real skill and real competence. That competence is yours, even if the original motivation wasn't the cleanest. In competitive contexts, in projects that require sustained discipline, in anything where the margin for error matters, fear of failure is a legitimate edge.",

    'Where This Fuel Burns Out':
      "The breakdown happens in two predictable ways. The first is burnout — the system runs hot for long enough that it simply exhausts the person running it. Fear-based motivation doesn't have a natural off switch, so the pacing tends to be unsustainable; rest gets experienced as threat rather than recovery. The second is paralysis, which sounds counterintuitive but is actually a common companion to high-performers driven by this engine. When the stakes feel high enough that failure seems genuinely catastrophic, the avoidance mechanism can turn inward — against the work itself. Procrastination, over-preparation, endless revision that prevents completion — these are fear-of-failure in its paralytic mode. You can also find yourself avoiding genuinely valuable things — risks worth taking, creative leaps, relationships that require vulnerability — because the possible failure is more vivid than the possible gain.",

    'Building a More Sustainable Drive':
      "The shift you're working toward isn't about removing the fear — that's not realistic, and the edge it gives you has real value. It's about adding a different engine that can run alongside it. Approach motivation — moving toward something that genuinely matters to you — doesn't exhaust the system the same way avoidance does. The question to sit with is: what would you still do if failure carried no weight? Not as a replacement for everything you currently do, but as a probe for what has intrinsic pull. Where that pull exists, it's worth building infrastructure around it — letting it generate some of the momentum rather than leaving everything to the threat-response. Over time, you're aiming for a portfolio of motivations, where fear of failure is one input rather than the primary fuel source.",
  },

  'status and approval': {
    'Your Motivation Profile':
      "You are calibrated to the room. This isn't a character flaw — it's a sophisticated social antenna that took years to develop, and it confers real advantages in almost every environment that involves other people. What drives you forward is a combination of wanting to be seen favorably and wanting to occupy a position that others recognize as meaningful. Status and approval as motivators are powerful precisely because they're social — other people's responses to you are a constant source of real-time data, which keeps you tuned in and responsive in ways that purely internal motivators don't. The complication is that when the goals belong to other people, the goalposts move when other people move them.",

    'The Engine Running Your Life':
      "The engine here is external referencing — you are, to a significant degree, locating your sense of progress and value in how other people respond to you. That's not the same as caring what people think in a shallow way. It's more structural: your internal sense of 'am I doing well?' is substantially answered by reading the room. Positive responses produce forward momentum. Critical or neutral responses produce recalibration. You're good at reading what a context values and moving toward it, which means you're socially effective, often impressive, and reliably oriented toward things that have audience. What this engine tends not to generate is movement toward things that are unpopular, that no one is asking for yet, or that will take a long time to be recognized — because those paths don't feed the signal.",

    'Where This Fuel Works':
      "Status and approval as motivators work exceptionally well in structured social environments — any professional context with clear hierarchies, visible metrics of success, and regular social feedback. Sales, management, performance, public-facing work, anything with audience — you tend to thrive. You are also genuinely good at navigating political environments, at understanding what a given context or person needs and orienting accordingly. That skill produces results. You're not merely performative; you deliver. The approval-seeking often aligns neatly with real competence, because you're motivated to actually get good at the things that get you recognized. And you carry an emotional intelligence that people oriented toward purely internal metrics sometimes lack.",

    'Where This Fuel Burns Out':
      "The place this fuel fails you is anywhere the external feedback is absent, delayed, or negative in a way that's hard to decode. Long solo projects where no one is watching. Creative work that requires you to be wrong for a long time before you're right. Pursuing a direction that the people around you don't yet understand or value. In those contexts, the engine doesn't have anything to run on, and the work stalls. There's also the goalpost problem: because other people set the standards by which you measure yourself, achieving those standards doesn't produce lasting satisfaction. You reach the level, the level moves, and you're calibrating again. This can produce a life of externally impressive achievement that feels hollow from the inside — not because the achievements weren't real, but because they were never answering the right question.",

    'Building a More Sustainable Drive':
      "The question that tends to be most clarifying for people with this motivation profile is: what would you pursue if no one would ever know? Not as a hypothetical, but as a genuine inventory of what has pull independent of audience. That pull — when you can find it — is the thing worth building toward. This doesn't require rejecting the social motivation; you can keep being responsive to feedback and still develop an internal north star that isn't entirely defined by what gets approved. Practically, this looks like: deliberately taking on things that won't be recognized for a while, and noticing what happens internally during that period. What sustains you? What collapses? You're mapping your intrinsic interest separate from the social signal. That map becomes increasingly useful as you move into phases of life or work where the external validation is less reliable.",
  },

  'intrinsic curiosity': {
    'Your Motivation Profile':
      "Something in you just wants to know. It moves toward things that are interesting without needing to justify that interest in terms of outcome or utility. You follow threads because they're compelling. You get absorbed in problems because the problem itself is engaging, not because of what solving it will get you. This is a genuinely rare form of motivation — most people need the carrot or the stick, and you're running on something that doesn't require either. The research on intrinsic motivation is fairly unambiguous: it produces deeper learning, higher creativity, and more sustained engagement than any external motivator. It also comes with a particular failure mode that is worth understanding, because it can make you look — to yourself and others — like something you're not.",

    'The Engine Running Your Life':
      "The engine is interest. Specifically, the feeling of being drawn toward something — a question, a domain, a problem, a project — and wanting to understand it more completely than you currently do. That draw is nearly frictionless when it's genuine. You don't need to motivate yourself to do things that are interesting; you need to stop yourself. The difficulty appears on the other side: when the interest is absent, or has moved on, the engine has nothing to run on. Tasks that bore you don't just feel unpleasant — they feel actively resistive, like pushing against your own wiring. You can override this with willpower for a while, but it costs more than it costs people with other motivation profiles, and the quality tends to show.",

    'Where This Fuel Works':
      "Intrinsic curiosity as a motivator is most powerful in creative and intellectual work where the problem itself is the point — research, design, building things that don't exist yet, figuring out how something works. You do your best work when you're genuinely interested, and when you're genuinely interested, you're very hard to stop. The depth of engagement you bring to things that fascinate you tends to produce an unusual quality of output — not just technically solid, but original. You're also self-starting in a way that requires expensive infrastructure to replicate in people who aren't. You don't need to be managed closely when you care about the work. That makes you a particularly high-value collaborator in the right environments, and a difficult employee in the wrong ones.",

    'Where This Fuel Burns Out':
      "The breakdown comes in two forms. The first is the loss of interest — when a project that once engaged you becomes routine, or when you've understood it enough that the edge of the unknown has moved and you're now in execution mode. The curiosity engine doesn't power execution particularly well. You can find yourself essentially done with something before the work is done, which can look like inconsistency or lack of follow-through from the outside. The second is the scope problem: curiosity takes you in many directions, and not all of them are the directions that serve the goals you've committed to. You can spend meaningful time on fascinating tangents that produce nothing actionable. This can feel like selfishness or unreliability to collaborators who are counting on you to stay in the lane, even after the lane has stopped being interesting.",

    'Building a More Sustainable Drive':
      "The sustainable version of this motivation profile involves building infrastructure around the curiosity rather than trying to replace it. That means: getting better at identifying the moment when genuine interest leaves a project, and making a deliberate choice at that point rather than letting it drift. It also means developing a practice around the parts of work that require discipline without interest — batching them, minimizing them, or finding someone else to do them. The deeper work is developing enough relationship with commitment that you can stay in something through the boring middle without feeling like you're betraying your nature. Curiosity doesn't have to be the only fuel in the tank; it works best as a lead engine supplemented by something — purpose, responsibility, craft — that can sustain you when curiosity temporarily goes elsewhere.",
  },

  'meaning and purpose': {
    'Your Motivation Profile':
      "You are driven by why. Not what you're building or how well you're building it, but the underlying reason it matters — the person it helps, the value it creates, the world it moves toward. Meaning-based motivation is, in the long run, the most sustainable of the four primary types. It doesn't exhaust itself the way fear does, doesn't shift with the room the way approval-seeking does, doesn't abandon you when the interesting parts are over the way curiosity can. When you're connected to the why, you can sustain effort through genuinely difficult stretches that would stop other engines cold. The vulnerability in this profile is less about duration and more about alignment — meaning-based motivation is highly fuel-efficient when connected to genuine values, and almost inert when it isn't.",

    'The Engine Running Your Life':
      "The engine is connection to significance. You need the work to matter — not abstractly, but specifically, in ways you can trace. You are energized by contribution: by knowing that what you're doing is in service of something beyond the immediate task. That connection to significance can come from many sources — a cause, a community, a person you're responsible to, a long-term vision — but when it's present, it generates a quality of engagement that is hard to manufacture any other way. What it requires is authenticity. Unlike fear or approval, you can't fake connection to meaning. If you're doing something that doesn't connect to what you actually value, the engine doesn't run on obligation — it stalls. And obligation trying to masquerade as meaning is one of the more exhausting psychological experiences available to a human being.",

    'Where This Fuel Works':
      "Meaning-based motivation works best in long-arc endeavors — the kind of work that doesn't pay off in weeks or months, that requires sustained effort toward a goal that's months or years away, and that involves enough hardship along the way that shorter-term motivation types would have quit. You can work through difficult stretches that stop people whose engines are fear or approval because you know why you're in the stretch. You're also genuinely committed in a way that creates trust — with collaborators, with clients, with anyone who needs to know that you'll be there for the duration. People can feel the difference between someone going through the motions and someone who actually cares. You're in the second category. That difference is worth something in virtually every professional and personal context.",

    'Where This Fuel Burns Out':
      "The fragility in this profile is disconnection. When the meaning-thread breaks — when the work stops connecting to your values, when the organization you believed in betrays that belief, when the goal you were oriented toward turns out not to matter in the way you thought — the engine can drop out almost entirely. That experience can be genuinely disorienting, because you've been running on something that felt fundamental rather than chosen. There's also a martyrdom risk that is specific to this profile: a tendency to work hard on things that 'should' matter even when they no longer actually connect to your genuine values. Meaning-based motivation can be hijacked by obligation, by identity investment in a cause or role, by the story of yourself as someone who does important things — and you end up burning fuel on something that isn't feeding you back.",

    'Building a More Sustainable Drive':
      "The most important maintenance for this motivation profile is regular reconnection with the actual why — not the stated mission or the narrative about the work, but the felt sense of what you're doing it for. That reconnection tends to slip without being noticed; you can be three months into work that has gradually become disconnected from your values without having consciously registered the drift. A regular check-in — is this still what I actually care about? — is less a philosophical exercise than a practical calibration. The other piece is distinguishing meaning from obligation more rigorously than is comfortable. Some of the things you feel you should care about are things you were taught to care about. Finding the genuine core of what you actually value — as distinct from what's admirable to value — is the ongoing project, and it keeps the engine running clean.",
  },
};
