export const narrativeIdentitySeeds: Record<string, Record<string, string>> = {
  secure: {
    'Your Life Narrative':
      "The story you tell about your life has a particular shape to it — one where you are, fundamentally, someone who can handle what comes. Not invincible, not immune to hardship, but capable. You carry a sense that the chapters of your life connect in some meaningful way, that difficult stretches had something to teach, and that the people who showed up mattered. You don't need your story to be perfect to feel okay about it. That's rarer than it sounds. Most people need their narrative to justify them, to explain them, to make a case for their worth. Yours tends to simply hold you — with room for contradiction, for regret, for things that didn't work out the way you hoped. That flexibility in how you hold your own history gives you something most people spend years trying to build: a story that doesn't trap you in it.",

    'How This Story Was Written':
      "Stories like yours don't appear by accident. They get built through a combination of early experiences that, however imperfect, gave you enough of a foundation — enough reliable connection, enough repair after rupture, enough moments of being genuinely seen — that you developed something psychologists call a coherent autobiographical narrative. You learned that it's okay to need people and still be okay when they're not there. You absorbed the idea that asking for help doesn't make you weak and that being alone doesn't make you abandoned. Someone, at some point, showed you that relationships could contain both closeness and disappointment without collapsing. That lesson became load-bearing. It shaped how you store and retrieve your own memories, how you talk about your past, and how much of your identity depends on things going right.",

    'The Story\'s Strengths':
      "What your narrative gives you is adaptability. Because your sense of self doesn't depend entirely on outcomes or on other people's constant approval, you can absorb bad news without revising the whole story. A job loss, a relationship ending, a failure that genuinely stings — these become chapters, not verdicts. That's not denial or forced positivity. It's actual structural resilience in how you process experience. You're also able to hold complexity in how you talk about others. You can love someone and be frustrated by them. You can acknowledge that a parent was both a source of pain and a source of strength. That kind of nuance keeps your relationships honest and your own sense of reality grounded. It also means that when new information comes in — about yourself, about someone you love — you don't have to defend against it to stay intact.",

    'Where the Story Becomes a Cage':
      "Even secure narratives have traps. One of the quieter ones is a kind of complacency — a sense that because you're fundamentally okay, you don't have to push into the uncomfortable territory that growth actually requires. Secure attachment can sometimes produce a subtle preference for harmony over honesty, especially in relationships where conflict might genuinely need to happen. You may also underestimate how much your narrative stability depends on conditions that still exist in your life. Remove the relationships, the routines, the context that supports your sense of coherence, and you'll discover that the story is more load-bearing than it appears. Another edge worth watching: secure people sometimes struggle to understand why others don't just 'get over it.' Your own processing speed can become a blind spot when you're trying to be present with someone whose wound runs deeper.",

    'Rewriting the Narrative':
      "The good news is that you don't need a major rewrite — your narrative architecture is sound. What matters now is staying curious about the edges of it. Where does the story feel rehearsed rather than felt? Where do you reach for the same explanation because it works well enough rather than because it's actually true? Your version of growth isn't about excavating trauma or rebuilding from scratch. It's about paying attention to the places where your story might be slightly too tidy, where complexity got smoothed over in the interest of coherence. It's also about deliberately extending the security you carry into contexts where it gets tested — not just where it's easy. Relationships that challenge you, work that involves real risk of failure, situations where the outcome isn't in your hands. That's where your story deepens.",
  },

  anxious: {
    'Your Life Narrative':
      "The story you tell about yourself has love at its center — but not in the simple way. What runs through your narrative is a long search for confirmation: that you are enough, that you matter, that the people you care about will stay. The protagonist of your story is someone who feels things deeply and who has learned, sometimes painfully, that feeling deeply can be a liability in a world where other people don't always match your intensity. Your story often divides along a fault line — before and after certain relationships, certain moments of rejection or connection that felt like they confirmed something essential about your worth. The good chapters tend to be defined by closeness. The hard ones are defined by its absence or its threat. That's not a defect in the story. It's the shape that experience gave it — but it's worth seeing clearly.",

    'How This Story Was Written':
      "Anxious attachment narratives are written by inconsistency. Not cruelty, necessarily — inconsistency. The caregivers or relationships that mattered most to you were present sometimes and absent or unpredictable other times, which meant you never quite got to relax into safety. Your nervous system learned to stay alert. Your mind learned to monitor for signs of withdrawal, disapproval, or distance, because catching those signals early was the only way to manage them. That vigilance became the lens through which your story got told. Relationships became high-stakes. Love became something you had to earn and maintain rather than something you simply had. Over time, your narrative built in a hypothesis: that your value is contingent, that it fluctuates with how others respond to you, and that the baseline answer to 'am I enough' is a question mark rather than a yes.",

    'The Story\'s Strengths':
      "What this story gives you is emotional depth and relational attunement that most people simply don't have. You notice things. You read rooms, track moods, catch shifts in other people that they haven't yet made conscious. You care about relationships with a sincerity that is not performative — it's structural. You actually want the connection you pursue. That's meaningful. Your capacity for loyalty, for showing up in other people's hard moments, for understanding what it feels like to be on the edge of losing something — these are not small things. Your story has also given you an intimate familiarity with your own emotional interior. You may not always know what to do with what you feel, but you are rarely out of contact with it. That kind of awareness, properly channeled, is the foundation of real self-knowledge.",

    'Where the Story Becomes a Cage':
      "The story becomes a problem when it starts writing itself in advance. When you enter a relationship — romantic, professional, sometimes even a friendship — with the hypothesis already running: that you will eventually be found wanting, that the distance will come, that your need will be too much. That hypothesis shapes how you behave, which can then confirm it. You reach, the other person feels crowded, they pull back, and the narrative says: see. What the narrative doesn't say is that the reaching was itself a response to the fear, not a response to anything that actually happened. The other trap is that love becomes an answer to a question it can't actually resolve. No amount of being loved will permanently settle the question of whether you are lovable, because that answer has to come from somewhere internal, and no relationship can install it for you.",

    'Rewriting the Narrative':
      "Rewriting this story isn't about needing less or caring less. It's about separating your worth from the moment-to-moment feedback of other people's responses. That's painstaking work, and it happens in small increments — not revelations. It starts with noticing when the narrative is running and being curious about it rather than immediately reactive to it. When you feel the pull of anxiety in a relationship, the question to ask isn't 'what does this mean about me' but 'what is happening in me right now, and what is it actually responding to?' Over time, you're building a new hypothesis: that your value exists even in the silence, even when no one is confirming it, even when a relationship ends or a person pulls away. The story doesn't have to be about seeking confirmation. It can be about what you already carry.",
  },

  avoidant: {
    'Your Life Narrative':
      "The story you tell about yourself is, on the surface, one of capability. You have figured things out. You've handled hard situations without falling apart. You don't rely on people in ways that make you vulnerable, and you have, somewhere along the way, come to experience that as a feature rather than a bug. The protagonist of your narrative is someone who learned early that dependence is costly — that leaning on others tends to disappoint, that needing people opens you to something that feels worse than just managing alone. Your story is not without connection, but connection in your narrative tends to be instrumental or chosen carefully, on your terms, with exits kept visible. What you might not have fully examined is the part of the story that came before the self-sufficiency — the part where that preference got built.",

    'How This Story Was Written':
      "Avoidant narratives are written by a specific kind of early experience: not usually dramatic rejection, but consistent emotional unavailability. The caregivers who shaped you were present enough that you survived fine, but not emotionally present enough that you could rely on them with your more vulnerable states. Distress, need, fear, sadness — these things may have been met with dismissal, discomfort, or an expectation that you manage yourself. So you did. You learned to manage yourself. You also learned to not need things that wouldn't be given anyway — and over time, that adaptation became invisible. It stopped feeling like a coping mechanism and started feeling like your actual personality. The independence isn't fake; it's real. But it was originally functional, not chosen. Your story is built partly on a foundation that was poured before you had any say.",

    'The Story\'s Strengths':
      "Your narrative gives you genuine resilience. You are not easily destabilized by external chaos, by the unpredictability of other people, or by circumstances that would undo someone with fewer internal resources. You can function when things fall apart. You can make hard decisions without needing prolonged support or reassurance. In a professional context, in emergencies, in any situation that requires someone to hold steady — these are real assets that come from your story, not despite it. You also tend to bring a kind of clarity to situations that others cloud with emotion. Your ability to step back, to see what's happening with some distance, to not be swept away — that produces useful perspective. People often trust you with difficult things precisely because you don't panic. That trust is earned. It's yours.",

    'Where the Story Becomes a Cage':
      "The story becomes a trap when what started as adaptation gets mistaken for preference. You may genuinely believe you don't need closeness much, that relationships are fine but not essential, that you're simply a more independent type. Sometimes that's true. Often, it's a story built on a decision that was made before you could make it consciously. The cost is quieter than the anxious version — no visible drama, no obvious pain — but it's real. It shows up as a persistent flatness in relationships that stay at the surface, as a nagging sense that something is missing without being able to name what, as a pattern of exit when closeness starts to feel like more than you signed up for. The people who want to get close to you hit a wall they can't always see clearly, and the relationship eventually rearranges itself around your comfort zone — which is comfortable but not alive.",

    'Rewriting the Narrative':
      "Rewriting this story doesn't require becoming a different person or suddenly needing people in ways that feel foreign. It starts with a more honest accounting: which parts of your independence are genuinely chosen, and which were originally necessary? Not as a verdict, but as information. From there, the question becomes whether you want to test some of the story's premises — whether leaning on someone actually costs what you've calculated, whether vulnerability actually produces the outcome you've been avoiding. That testing is low-stakes at first. It's telling someone something true about yourself that you would normally keep private. It's staying in a conversation instead of ending it. It's letting someone help you with something when you could handle it alone. The story can expand to include closeness as something that's genuinely available to you — not as a need that exposes you, but as a thing worth having.",
  },

  disorganized: {
    'Your Life Narrative':
      "Your story doesn't follow a clean arc, and you probably know that. The narrative you carry about yourself contains contradictions that resist resolution — you want closeness and you fear it. You reach toward people and you pull away. You have moments of feeling intensely connected followed by a collapse into distance or numbness. The protagonist of your story is caught between two things that can't both be true at once and yet somehow are: that other people are the answer, and that other people are the threat. This isn't confusion or weakness. It's the natural outcome of a very particular kind of early experience, where the person you needed for safety was also the source of fear or harm. When safety and danger share the same face, your nervous system learns to be permanently unresolved — and that unresolved state becomes the ground your story is built on.",

    'How This Story Was Written':
      "Disorganized attachment — the clinical name for what your story reflects — emerges when a child's caregiving environment contains real contradictions: the person who hurt you was also the person you needed, or the person you needed was so unpredictable that you never developed a reliable strategy for getting comfort. In those circumstances, you can't settle on a coherent approach to relationships. Anxious strategies don't work, avoidant strategies don't work, so you oscillate — sometimes desperately seeking closeness, sometimes shutting down completely. That oscillation gets coded into your nervous system as the default mode of intimacy. Your body learned that love is unsafe. Your mind learned that wanting something from people produces unpredictable results. Your story was written under those conditions, and it makes sense that it has the shape it does.",

    'The Story\'s Strengths':
      "Your narrative has given you something unusual: a firsthand, embodied knowledge of what it costs to live in contradiction. You understand ambivalence from the inside. You know what it feels like to simultaneously want and fear the same thing. That knowledge — when it becomes conscious — makes you deeply perceptive about other people's hidden conflicts, about the gaps between what people say and what they feel, about the parts of the human experience that most people prefer to keep at arm's length. You have a tolerance for complexity, for things that don't resolve cleanly, that is genuinely rare. You've also survived something. The fact that you're still here, still capable of wanting connection despite a history that taught you it was dangerous — that's not small. It reflects something durable in you that the story hasn't extinguished.",

    'Where the Story Becomes a Cage':
      "The cage in your story is built from the expectation of rupture. You enter relationships carrying a set of predictions — that closeness will become unsafe, that the person will either hurt you or leave, that your need will produce something bad. Those predictions are based on real past data. They were accurate once. The problem is that your nervous system doesn't always distinguish between historical patterns and current reality. So a partner who is actually safe gets processed through the old threat-detection system. A moment of ordinary conflict trips a wire that was installed in a different context. You may find yourself doing things in relationships that confirm the predictions — creating distance before it's imposed on you, escalating conflict to test what the other person will do, dissociating when intimacy gets close. The story keeps playing, not because it's still true, but because it's the only story the system knows.",

    'Rewriting the Narrative':
      "Rewriting this story requires something different from what most self-improvement framing suggests. It's not primarily a cognitive task — you can't think your way out of a narrative that lives in your body. The work is slower and more physical: it's about accumulating evidence, experience by experience, that safety is possible. Relationships that are genuinely consistent over time. Moments of rupture that actually get repaired. Closeness that doesn't end in harm. Each of those experiences is data that begins, slowly, to update the prediction. Therapy that works with the nervous system directly — somatic approaches, EMDR, attachment-focused work — tends to be more effective than insight alone, not because insight isn't valuable but because your story was written before language. The rewrite happens at that same level. Slowly, with evidence, your nervous system learns that safety and the people who love you are not mutually exclusive.",
  },
};
