export const overthinkingSeeds: Record<string, Record<string, string>> = {
  suppression: {
    'Your Overthinking Profile':
      "Your version of overthinking is protective. The loop you get caught in — the turning over of a problem, the replaying of a conversation, the endless calculation of what might happen — isn't random noise. It's doing a job. Specifically, it's keeping you one step removed from something you don't want to feel directly. Your mind is genuinely good at this. It can sustain a cognitive loop almost indefinitely, and as long as it's spinning, you're in the realm of thinking rather than feeling, which is where you're more comfortable. That's not weakness — it's an adaptation that made sense somewhere along the way. Understanding it clearly is the first step toward having more choice about it.",

    'The Loop You Get Stuck In':
      "The loop tends to be analytical in character. You think about the situation. You consider angles. You run scenarios. You draft responses or decisions in your head, evaluate them, discard them, start over. From the outside — and often from the inside — it looks like productive deliberation, because you're using the vocabulary of problem-solving. But genuine problem-solving moves toward resolution. Your loop tends to circle. The thinking isn't building toward an answer; it's serving a different function — keeping you occupied, keeping you above the waterline, keeping you in your head and away from your body. The tell is that the loop doesn't resolve when you get more information. More information just gives it more material.",

    'What You\'re Actually Avoiding':
      "What's underneath the loop is almost always an emotion that feels too large, too uncertain, or too threatening to sit with directly. Not necessarily dramatic — it could be a mild but persistent anxiety, a grief that hasn't had room to be felt, a fear that you've been managing by refusing to acknowledge it fully. Suppression-style overthinking emerges when the emotional processing system and the cognitive system are working at cross purposes: the emotion is trying to be processed, the mind is trying to prevent that from happening, and the loop is the compromise. You stay close enough to the feeling to keep it contained, but not close enough to actually move through it. It can last years. Decades, in some cases.",

    'The Cost of the Loop':
      "The costs are real and cumulative. Cognitively, sustained suppression and looping consume significant working memory and attention — resources you could be using for actual thinking. You may notice a persistent low-level mental fatigue that doesn't resolve with rest, because rest doesn't address what's actually running in the background. Emotionally, suppressed material doesn't disappear; it tends to either compress into somatic symptoms — tension, disrupted sleep, vague anxiety — or leak out sideways in situations where you're depleted enough that the suppression fails. Relationally, the loop pulls your presence inward in ways other people feel without necessarily being able to name. You're there, but you're not fully there. That distance has a cost in intimacy.",

    'Breaking the Pattern':
      "The counterintuitive move with suppression-style overthinking is to go toward the feeling rather than trying to stop the thinking. Trying to stop the loop directly — through distraction, through force of will, through 'just deciding' — tends not to work, because it doesn't address the function the loop is serving. What works is creating conditions where the underlying emotion has somewhere to go: journaling in a way that asks 'what am I feeling right now' rather than 'what do I think about this situation,' body-based practices that bypass the cognitive layer, conversations where you're specifically trying to feel rather than analyze. The loop doesn't need to be conquered; it needs to become unnecessary. When the emotion gets processed, the loop loses its job.",
  },

  acceptance: {
    'Your Overthinking Profile':
      "You're something of a paradox in this space. You have more self-awareness about your internal states than most people — you can name your feelings with reasonable accuracy, you understand that you're overthinking, you often know in real time that the loop you're in isn't producing anything useful. And yet the loop persists. That combination — good awareness, continued spinning — can be genuinely frustrating, and it sometimes produces a secondary loop: thinking about why you're thinking about what you're thinking about. Your overthinking isn't driven by emotional avoidance or by a need to resolve unacknowledged feelings. It's more structural than that, which actually makes it a different problem from the other types.",

    'The Loop You Get Stuck In':
      "Your loop tends to be high-resolution rather than circular. You're not replaying the same five seconds of a conversation — you're analyzing it from multiple angles, considering what each angle implies, cross-referencing those implications against what you know about yourself and the situation, and then evaluating the quality of your own analysis. There's a thoroughness to it that can feel productive, but it rarely is. The specifics change; the pattern doesn't. You're applying a level of cognitive precision to situations that cannot be resolved through additional precision. Some things can't be thought through to completion — ambiguous relationships, uncertain outcomes, questions about your own motivations — and your mind's response to that ambiguity is to try harder, which produces more loop rather than more clarity.",

    'What You\'re Actually Avoiding':
      "Your loop isn't primarily about avoiding an emotion. It's about avoiding something slightly different: the discomfort of not knowing. Ambiguity is genuinely uncomfortable for you — not because you're incapable of sitting with uncertainty, but because your cognitive style has a strong drive toward completion, toward resolution, toward having a clear model of what's happening. When a situation resists that clarity, the mind keeps working at it the way a tongue keeps finding a gap in a tooth. The other thing your loop can be avoiding is the action that would come after the thinking is done. If you think long enough, you don't have to decide. If you haven't quite figured it out yet, the moment of commitment is always one more consideration away.",

    'The Cost of the Loop':
      "The cost here is often felt as decision fatigue and a kind of paralysis-by-analysis that can look, from the outside, like thoroughness. You take longer than necessary to make decisions that could be made faster without meaningful loss of quality. You sometimes over-process simple interpersonal situations in ways that make them feel more complicated than they are — and then relate to people through the model you've built of them rather than through direct contact. Your self-awareness, which is genuinely a resource, can tip into a kind of hypervigilant self-monitoring that makes it harder to be present and unrehearsed. The loop also creates a gap between your internal processing and the external moment: life keeps moving while you're still analyzing the previous thing.",

    'Breaking the Pattern':
      "For you, the intervention isn't going toward a feeling — you already have decent access to your feelings. It's about developing a higher tolerance for ambiguity and a practice around deliberately incomplete analysis. That means: identifying the point at which you have 'good enough' information to act or to rest, and making a practice of stopping there rather than seeking the next increment of clarity. It also means developing what researchers call 'closure on demand' — the ability to put a question down intentionally rather than waiting until it resolves. Some questions don't resolve; your relationship with those questions is a separate practice from your relationship with solvable ones. Finally, the action piece: movement tends to break your version of the loop better than more thinking. Get to the next actual step before the analysis is complete. Let the doing generate data instead of asking the thinking to produce it.",
  },

  rumination: {
    'Your Overthinking Profile':
      "Your version of overthinking is oriented toward the past. The loop you get caught in has a particular quality: it revisits. It goes back to things that happened — conversations, decisions, failures, moments of pain or regret — and runs them again, looking for something. Not quite understanding, though that's the surface story. More like resolution. Like if you review it carefully enough, the thing might come out differently, or you might finally be able to set it down. Rumination is overthinking as emotional processing that got stuck in a groove. The mind is genuinely working — it's not suppression, it's not perfectionism, it's actual processing — but the processing has looped back on itself and can no longer move forward.",

    'The Loop You Get Stuck In':
      "The loop tends to have an emotional quality that distinguishes it from other types — there's often frustration, grief, guilt, or anger woven into the spinning, not just cognitive activity. You replay a conversation and feel again what you felt during it. You revisit a decision and feel again the weight of having made it. You re-examine a relationship and cycle through the same feelings that didn't resolve the first time. The loop has texture; it's not dry analysis. That emotional charge is both what makes it feel like it's 'working' — it has weight, it feels meaningful — and what keeps you stuck. Real emotional processing tends to move. Rumination moves in circles, returning to the same material with the same charge, because it hasn't found the exit.",

    'What You\'re Actually Avoiding':
      "Rumination is often less about avoiding than it is about failing to complete. What you're circling around is usually something that needs one of three things to actually move through: a genuine expression of the emotion (grief to be grieved, anger to be released), an acceptance of something that cannot be changed, or occasionally an action that would require you to engage with the situation differently rather than just revisit it internally. The loop substitutes for all three. It feels like you're processing, so you don't look for the actual path through. What the loop is often specifically avoiding is the moment of acceptance — the felt acknowledgment that the thing happened, it can't be undone, and it still hurts. That moment is the exit, but it requires sitting with the loss in a way that feels worse before it feels better.",

    'The Cost of the Loop':
      "Rumination is one of the most well-studied contributors to depression and anxiety in the psychological literature. The costs are significant: sustained backward focus pulls attention away from the present moment and from the future, which means both immediate engagement and forward-planning suffer. It also tends to worsen the emotional charge of whatever you're processing rather than reducing it — each pass through the material can intensify the feelings rather than discharge them, because you're not completing the emotional cycle, just re-activating it. Rumination also tends to distort over time: memories get interpreted through the lens of the current emotional state, which means the version of events you're looping over becomes increasingly removed from what actually happened.",

    'Breaking the Pattern':
      "Breaking rumination requires identifying the specific point where the loop typically gets stuck, because that point reveals what the processing needs in order to complete. If the loop keeps returning to something you did, there may be a genuine apology or amends that would close it. If it keeps returning to something that was done to you, the processing may need a genuine expression of the anger or grief — not just the cognitive acknowledgment of it, but the felt expression. If it keeps returning to a situation that simply ended, the exit is probably some form of acceptance practice, where you deliberately sit with the loss rather than trying to resolve it through analysis. Behavioral activation — doing things that engage you in the present, especially physical activity — is one of the most effective evidence-based interventions for breaking the ruminative cycle, precisely because it forces the nervous system into the present rather than the past.",
  },
};
