export const personalLeverageSeeds: Record<string, Record<string, string>> = {
  Creativity: {
    'Your Leverage Profile':
      "Your highest-order strength isn't execution — it's the thing that happens before execution, the part most people skip or do badly. You generate options. You see configurations of a problem that others haven't considered because they moved to solving it before they'd finished understanding its shape. This is genuinely rare, and genuinely undervalued, because the people around you often don't realize that the decision they're optimizing was never the right decision to begin with. Your leverage is upstream. It's in the problem-framing, the reframing, the moment when you say 'wait, what if the actual question is this?' — and the room shifts because you were right. The risk for creative types is that this upstream power gets deployed randomly, at every decision, when it's most needed specifically at the consequential ones. Knowing where your creativity creates the most return is part of learning to use it strategically rather than prolifically.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is getting yourself into problem-framing conversations before decisions get locked in. The further upstream you intervene, the more your creativity compounds. A new option that you generate at the beginning of a process propagates through every downstream decision. An option you generate after the team has already committed to a direction has to fight against sunk cost and momentum. This means your strategic position in any project or organization is ideally at the front of cycles, not the back. You are not most valuable as a reviewer of finished work. You are most valuable before the scope is set, before the brief is written, before the team has decided what they're solving. Getting yourself into those rooms — or creating them when they don't exist — is the ROI move. Concretely, this might mean asking to be involved in planning conversations earlier, volunteering to facilitate problem-definition sessions, or simply making a habit of asking 'are we solving the right problem?' before joining any solution-focused discussion.",

    'What to Stop Doing':
      "Stop applying your creativity uniformly to everything. This is probably the most common leverage leak for people with your strength. When everything gets the creative treatment — every email, every meeting, every routine task — the signal gets lost in the noise and the people around you stop being able to tell when you're offering a genuine reframe versus generating variation for its own sake. Creativity applied everywhere is creativity that doesn't have a strategic point. There's also a specific trap worth naming: generating options without advocating for any of them. The creative person who presents five directions and then says 'I just wanted to put these out there' is doing the first half of the job and skipping the part where their creativity actually moves anything. Your options need a point of view attached. The generation is the setup; the recommendation is the leverage.",

    'The Strength You\'re Underusing':
      "You're probably underusing your creativity in the domain of process design — not just what to do differently, but how to make the doing of things different. Most organizations have inherited processes that nobody designed; they accumulated. The creative person who turns their attention to the how rather than just the what tends to find enormous leverage, because process is the thing that shapes every output downstream. You may also be underusing your ability to make complexity accessible. The upstream, reframing quality of your creativity often means you can hold multiple configurations of a problem simultaneously — which is exactly the skill needed to explain a complicated thing to someone who's seeing it fresh. That explanatory creativity is often invisible until you name it and use it deliberately.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, run one experiment in upstream creative leverage: identify a decision or direction that your team, organization, or project is about to commit to, and ask to facilitate a one-hour problem-definition session before the solution phase begins. Your only job in that session is to generate at least three versions of the problem statement and let the group choose which one they're actually trying to solve. Track whether the downstream work changes as a result. In parallel, pick one domain where you've been applying creativity broadly and get more selective. Decide what it's actually for in that context — what specific kind of creative contribution has the most consequence — and route your energy there rather than distributing it. By day 90, you should have at least one clear example of upstream creativity changing an outcome, and a sharper vocabulary for where your creative leverage is highest.",
  },

  Curiosity: {
    'Your Leverage Profile':
      "Your leverage is learning velocity — the rate at which you acquire genuine understanding relative to other people. In a world where most people learn just enough to function in a domain and then stop, you keep going. You go through the surface and into the structure. You want to know not just what something does but why it does it, what would happen if it were different, what the people who built it were thinking when they made the choices they made. This learning depth is your competitive edge in a specific way: it means that when something changes, when a domain shifts, when a new problem emerges, you have the underlying architecture of a subject available rather than just the surface features. Surface learners get disoriented when the surface changes. You can adapt because you understood what was underneath. The other dimension of your leverage is novelty tolerance — you can stay genuinely interested in unfamiliar things longer than most people can, which means you're less likely to abandon a difficult domain before it yields its real insights.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is going deeper in fewer domains rather than wider in more of them. This sounds like a constraint but is actually the opposite. Your curiosity can produce a mile-wide, inch-deep knowledge base if you follow every interesting thread equally. That's pleasurable but not leveraged. The version that compounds is: picking the two or three domains where depth has the most consequence for what you're trying to build or do, and going further into those than any generalist would. Being the person who knows a field genuinely, not just well enough to talk about it at dinner — that's where your curiosity becomes a structural advantage. The specifics of which domains matter less than the principle: be deeper in fewer things, and let your curiosity drive you to the level of understanding where the non-obvious insights live.",

    'What to Stop Doing':
      "Stop treating curiosity as a consumption habit and start treating it as a production tool. There's a version of curiosity that is essentially sophisticated entertainment — fascinating content, interesting ideas, one thing after another — without ever producing anything from it. You probably recognize this mode. The thing that separates a curious person from a curious person with leverage is the question: what am I building with what I'm learning? The learning has to be oriented toward something, has to deposit into a project or a problem or a question you're actually trying to answer, or it dissipates without compounding. The other thing to stop: learning at the level of familiarity rather than the level of understanding. You know when you actually understand something versus when you just know about it. Stop letting the familiarity feel like enough.",

    'The Strength You\'re Underusing':
      "You're probably underusing your curiosity in service of other people's thinking. The depth of understanding you bring to topics makes you exceptionally well-positioned to help others navigate domains they're trying to learn — not as a teacher in the formal sense, but as the person who can explain the structure of a field, surface the non-obvious questions, and point toward the things worth paying attention to. This is a form of intellectual leverage that often goes undeployed because curious people tend to orient their curiosity inward rather than outward. Turning it toward the people around you — genuinely trying to understand how they think, what they're trying to figure out, what would help them go deeper — tends to compound in ways that pure individual learning doesn't.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, choose one domain that matters for your current work and commit to going significantly deeper than you currently have. Not a survey course — a deep dive. Read primary sources. Find the people who actually built the field, not the people who summarize it. Track what changes in your thinking and your output as a result. In parallel, identify one project or question that your curiosity can organize around rather than just illuminate. Something you're actually trying to figure out, not just learn about. The orienting question is the difference between learning that compounds and learning that evaporates. By day 90, the target is: one domain where you have understanding rather than familiarity, and one project that demonstrates what that depth can produce.",
  },

  Judgment: {
    'Your Leverage Profile':
      "Your leverage is decision quality — specifically, the quality of your read in situations where the relevant variables are complex, competing, or partially obscured. You've developed, probably through a combination of experience and natural aptitude, the ability to sort relevant from irrelevant, to identify the thing that actually matters in a situation rather than the thing that presents most loudly. This is rarer than most people realize. Most decisions get made on the most available information, the most recent data, the most vocal advocate. You have the capacity to cut through that and ask what's actually true, what's actually at stake, what the situation actually calls for. That capacity is valuable in proportion to the stakes of the decisions you're involved in. Judgment at low stakes has modest impact. Judgment at high stakes — in the room where consequential decisions get made — is a multiplier on everyone and everything around you.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is being selective about when you offer your read. This seems counterintuitive — shouldn't you share good judgment broadly? — but the selectivity is what makes it valuable. When someone is always willing to weigh in, always has an opinion, always offers a take, the signal gets averaged down by the noise. People stop treating the input as premium. When you're known as someone who speaks carefully, who waits until they have something real to offer, who says 'I don't have a useful view on this one' with some regularity — when you do weigh in, people listen differently. The ROI move is being the most trusted read in the room, not the most frequent one. And being trusted means being legible: offering your reasoning, not just your conclusion, so people can calibrate on the quality of your thinking rather than just the confidence of your delivery.",

    'What to Stop Doing':
      "Stop offering judgment on things that don't warrant it, and stop offering judgment prematurely on things that do. The first is about selective deployment — not every conversation needs your read, and inserting one dilutes the signal. The second is about patience: good judgment often requires more time with a situation than feels comfortable, and the instinct to call something before you've fully sat with it is a quality leak. There's also a specific trap for people with strong judgment: the conclusion comes fast, but the explanation comes slow, and the temptation is to share the conclusion without doing the work of articulating the reasoning. That's a form of lazy judgment that erodes the trust that good judgment is supposed to build.",

    'The Strength You\'re Underusing':
      "You're probably underusing your judgment as a mentoring asset. The ability to see clearly in complex situations is something that develops over time and with experience, and people who are earlier in that development are often desperate for exposure to someone who actually has it. Sharing not just your conclusions but the specific way you're thinking through a situation — what you're weighting, what you're discounting, what question you're actually trying to answer — is a high-value transfer that most good-judgment people don't think to make explicit. You're also likely underusing your judgment in the domain of identifying bad decisions before they're made, which is different from diagnosing decisions after they've gone wrong.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, identify two or three decisions — in your work, organization, or personal domain — where your judgment could have the most downstream impact, and invest specifically there. For each one, write down your read before the outcome is known: what do you actually think, why, and what would change your mind? This practice sharpens the calibration loop that good judgment depends on. In parallel, practice selective silence in low-stakes situations where you'd normally offer an opinion. Track whether your input in high-stakes situations lands differently. By day 90, the goal is a clearer sense of where your judgment creates the most return and a strengthened habit of deploying it there rather than everywhere.",
  },

  Perspective: {
    'Your Leverage Profile':
      "Your leverage is context-setting — the ability to help people and systems see what they're too close to see themselves. You operate at a level of abstraction that isn't always natural for people who are deep in the work, close to the problem, or invested in a particular outcome. That distance is the thing. It lets you see patterns that proximity obscures, trade-offs that tunnel vision misses, and the relationship between things that seem unrelated until someone draws the line between them. This is particularly valuable in moments of decision, when organizations or teams are about to commit to a direction without having fully understood the map of the terrain they're about to enter. You are, at your best, the person who provides that map. The challenge is that perspective-holders often don't realize they're doing something distinct from what everyone else is doing — because it feels like just seeing clearly, which seems like it should be accessible to everyone.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is helping people and systems see themselves from the outside. This sounds abstract but is concrete in practice: being the person who can tell an organization, team, or individual what they look like to the people they're trying to serve, what patterns are visible in their behavior that they can't see themselves, what the gap is between their stated direction and their actual trajectory. This is useful at every scale — from a one-on-one conversation where you help someone understand how they're being perceived, to an organizational strategy session where you can articulate why the strategy isn't landing the way they think it is. The ROI of this move is high precisely because self-perception is so systematically unreliable. People and systems have enormous blind spots about themselves, and someone who can see clearly from outside those blind spots is offering something that can't be produced internally.",

    'What to Stop Doing':
      "Stop offering perspective without making it actionable. The view from above is genuinely useful, but if it doesn't translate into something that people can do with it, it functions more as observation than as leverage. The best perspective-holders are not just people who see clearly but people who can bring what they see down to the level of concrete implication: here is what I see, here is what it means for what you do next. There's also a tendency for perspective-holders to stay in advisory mode when the situation calls for directness — to offer the view rather than the recommendation. Sometimes that's the right call. Other times it's a form of maintaining distance that lets you be right without taking responsibility for the outcome.",

    'The Strength You\'re Underusing':
      "You're probably underusing your perspective as a diagnostic tool for your own systems and projects. It's common for people with strong contextual perspective to see other people's situations clearly and their own less so — because the emotional proximity to your own work collapses the distance that makes the strength operate. Building a practice of deliberately stepping back from your own projects to look at them the way you'd look at someone else's tends to surface exactly the kinds of things you'd catch immediately in an external review. You're also likely underusing your perspective in written form — the ability to articulate a clear-eyed view of a complex situation is rare and valuable in writing, where it can reach and influence people beyond the room.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, take on one explicit perspective role: offer to do a review, a retrospective, or a strategic read for a project, team, or organization other than your own primary work. Go in specifically as the outside view, not as a subject matter expert. Track what you see that they don't and whether your perspective changes the conversation. In parallel, apply the same perspective discipline to one of your own projects: schedule a monthly hour where your only job is to look at it from the outside and write down what you see. By day 90, the goal is a clearer articulation of where your perspective is most needed and a stronger habit of deploying it with actionable specificity rather than just clear observation.",
  },

  Bravery: {
    'Your Leverage Profile':
      "Your leverage is initiation — the willingness to move first, say the thing others are thinking but won't say, start the conversation that the room has been circling around, make the call that requires accepting visible risk. Bravery as a character strength is sometimes romanticized into something dramatic, but in everyday professional and personal contexts, what it usually means is a higher-than-average threshold for tolerating social discomfort in service of something important. You can say the true thing when saying it requires absorbing some cost. Most people can't, reliably, when the cost is visible and immediate. This is where your leverage sits. The things that don't get said, the decisions that don't get made, the conversations that don't happen — these have real costs in organizations and relationships, and you have the capacity to bear the friction of initiating them.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is being the person who says the thing that's actually true in situations where the social cost of saying it is real but the cost of not saying it is higher. This sounds simple, but the consistent willingness to do it — meeting after meeting, conversation after conversation, not just when it's easy but when it's genuinely uncomfortable — is what separates someone with the strength of bravery from someone who is just occasionally blunt. The ROI compounds through reputation: when people know you can be trusted to say what's actually happening rather than what's socially convenient, they bring you into the conversations that matter. You become the person who gets asked into the room where the hard thing needs to be named. That access is where your leverage multiplies.",

    'What to Stop Doing':
      "Stop confusing bravery with aggression, and stop using your higher threshold for discomfort as a reason to skip the preparation that makes hard things land productively. There's a version of this strength that has gone sideways: the person who says the hard thing without care for how it's received, who mistakes bluntness for honesty, who doesn't distinguish between the courage it takes to say something difficult and the thoughtlessness of saying it carelessly. Bravery is not an exemption from tact. The true thing said badly is often less effective than the true thing said well, and 'I'm just being honest' is not an adequate substitute for thinking about how to be honest usefully. The goal is impact, not catharsis.",

    'The Strength You\'re Underusing':
      "You're probably underusing your bravery in the domain of starting things rather than just saying things. The initiation that bravery makes possible isn't only conversational. It includes moving first on projects that feel risky, committing to directions before all the uncertainty has resolved, putting something out into the world before it's fully finished, asking for things that might get refused. These are all forms of bravery that require the same tolerance for discomfort that the conversational version does, but they operate over longer time horizons and often have larger leverage. You may also be underusing your bravery as a permission structure for people around you — when you move first, you make it easier for others to follow.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, identify one conversation you've been avoiding and have it — with the preparation that makes it useful, not just honest. Track what changes as a result. In parallel, identify one thing you've been waiting to start until conditions were better, more certain, or more ready, and start it now. The initiation is the experiment. By day 90, the goal is two data points: one on what your bravery makes possible in conversation, one on what it makes possible in action. Use those to calibrate where your highest-leverage initiation opportunities are and where you're leaving impact on the table by waiting.",
  },

  Honesty: {
    'Your Leverage Profile':
      "Your leverage is trust-building at speed. In a world full of managed impressions, strategic communication, and people saying what they think others want to hear, the person who is consistently, legibly honest is a genuinely unusual resource. People calibrate to you faster because you're readable. They don't have to spend energy trying to figure out what you're not saying, what your real agenda is, what the gap is between your stated view and your actual one. That calibration shortcut is valuable in every relationship context — professional, personal, collaborative — because it reduces the interpretation overhead that eats up so much relational bandwidth. The leverage compounds through reputation: once you're known as someone who tells the truth, people bring you their real problems instead of the sanitized versions.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is making yourself available as the person others bring real problems to. This requires a combination of honesty and accessibility — being someone who will tell the truth, and someone who is worth talking to precisely because of that. The ROI shows up in the quality of conversations you have access to: when people trust you to give them an accurate read rather than a comfortable one, they bring you the problems that actually matter to them rather than the ones they've already figured out. Being known for this — cultivating the reputation actively rather than assuming it will develop organically — means more interesting conversations, more meaningful collaboration, and greater influence over outcomes that matter.",

    'What to Stop Doing':
      "Stop treating honesty as a passive quality and start treating it as an active practice. Being honest when asked isn't the same as offering honest perspective when it would help but hasn't been solicited. The leverage of your strength comes from the proactive version — from volunteering an accurate read when you notice someone is missing something important, not just confirming the truth when someone asks directly. There's also a specific failure mode worth naming: honesty deployed without relational attunement can damage the trust it's supposed to build. The goal is to be the person whose honesty people want, not the person whose honesty people brace for. The difference is in how it's offered, not in whether it's true.",

    'The Strength You\'re Underusing':
      "You're probably underusing your honesty in the domain of self-disclosure — being honest about your own uncertainty, your own limits, your own mistakes. There's a version of honesty that's primarily directed outward (accurate feedback about others, accurate reads of situations) while maintaining careful management of inward disclosures. The trust that honesty builds tends to deepen significantly when people see that your honesty extends to yourself: that you'll say 'I was wrong,' 'I don't know,' 'I got that backward.' That transparency about your own fallibility is often more trust-building than any number of accurate reads about external situations.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, practice one instance per week of proactive honest input — offering a true perspective in a situation where it would help but wasn't requested. Track how it lands and what changes as a result. In parallel, practice one instance per week of honest self-disclosure — naming something you got wrong, don't know, or are uncertain about, in a context where you'd normally manage the impression more carefully. By day 90, the goal is a clearer sense of where your honesty creates the most relational return and a habit of deploying it actively rather than waiting to be asked.",
  },

  Kindness: {
    'Your Leverage Profile':
      "Your leverage is relational maintenance — the ability to make hard things easier to be around, to lower the friction in systems that would otherwise generate unnecessary conflict, to make people feel genuinely seen in ways that most interactions don't. This is undervalued as a strategic asset, partly because it doesn't produce obvious artifacts and partly because it tends to prevent problems rather than solve them, which means the return is measured in things that didn't go wrong rather than things that went right. Kindness at scale — the consistent, non-performative, actually-paying-attention version — is one of the more powerful lubricants in any collaborative system. The people who have it and deploy it reliably tend to be the ones that organizations and relationships cannot function well without, even when the formal accounting doesn't capture their contribution.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is being the person who makes hard things easier to navigate, specifically in high-stakes or high-tension situations where most people are focused on their own position. During a difficult negotiation, a team conflict, a hard feedback conversation, a decision with real losers — the person who can be genuinely kind without being soft, who can acknowledge what's hard for everyone involved without losing their ability to also advocate for what's right, is doing something rare. This isn't conflict avoidance. It's the opposite: it's the willingness to be in the hard thing and bring humanity to it. That combination — clarity about what needs to happen, genuine care for the people it's happening to — is your most distinctive mode.",

    'What to Stop Doing':
      "Stop letting your kindness function as a reason not to say difficult things. This is probably the most common leverage leak for people with your strength: kindness that becomes a form of protection for others from necessary discomfort. The person who never challenges, never gives hard feedback, never lets things be uncomfortable because they care too much about the other person's immediate emotional state is deploying their kindness in a way that ultimately doesn't serve the people they care about. Real kindness sometimes looks like saying the true thing, holding a limit, refusing to enable a pattern that isn't working. Being willing to be kind and direct at the same time is the upgrade that turns this strength from a softening agent into a genuine force.",

    'The Strength You\'re Underusing':
      "You're probably underusing your kindness as a trust-building tool in formal or professional contexts where it tends to get suppressed in favor of appearing appropriately serious. There's a widespread assumption that warmth and competence trade off against each other in professional environments, and people with the strength of kindness sometimes over-correct toward a flatter, more businesslike mode to avoid being underestimated. The data actually suggests the opposite: warmth is the first thing people assess in evaluating whether to trust someone, and competence is the second. Leading with genuine care — in professional contexts as much as personal ones — tends to accelerate trust in ways that the alternative doesn't.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, identify one context where you've been suppressing your kindness in favor of appearing more formal or competent, and experiment with being more openly warm there. Track whether it changes the quality of your interactions. In parallel, identify one relationship or situation where your kindness has been preventing a necessary hard conversation, and have that conversation — with your kindness present in how you have it, not absent from whether you have it. By day 90, the goal is a clearer sense of where your kindness creates the most relational leverage and a stronger ability to deploy it alongside directness rather than instead of it.",
  },

  'Social Intelligence': {
    'Your Leverage Profile':
      "Your leverage is your ability to read and navigate the human layer of any system — to understand what's actually happening between people, not just what's officially happening. You pick up on dynamics that others miss: the tension underneath the agreeable surface, the real objection hiding behind the stated one, the relationship history that's shaping a conversation everyone is pretending is purely logical. This social reading isn't just observation — it's information that you can use to navigate, translate, and intervene in ways that move things forward. In any system involving people (which is every system that matters), someone with this ability operating at a high level is an enormous asset. The challenge is that social intelligence is invisible when it's working and only visible when it's absent.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is being the translator between people who can't quite hear each other. Every team, organization, and relationship has these gaps: the technical person who can't make themselves understood to the business side, the leader whose message is getting distorted before it reaches the people who need to act on it, the two stakeholders whose positions seem incompatible but whose underlying interests are actually aligned. You can see what's happening in these situations with unusual clarity, and you have the relational skill to build the bridge between them. This translation role is high-leverage because it's a force multiplier: when you help two people actually understand each other, you unlock everything they could produce together that the misunderstanding was blocking.",

    'What to Stop Doing':
      "Stop using your social intelligence to read situations without acting on what you read. This is the subtle failure mode: you understand exactly what's happening in a room, exactly why it's going wrong, exactly what would help — and you do nothing with it because acting requires a kind of visibility you're not comfortable with. The reading is only half the leverage. The other half is the intervention, and interventions require accepting that you might be wrong, might be unwelcome, might create friction of their own. Your social intelligence can become a form of sophisticated observing that doesn't move anything. The leverage is in the doing, not just the seeing.",

    'The Strength You\'re Underusing':
      "You're probably underusing your social intelligence to build bridges at the level of systems rather than individual relationships. You're likely good at the one-on-one version — understanding a specific person, navigating a specific dynamic. The scale-up is using that same acuity to read organizational or group dynamics and intervene at that level: who in this system isn't hearing who, where is the friction that's costing the most, what structural thing would change the relational dynamic for everyone? The individual and the systemic versions of your strength tend to feel different, but they draw on the same underlying capacity.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, identify one translation opportunity — a gap between two people or groups that you can see clearly and have the position to bridge — and intervene deliberately. Track what changes. In parallel, practice narrating at least some of your social reads to the people involved: not 'I can see that you're in conflict,' but 'here's what I think is making this hard, and here's what I think you both actually want.' The articulation is the leverage; the read alone doesn't move anything. By day 90, the goal is at least one concrete example of your social intelligence changing a real outcome, not just your understanding of it.",
  },

  Leadership: {
    'Your Leverage Profile':
      "Your leverage is activation — the ability to unlock other people's capacity rather than just your own. Leadership as a character strength isn't about formal authority or title; it's about the capacity to orient groups, sustain momentum, and make decisions that the people around you couldn't quite make without you. The ROI of this strength is multiplicative rather than additive: when your decisions unlock other people's capacity, the output is the sum of what everyone can do, not just what you can do. This is the thing that distinguishes leadership as a leverage point from individual performance as a leverage point. One person at full capacity is bounded. One person at full capacity who's also activating three or five or ten others is a different kind of entity.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is making decisions that clear the path for others — not just the decisions that advance your own work, but the ones that remove the blockers, resolve the ambiguities, and establish the clarity that other people need to move. This often means making calls before you're fully certain, accepting the risk of being wrong so that other people don't have to wait. It also means investing in the specific decisions that have the highest leverage on others' output: the direction call that ends the debate and lets the team execute, the conflict resolution that unblocks the relationship, the resource allocation that gives someone what they need to actually do the thing. Your leadership ROI is proportional to the quality and speed of your unblocking decisions.",

    'What to Stop Doing':
      "Stop doing things that others could do in order to reserve time and energy for the things only you can do. This is the execution trap: leaders who are effective at doing things tend to default to doing things, because doing things produces visible results and feels productive. But the leadership leverage is in the activating, not the doing. Every hour you spend executing work that someone else could execute is an hour not spent making the decisions, providing the direction, and building the conditions that multiply everyone's output. The discipline of delegation — not as an organizational courtesy but as a strategic choice about where your leverage is highest — is the ongoing practice this strength requires.",

    'The Strength You\'re Underusing':
      "You're probably underusing your leadership in the domain of developing others' leadership capacity. The most leveraged form of your strength is not leading but producing more leaders — people who can make activation decisions themselves, who can orient groups and sustain momentum in contexts where you're not present. This is slower and harder than leading directly, and the return timeline is longer, but the compound effect is significant. Every person you develop into an effective decision-maker multiplies your leverage by their entire future output.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, identify the three highest-leverage decisions on your plate — the ones where your call would do the most to unlock other people's capacity — and prioritize making those before anything else. In parallel, identify one person in your sphere who has leadership potential and invest deliberately in their development: give them a real decision to make, debrief it with them afterward, and track what they learn. By day 90, the goal is a clearer map of where your leadership creates the most activation return and at least one person further along their own leadership development because of your investment.",
  },

  Fairness: {
    'Your Leverage Profile':
      "Your leverage is legitimacy — the quality that makes people trust the process even when they don't like the outcome. In any system involving allocation of resources, recognition, opportunity, or consequence, the person whose process people trust is the person whose decisions stick. Decisions made without legitimacy generate backlash, workarounds, and resentment even when they're substantively correct. Decisions made with legitimacy — where people believe the process was genuinely fair even if they disagree with the result — tend to be accepted and implemented. You, operating at your best, produce that legitimacy. People may not always get what they wanted from a process you ran, but they tend to believe it was run honestly.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is being the person whose process people trust even when they dislike the outcome. This requires actually building that trust through consistent, visible fairness — not just doing the right thing, but being legible about how and why you're doing it. The ROI move is volunteering to run processes where legitimacy is the critical variable: conflict resolution, resource allocation, performance evaluation, anything where the perception of fairness is as important as the substance of the decision. Your presence in those processes doesn't just improve the outcomes — it improves the acceptance of those outcomes, which is often what determines whether a decision actually gets implemented.",

    'What to Stop Doing':
      "Stop applying the same level of fairness processing to every situation. Not every decision warrants the same rigor of fair-process consideration, and over-applying the process in low-stakes situations is a drag on speed and a signal leak — when everything gets the full fair-process treatment, the situations that actually need it become harder to distinguish. The other thing to stop: confusing fairness with equal treatment. Treating everyone exactly the same is sometimes the most unfair thing you can do, because people are in genuinely different situations with genuinely different needs. Your strength is justice, not sameness, and knowing the difference is what makes your fairness worth trusting.",

    'The Strength You\'re Underusing':
      "You're probably underusing your fairness in the domain of advocacy — using your legitimacy and credibility to speak up for people or outcomes that aren't getting a fair hearing in systems you're part of. The fair-process orientation that makes you trusted as an adjudicator also gives you standing to say 'this isn't right' in ways that people listen to. That standing is a form of leverage in its own right, and it tends to go unused by people who associate their strength with running processes rather than initiating challenges to unfair ones.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, volunteer to run one process where legitimacy is the critical variable — an evaluation, an allocation, a conflict resolution — and do it with explicit transparency about how you're making decisions and why. Track whether the outcome is accepted differently than it would be otherwise. In parallel, identify one situation where something unfair is happening and use your credibility and legitimacy to name it. By day 90, the goal is clearer evidence of where your fairness creates the most leverage and at least one instance of using that leverage to advocate rather than just adjudicate.",
  },

  Humility: {
    'Your Leverage Profile':
      "Your leverage is learning rate and trust, and they're connected in a specific way. Because you're genuinely open to being wrong, you update faster than people who are invested in being right. You get better faster. You incorporate feedback that others filter out because it threatens their self-image. You're willing to sit in the discomfort of not knowing rather than retreating into the comfort of a position you've already staked. This is a compounding advantage: over time, the person who updates accurately and consistently develops a more accurate model of reality than the person who defends their existing model against evidence. The trust dimension is equally real: people who are genuinely humble — not performatively self-deprecating, but actually coachable — tend to generate significant trust, because they're demonstrably more interested in the truth than in being seen as having had it all along.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is being genuinely coachable in a visible and consistent way — modeling what it looks like to take feedback, update your position, and acknowledge error without it being a catastrophe. This sounds small, but in most contexts it's genuinely rare, and it has outsized downstream effects. When you update visibly, you accelerate the feedback loops that others are getting more slowly, and you create a social permission structure for the people around you to do the same. Organizational and relational cultures change through permission structures: when someone with standing demonstrates that it's safe to be wrong and learn from it, the whole system moves. You are often that person.",

    'What to Stop Doing':
      "Stop letting humility tip into self-effacement that undercuts your own credibility. There's a version of this strength that has miscalibrated: the person who so consistently defers, qualifies, and yields that their actual views and capabilities stop registering for the people around them. Humility is about accurate self-assessment, not systematic self-underestimation. If you're genuinely good at something, saying so — directly, without hedging — is humility operating correctly. Understating your capacity isn't humble; it's a different kind of inaccuracy. The target is the version of humility that includes honest acknowledgment of both limits and strengths.",

    'The Strength You\'re Underusing':
      "You're probably underusing your humility as an explicit practice — creating formal feedback structures rather than just being open to informal feedback when it arrives. The person with genuine humility who also actively solicits feedback, builds in systematic review of their own work and decisions, and creates opportunities for correction tends to develop significantly faster than the person who is just generally open to input. The proactive version of coachability is substantially more leveraged than the reactive version, because it catches the things that wouldn't have been said without being asked.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, build one explicit feedback structure: a monthly conversation with someone whose judgment you trust specifically about what you're getting wrong and where you're improving. Make the format specific — not 'how am I doing' but 'what's the most important thing I should be doing differently?' Track what you learn and what you change as a result. In parallel, practice one instance per week of updating publicly: saying 'I was wrong about that' or 'I changed my mind because' in a context where you'd normally just move on. By day 90, the goal is an accelerated feedback loop and at least two or three specific changes driven by input you actively sought.",
  },

  Perseverance: {
    'Your Leverage Profile':
      "Your leverage is compounding over long games. Most people are reasonably persistent when things are going well. The real sorting happens when things aren't — when the progress is invisible, when the feedback is negative, when everyone around you has moved on to the next thing, when the rational case for continuing is genuinely ambiguous. You have a constitution for this. Not because you're indifferent to difficulty, but because you've developed the capacity to stay in hard things longer than people who are waiting for clarity before they persist. This is a genuine advantage precisely because most things worth doing are hard for longer than most people can tolerate. The ventures that require three years to validate, the skills that take a decade to develop, the relationships that need to survive multiple difficult passages — these are the domains where your strength creates disproportionate return.",

    'Your Highest-ROI Move':
      "The highest-return move for your profile is entering long games that others exit too early and staying in them past the point where most participants quit. This sounds obvious as a principle but requires real discernment in practice, because not every long game is worth winning. The leverage of perseverance is only as good as the quality of the game you've chosen. Persisting in the wrong direction compounds the cost rather than the return. The ROI move, then, is a combination of your natural staying power and deliberate game selection: choosing the domains, projects, and relationships where long-term consistency creates the most distinctive advantage, and then actually staying long enough to capture it.",

    'What to Stop Doing':
      "Stop persisting uniformly across everything and start being more selective about what gets your sustained attention. Perseverance applied everywhere is perseverance that can't tell the difference between a long game worth playing and one that should have been quit six months ago. The sunk-cost problem is real and specific for people with your strength: the same constitution that keeps you in things that are worth staying in also keeps you in things that aren't, because the sensation of persisting feels the same regardless of the quality of what you're persisting toward. Building a periodic review practice — genuinely asking whether a given long game still deserves your staying power — is the corrective.",

    'The Strength You\'re Underusing':
      "You're probably underusing your perseverance as a credibility signal in how you represent yourself and your commitments. The person who is known to follow through over long time horizons, who doesn't quit when things get hard, who delivers on commitments made months or years ago — this person has a specific kind of credibility that opens doors that skill and intelligence alone don't. You may have this reputation in some domains but not made it visible or explicit in others. Being more deliberate about communicating your track record of long-game follow-through — not boastfully, but as evidence — tends to compound your credibility in proportion to the length of the record.",

    'A 90-Day Leverage Plan':
      "In the next 90 days, identify your highest-value long game — the project, relationship, or domain where sustained consistency over years would create the most disproportionate return — and make one deliberate choice that increases your commitment to it. Not a dramatic gesture but a structural one: the thing that makes it harder to quit when difficulty arrives. In parallel, do a quick audit of what else has your perseverance: is there anything you're staying in out of habit or sunk cost rather than genuine conviction? By day 90, the goal is a clearer alignment between where your staying power is going and where it would create the most long-term return.",
  },
};
