// src/lib/modules/blockSeeds.ts
// Pre-generated block seeds for each module × primary driver value.
// Each block is 100-150 words: the psychological grounding truth for this type.
// Primary drivers are documented per module below.

export const BLOCK_SEEDS: Record<string, Record<string, string>> = {

  // ─── MODULE 1: SHADOW SELF ───────────────────────────────────────────────
  // Primary driver: enneagram.primary (1-9)
  // What this type has buried and how it leaks out.
  shadow_self: {
    '1': `The One's shadow is a seething, formless mess they've spent a lifetime scrubbing clean. The inner critic — that relentless internal prosecutor — is actually the voice of their own suppressed impulsivity and rage, externalized as standards so they never have to own the chaos underneath. When they erupt over a misaligned shelf or someone else's "lazy" work, that's not about the shelf. The anger they've classified as righteous is mostly just anger, and the judgment they level at others is the shadow version of the judgment they apply to themselves twenty-four hours a day. The thing they've buried is the desire to be bad, wrong, free — and it shows up as contempt.`,

    '2': `The Two's shadow is the demand lurking beneath every gift. They've constructed an identity around being needed, which sounds generous until you realize that needing to be needed is a control strategy — if everyone depends on you, no one can leave. What they've buried is their own hunger: for recognition that doesn't have to be earned, for receiving without first giving, for existing without justifying that existence through service. The resentment they feel when people don't appreciate them enough is the shadow breaking through — it's the proof that the love was never fully unconditional, even as they insisted it was. The thing they can't say out loud is: I do this for me too.`,

    '3': `The Three's shadow is the hollow where a self used to be. So much energy has gone into performing the winning version of themselves that they've genuinely lost track of what they actually want versus what would make them look like they have what people want. The shame they've buried isn't about failure — it's about the suspicion that if you stripped the achievements away, there'd be nobody home. The shadow leaks out as an allergic reaction to slowness, to people who seem comfortable not performing, to any moment that requires them to sit with who they are rather than what they're doing. The terror underneath is not failure. It's irrelevance.`,

    '4': `The Four's shadow is ordinary contentment — the thing they've quietly decided is beneath them. By over-investing in their uniqueness and suffering, they've made their pain into an identity, which means healing becomes threatening. If the wound closes, what's left? They've buried the capacity for simple, uncomplicated okay-ness, and it leaks out as contempt for people who seem happy with ordinary lives, as manufacturing intensity in relationships that are getting too stable, as the low hum of envy toward people who seem to have the very groundedness Fours push away. The uncomfortable truth is that some of the suffering is chosen — not consciously, but chosen.`,

    '5': `The Five's shadow is the body, the need, the unmanageable fact of depending on other people. They've survived by contracting — less need means less exposure means less vulnerability — and they've convinced themselves this is wisdom rather than fear. What they've buried is longing: for full contact with people, for being seen as more than a thinking machine, for the kind of intimacy that can't be scheduled and controlled. The shadow leaks out as arrogance (my analysis beats your experience), as contempt for people who are "too emotional," and as a strange loneliness that they refuse to name as loneliness because naming it would require admitting they wanted connection in the first place.`,

    '6': `The Six's shadow is the inner authority they've been outsourcing to everyone else. By building elaborate systems of loyalty, skepticism, and worst-case planning, they've avoided having to trust their own judgment — because if they're wrong and they trusted themselves, there's no one else to blame. What they've buried is their own competence and the quiet arrogance of thinking their fear-scanning is more accurate than reality. The shadow leaks out as subtle sabotage when things go too well (good things are suspicious), as projection — seeing danger and betrayal in people who are probably fine — and as a hot flash of reactivity when someone they've deputized as authority disappoints them. The thing they can't say is: I don't actually know if I can trust myself.`,

    '7': `The Seven's shadow is the grief they've been outrunning since the beginning. Every new plan, every pivot to the next exciting thing, every reframe of pain as "just a learning experience" is the same move: forward motion as anesthesia. What they've buried is loss — the capacity to grieve something fully, to let a failure or a disappointment sit in them without being immediately metabolized into optimism. The shadow leaks out as a subtle cruelty toward people who are "stuck" in their pain, as commitment phobia disguised as keeping options open, and as a nagging anxiety that hits hardest in the quiet moments when there's nothing to be excited about. The thing underneath is not boredom. It's grief.`,

    '8': `The Eight's shadow is tenderness — the vulnerability they concluded early on was a weapon other people would use against them. They've built ferocity and force as a habitat, which works until you realize they've also made it impossible to receive care without feeling diminished. What they've buried is the need to be held, not managed, and the fear that if they stop controlling every room they're in, something terrible will happen. The shadow leaks out as contempt for weakness in others (which is contempt for weakness in themselves), as escalation when they feel handled or patronized, and as a rageful protectiveness toward people they love that can feel indistinguishable from control. The thing they've never said: I'm scared too.`,

    '9': `The Nine's shadow is the anger they've medicated into numbness. Their entire operating system is built around conflict avoidance — which sounds peaceful until you realize that swallowing twenty years of resentment and preference-erasure is not peace, it's a slow-motion implosion. What they've buried is their own will, their own priorities, their own sense that what they want matters. The shadow leaks out as passive resistance (agreeing to things they'll quietly not do), as sudden volcanic rage when the lid finally comes off, and as a profound inertia that looks like laziness but is actually a refusal — the one form of agency they still exercise. The thing they can't say: I have opinions. I have fury. I've just decided neither of them is safe.`,
  },

  // ─── MODULE 2: COGNITIVE BIAS ────────────────────────────────────────────
  // Primary driver: cognitiveDistortions.top3[0]
  // The core cognitive bias pattern and how it distorts perception.
  cognitive_bias: {
    'catastrophizing': `Catastrophizing is not irrationality — it's a nervous system that learned early that if you don't anticipate the worst, the worst will surprise you. The bias runs as a background simulation: take any ambiguous signal, fast-forward to the worst plausible outcome, and treat that outcome as information rather than projection. The actual distortion isn't the fear, it's the certainty — the way a bad scenario gets promoted from possibility to probability without passing through evidence. This creates a life where threat-detection is highly calibrated but threat-assessment is not, where real risks and imagined catastrophes receive equal cognitive weight, and where the exhausting work of pre-catastrophizing things that never happen is invisible because it's been reframed as responsible preparation.`,

    'mind_reading': `Mind reading is the belief that you already know what people think of you — usually something disappointing — and that checking would just confirm it. The bias runs constantly in social situations, generating confident interpretations of silence, tone, and facial expressions that feel like perception but are actually projection. The core distortion is treating internal predictions as external data: because it feels like you know what someone meant, it never occurs to you to verify. This produces a social life organized around managing a judgment that may not exist, where real conversations get filtered through an imagined meta-conversation about what the other person is secretly thinking. The uncomfortable truth is that the harsh critic in the mind-reading loop is usually a version of the person's own self-judgment, not an accurate rendering of anyone else.`,

    'all-or-nothing thinking': `All-or-nothing thinking is efficiency taken too far: the brain collapses a continuum into a binary because nuance is expensive and certainty is fast. The distortion runs on a switch rather than a dial — things are succeeding or failing, people are trustworthy or not, efforts are worth it or pointless — which means the middle ground where most of reality lives gets systematically ignored. The cost isn't just cognitive; it's motivational. A diet broken by one cookie, a project declared a failure at the first obstacle, a relationship written off after one bad week — all casualties of a filtering system that can't represent partial progress. The pattern is self-reinforcing: because the standards are total, failure is frequent, which confirms the belief that total standards are necessary.`,

    'personalization': `Personalization is the cognitive habit of auditing every negative event for your contribution to it, and consistently overestimating that contribution. When something goes wrong in a system — a relationship, a project, a social dynamic — this bias fast-tracks to personal responsibility before examining external factors, other people's roles, or simple chance. It's worth noting that this isn't purely self-flagellation: personalization also implies a kind of centrality — if it's your fault, you had power over it, which is less terrifying than accepting that bad things happen in systems you can't control. The distortion produces both chronic guilt (for things that weren't yours to own) and a chronic over-inflation of self-agency in situations that were always more complex than one person's choices.`,

    'over-responsibility': `Over-responsibility is what happens when the nervous system decides that the safest way to exist in relationship is to make sure everything is okay for everyone, all the time. The cognitive distortion runs as a constant background audit: is anyone uncomfortable? Is anything wrong? Whose fault is it? Am I doing enough? The core error is category confusion — treating other people's emotional states as your functional responsibility rather than your concern. This distortion is often invisible because it looks like conscientiousness and care from the outside, and it feels like character from the inside. The cost is a life organized around managing a sprawling field of variables you can't actually control, with a persistent low-grade guilt about the ones that slip through anyway.`,

    'discounting_positives': `Discounting positives is a quality control process pointed in the wrong direction: incoming evidence of success, capability, or worth gets systematically downgraded before it can register. Compliments become "they're just being nice." Achievements become "anyone could have done that." Good feedback becomes "they don't know the full picture." The distortion functions as a one-way valve — negative information passes through at full strength, positive information gets filtered to near-zero. This isn't false modesty; it's a belief system about the kind of person you are, and the brain is just doing its job of confirming that belief by routing contradictory evidence through the discount mechanism. The result is a person who has more evidence of their capability than they can actually hold.`,
  },

  // ─── MODULE 3: INTERNAL CONFLICT ─────────────────────────────────────────
  // Primary driver: enneagram.primary (1-9)
  // The central internal war this type fights.
  internal_conflict: {
    '1': `The One's central war is between the person they are and the person they believe they should be — and it never ends because the "should" has no ceiling. They genuinely want to do good, to be good, to improve things — and that impulse is real and admirable. But it's in constant civil war with the human reality of being imperfect, tired, and sometimes wrong, a reality they experience not as information but as indictment. The tension runs in both directions: self toward world (nothing is ever quite right) and world toward self (I am never quite right). Freedom would require forgiving themselves, which feels like lowering standards, which feels like betrayal of everything they've built their identity on.`,

    '2': `The Two's internal war is between genuine love and the terror of not being loved back. They've fused their care for others with their self-worth management so completely that it's almost impossible to disentangle: is this gift given freely, or is it a bid for safety? The answer is usually both, which is the problem. They war between the desire to rest — to stop earning their place — and the belief that without the giving, the place disappears. There's also a quieter conflict between who they are in service of others and who they might be if they ever stopped long enough to ask. The version of themselves that exists outside of other people's needs is a stranger they're not sure they'd like.`,

    '3': `The Three's internal war is between performing and being. They've become so skilled at the performing — reading rooms, optimizing impressions, becoming whoever succeeds here — that the being side has atrophied from disuse. The conflict emerges as a haunting question they can't quite formulate: is any of this actually what I want, or is it just what wins? Slowing down is threatening because the gap between doing and feeling opens up, and what lives in that gap might be emptiness, or grief, or worse — desire that doesn't fit the winning image. They're simultaneously the most adaptive people in the room and the most at risk of waking up one day having built an entire life for an audience rather than for themselves.`,

    '4': `The Four's central war is between the longing to be fully known and the conviction that being fully known means being rejected. They've constructed an identity around depth and uniqueness — which requires them to be seen — but their vulnerability is so charged that real seeing feels unbearable. So they oscillate: pull people in with intensity, push them away when the closeness activates shame, then grieve the distance they created. There's also a war between the desire to be special and the desire to belong — needs that feel mutually exclusive but are both desperately real. The sadness they carry is partly genuine and partly functional: it marks them as different, and different is the only safe version of significant they've found.`,

    '5': `The Five's internal war is between the life of the mind, where they're sovereign and safe, and the life of the body and relationship, where they're dependent and exposed. They've been convinced — usually by early experience — that their internal world is the only one they can fully control, which makes the external world feel like a resource extraction problem: people take energy they can't replenish, situations demand presence they can't afford. The war runs as: I want to connect / connecting depletes me / depletion feels like dissolution / so I withdraw / which produces loneliness / which I explain rather than feel. They're fighting a battle between the desire for full aliveness and the belief that full aliveness will cost them everything they use to stay safe.`,

    '6': `The Six's internal war is between their own judgment and the authority they've outsourced it to. They're perpetually scanning for trustworthy structures — people, institutions, frameworks — to anchor to, and perpetually disappointed when those structures fail or turn ambiguous, which they always eventually do. The conflict runs in two directions at once: they fear authority (what if it's wrong? what if it betrays them?) and they fear the absence of authority (what if I'm on my own and I'm wrong?). This produces a type that can be simultaneously over-deferential and fiercely contrarian — the same ambivalence playing out in opposite directions depending on context. The thing they're really fighting is the question they can't answer: can I actually trust myself?`,

    '7': `The Seven's internal war is between freedom and depth. They've decided — usually below conscious awareness — that commitment means foreclosure, that going deep in one direction means losing all the other directions, that staying in one feeling long enough to really feel it might mean getting stuck there. So they run: between options, between projects, between experiences, always optimizing for possibility. The conflict is that the running is also costing them the thing they actually want, which is not more options but more meaning — and meaning is assembled from commitment, from staying, from the willingness to let something matter enough to disappoint you. The Seven is at war between the life they're living (wide, fast, stimulating) and the life they're built for (wide and fast and also, finally, rooted).`,

    '8': `The Eight's internal war is between the need to be strong and the fear of what it means to need anything. They built their identity on force, on being the one who doesn't flinch, on protecting themselves and others from a world they correctly assessed as not always safe. But strength as identity forecloses the rest of the self — the softness, the need, the capacity to receive care without experiencing it as a threat. The war runs as: I want intimacy / intimacy requires vulnerability / vulnerability is exposure / exposure is danger / so I maintain control / which keeps intimacy at arm's length / which eventually produces a profound loneliness they can't fully name because naming it would be the vulnerability they've been preventing.`,

    '9': `The Nine's internal war is between their own existence and the peace they've traded it for. To avoid conflict, they've been making themselves smaller — preferences first, then opinions, then presence — until they've achieved a kind of frictionless invisibility that feels like peace but is actually disappearance. The conflict lives in the gap between the absence of external conflict (which they've engineered) and the presence of internal conflict (which they've swallowed). They've suppressed their own will so thoroughly that when they try to locate what they actually want, there's static. The deepest war is not between the Nine and other people — it's between the Nine and the Nine: the part that wants to exist fully, loudly, specifically, and the part that decided that existing fully, loudly, specifically is not worth the risk.`,
  },

  // ─── MODULE 4: NARRATIVE IDENTITY ────────────────────────────────────────
  // Primary driver: attachment.style (secure, anxious, avoidant, disorganized)
  // The dominant life narrative this attachment style creates.
  narrative_identity: {
    'secure': `The secure attachment style generates a narrative of earned trust — not naivety, but a foundational expectation that people are broadly capable of good faith and that ruptures are survivable. The life story tends to be structured as a bildungsroman: growth, challenge, relationship, integration. There are villains and setbacks, but they don't contaminate the whole text. This isn't because securely attached people have had easier lives — it's because their internal working model doesn't convert difficulty into evidence that love is unsafe. They're the builders: people who can tolerate conflict without catastrophizing about it, who can repair without shame, who can leave unhealthy situations without either clinging or burning everything down. The story they tell about themselves is fundamentally coherent.`,

    'anxious': `The anxious attachment style generates a narrative of proximity management — a life story organized around the question of whether the people who matter are still there, still satisfied, still close enough. The hero of this story is perceptive and loving and often exhausted: always reading the room, always scanning for the early signs of withdrawal, always recalibrating behavior to maintain closeness. The central dramatic tension is never the external plot — it's the emotional weather of key relationships. This creates people who are profoundly empathic (they've had to be) and profoundly self-doubting (the hypervigilance turns inward too). The narrative tends to have an unspoken hypothesis baked into it: I am the kind of person people leave, and everything I do is evidence for or against that.`,

    'avoidant': `The avoidant attachment style generates a narrative of self-sufficiency — a life story where needing people is the vulnerability that gets you hurt, and independence is both the survival strategy and the identity. The hero of this story is capable, competent, and privately lonely in a way they rarely name aloud. They've rewritten the emotional plot into a logistical one: problems are to be solved, needs are to be managed, feelings are to be processed privately and efficiently. The central dramatic tension is invisible in the story they tell but visible in the life they build — a succession of relationships that get close enough to threaten the independence and are then, consciously or not, held at arm's length. The story has a clean surface and a complicated subtext.`,

    'disorganized': `The disorganized attachment style generates a narrative without a stable genre — it can be a love story, a tragedy, a thriller, and a comedy of errors in the same week, sometimes the same day. This is the attachment style formed when the source of comfort was also the source of fear, which means the nervous system never got to learn a consistent answer to the question "what do I do with this feeling?" The story they tell about themselves is often fragmented — intense highs, confusing lows, relationships that feel transformative and then inexplicably dangerous. The central conflict is between the desire for closeness (which is real) and the way closeness activates a threat response (which is also real). The narrative identity is a work-in-progress, usually more honest than most, often more painful.`,
  },

  // ─── MODULE 5: BLINDSPOT ─────────────────────────────────────────────────
  // Primary driver: selfConceptClarity bucketed as low (<0.4), medium (0.4-0.65), high (>0.65)
  // The specific blind spot pattern for this clarity level.
  blindspot: {
    'low': `Low self-concept clarity produces a blindspot that is structural rather than specific: without a stable, internally consistent sense of self, it's hard to see your own patterns because each version of yourself seems to cancel out the last one. The result is a person who can describe how they behave in this situation or with this person, but who struggles to abstract upward to "this is how I am." The blindspot isn't about lacking insight — it's that insight requires a stable observer, and the observer keeps shifting. What this produces in practice: a strong tendency to be heavily influenced by context and the people around them, an inability to predict their own reactions accurately, and a chronic underestimation of how much their self-presentation varies across relationships.`,

    'medium': `Medium self-concept clarity produces a blindspot of selective self-knowledge: they know themselves well in the domains where they've done the work, and have significant gaps in the domains they've avoided examining. The pattern looks like sophisticated self-awareness on the surface — they can speak fluently about their psychology — but there are protected areas, usually adjacent to their core wounds, where the insight stops abruptly. The blindspot is often around the gap between how they think they affect other people and how they actually do: they have an accurate internal self-model but an underdeveloped model of their social impact. They're more self-aware than most people and less self-aware than they believe.`,

    'high': `High self-concept clarity comes with an unexpected blindspot: over-confidence in the accuracy of the self-model. They know themselves well — their values, patterns, preferences, and reactions are legible to them in a way that's genuinely rare. But a stable, coherent self-concept can become a lens that filters out disconfirming evidence, and people with high clarity sometimes mistake their narrative about themselves for objective truth. The specific blindspot is around change and context: they may not notice when the self-concept has become a prescription rather than a description, when new situations are revealing genuinely new aspects of themselves that don't fit the model. They're the most likely to say "that's just not who I am" about something that might, actually, be who they are becoming.`,
  },

  // ─── MODULE 6: MOTIVATION SOURCE ─────────────────────────────────────────
  // Primary driver: motivation.primaryDriver
  // The root motivational engine and its sustainability profile.
  motivation_source: {
    'fear of failure': `Fear of failure as a primary motivational engine is jet fuel — it produces exceptional output under pressure and creates people who rarely stop moving. The mechanism is straightforward: the prospect of failing activates enough aversion that action feels less risky than inaction. But the sustainability profile is poor. Fear-driven motivation doesn't accumulate momentum the way intrinsic drive does — every success resets the threat level rather than building toward something. There's also a consistency problem: it works well when stakes are clear and failure is concrete, but struggles with long-horizon projects where failure is abstract and distant. Over time, the psychological cost of living in a constant threat-response state compounds, and burnout is less about volume of work than about the exhausting quality of the motivation underlying it.`,

    'status and approval': `Status and approval as a primary motivational engine is highly responsive to environment — it produces extraordinary effort in high-feedback contexts and significant drift in low-feedback ones. The mechanism requires an audience: performance is calibrated to what gets recognized, which means the effort profile tracks perceived reputation more than actual priorities. The sustainability problem is external dependency: this engine is only as reliable as the approval is available, which means it can fail catastrophically during periods of isolation, career transition, or genuine criticism. There's also a subtle identity risk — doing things for recognition long enough tends to erode the ability to distinguish what you want from what you want to be seen wanting. The engine is powerful but borrowed.`,

    'intrinsic curiosity': `Intrinsic curiosity as a primary motivational engine is the most sustainable of the four, but it has a specific failure mode: it doesn't scale well to execution phases. The mechanism runs on novelty, challenge, and genuine interest — which means the initiation and exploration phases of any project get disproportionate energy while the finishing, maintaining, and systematizing phases run on fumes. This produces people who are exceptional starters and often mediocre finishers, who are most alive at the frontier of a problem and least alive in the middle of implementation. The upside is that curiosity-driven motivation is genuinely self-replenishing in a way that fear and approval are not — but it needs structural support (accountability, deadlines, partners who handle the steady-state work) to convert that energy into completed things.`,

    'meaning and purpose': `Meaning and purpose as a primary motivational engine produces the most coherent long-term trajectory of the four, but it's slow-burning and difficult to sustain across micro-timescales. The mechanism runs on alignment — effort feels justified when it's connected to a larger narrative about why this matters, and becomes effortful and hollow when that connection breaks. The specific vulnerability is meaning maintenance: purpose can erode through accumulation of non-aligned tasks, through proximity to cynical institutions, or through the simple grinding of time without enough signal that the work is actually doing what it's supposed to do. Purpose-driven people don't burn out from overwork the way fear-driven people do; they burn out from loss of signal — from doing the work but losing the why.`,
  },

  // ─── MODULE 7: OVERTHINKING ──────────────────────────────────────────────
  // Primary driver: emotionRegulation.style (suppression, acceptance, rumination)
  // How this regulation style drives overthinking and what it's avoiding.
  overthinking: {
    'suppression': `Suppression-style overthinking is cognitive laundering: the emotion is not allowed to exist, so it gets converted into thoughts that feel productive and analytical but are functionally carrying the emotional charge without processing it. The brain finds the suppressed feeling intolerable, redirects to thinking-about-the-situation as a safer container, and generates elaborate analyses that circle the feeling without ever landing on it. What the overthinking is actually avoiding is the emotion itself — not the outcome, not the decision, not the person, but the raw felt experience that the suppression is designed to prevent. The tell is that the thinking rarely resolves: they can analyze a situation from twelve angles and still feel no relief, because the thing driving the loop isn't a question that analysis can answer.`,

    'acceptance': `Acceptance-style overthinking is rarer but real: it shows up not as avoidance of emotion but as a tendency to over-process experiences rather than letting them pass. For people with high emotional acceptance, the risk is that awareness becomes a project — examining every feeling, tracing every reaction back to its source, contextualizing every experience within a psychological framework. This is cognitively sophisticated and can become its own form of avoidance: the meta-level analysis of "why do I feel this?" as a way of not simply feeling it. The overthinking here is less about suppression and more about intellectualizing — using psychological understanding as a buffer against the unmediated experience of being a person. The thing being avoided is often simplicity: the permission to just feel something without it needing to mean something.`,

    'rumination': `Rumination-style overthinking is a closed loop with a locked exit: the mind revisits the same events, the same conversations, the same failures, looking for the update or resolution that would let it stop — and never finding it, because rumination is not actually a search process. It's a maintenance process that keeps a threat (usually a social wound, a failure, or an uncertainty) active in working memory under the premise that continued attention will eventually produce safety. What it's actually avoiding is the finality of acceptance — the acknowledgment that the thing happened, that it hurt, that it can't be undone by additional processing. Rumination is grief that won't grieve. The loop continues not because the person hasn't thought about it enough but because thinking about it has become a substitute for feeling the loss.`,
  },

  // ─── MODULE 8: EMOTIONAL TRIGGER ─────────────────────────────────────────
  // Primary driver: attachment.style (secure, anxious, avoidant, disorganized)
  // The specific emotional trigger blueprint for this attachment style.
  emotional_trigger: {
    'secure': `Securely attached people have emotional triggers — they're not immune, and they're not always calm. But their triggers are mostly proportionate: they fire when something actually bad is happening, and they de-escalate when the threat resolves. The most reliable triggers are violations of trust (because security was built on trust being reliable) and being treated as though their feelings don't matter (because security includes the expectation of being taken seriously). The distinction from anxious and avoidant triggers is context-sensitivity: secure triggers respond to what is actually happening rather than to what it might mean about the relationship's survival. Their recovery is also faster — not because they feel less, but because they're not fighting the secondary spiral of "what does this reaction say about me?"`,

    'anxious': `Anxiously attached people are triggered most reliably by anything that activates the abandonment schema — which is a broader category than most people realize. It's not just physical absence; it's emotional distance, perceived coldness, delayed responses, ambiguous tone, mixed signals, or any moment where they can't read whether the relationship is still okay. The trigger fires fast and hot because the nervous system has been trained on intermittent reinforcement — sometimes available, sometimes not — which produces hypervigilance to signs of withdrawal. The secondary trigger is self-related: once the abandonment alarm fires, a self-blame loop often activates alongside it (what did I do? what's wrong with me?). The two triggers reinforce each other, which is why a small perceived slight can produce a reaction that looks wildly disproportionate from the outside.`,

    'avoidant': `Avoidantly attached people are triggered most reliably by demands for closeness, emotional accountability, or explicit need — anything that reads to the nervous system as encroachment on the independence that's serving as their primary safety system. The trigger is sneaky because it often presents as irritability, contempt, or withdrawal rather than as distress, which makes it hard for partners to recognize as fear. A partner asking "are you okay?" can feel like surveillance. Being emotionally needed feels like a debt. Intimacy that's escalating can produce a kind of claustrophobic panic they may not identify as panic. The secondary trigger is self-directed: being perceived as cold or unavailable hits the self-concept in a way that produces defensiveness — because they've told themselves the independence is strength, not wound.`,

    'disorganized': `Disorganized attachment produces the most paradoxical trigger profile: closeness itself is triggering, but so is distance. The nervous system learned in an environment where the attachment figure was both comfort and threat, which means it never developed a coherent strategy for what to do when overwhelmed — approach or flee, both feel dangerous. The triggers are often confused with mood instability because they can look like rapid emotional state changes without clear cause. The most reliable activation is intimacy paired with uncertainty: feeling close to someone in a moment where trust is incomplete. Perceived betrayal is particularly destabilizing — not because it's unexpected (the nervous system was already scanning for it) but because it confirms the belief that closeness always eventually produces harm.`,
  },

  // ─── MODULE 9: MENTAL ENERGY ─────────────────────────────────────────────
  // Primary driver: ocean.E bucketed as low (<35), medium (35-65), high (>65)
  // The cognitive rhythm and energy pattern for this extraversion level.
  mental_energy: {
    'low': `Low extraversion produces a cognitive rhythm built for depth rather than throughput: they think by going in, not by talking it out, and their best work happens in conditions with minimal social interruption. The energy math is genuinely different — social interaction is not neutral, it's metabolically expensive, and a draining conversation can cost them concentration that takes hours to restore. This is not shyness (that's a separate variable), and it's not misanthropy; it's a processing architecture that's tuned for internal signal and attenuated by external noise. The practical consequence is a strong need to protect conditions for deep work, a tendency to be underestimated in real-time (their thinking happens offline) and a tendency to be overwhelmed in environments designed for extraverts — open offices, brainstorming sessions, always-on communication cultures.`,

    'medium': `Medium extraversion produces the most context-dependent cognitive rhythm: they're responsive to their environment in a way that high and low scorers are not. They can run on social energy when it's available and shift to internal processing when it's not, which makes them highly adaptive and also occasionally unclear about what they actually need. The ambiguity shows up in their energy accounting — they don't have the clear signal that introverts have (that was too much social contact) or that extraverts have (I need more people), so they sometimes misattribute energy drain or energy boost. Their best cognitive states tend to be collaborative but bounded: they think well with other people present and lose sharpness when the interaction becomes too dense or too long. They're the most situationally flexible and the least able to optimize for a fixed preference.`,

    'high': `High extraversion produces a cognitive rhythm that runs on contact — thinking sharpens in conversation, ideas emerge in social processing, and isolation is functionally depleting in a way that's often underestimated by the people around them. This is not about being loud or needing attention; it's about how the brain activates. An extravert alone for an extended stretch isn't just bored, they're cognitively running at reduced capacity, because the architecture is tuned for external input. The practical challenge is that high-extraversion people often underestimate how much their quality of thinking depends on their social environment, which means they can have significant cognitive performance variance based on whether they've had enough contact — and may attribute that variance to other causes (sleep, stress, diet) rather than the real one.`,
  },

  // ─── MODULE 10: DECISION PATTERN ─────────────────────────────────────────
  // Primary driver: decisionStyle.primary (intuitive, deliberate)
  // The decision algorithm, its strengths, and exactly where it breaks down.
  decision_pattern: {
    'intuitive': `Intuitive decision-making is a pattern recognition engine running on compressed experience: the brain samples a situation, matches it against a vast library of absorbed patterns, and surfaces a conclusion — often before the person can articulate the reasoning. This is genuinely fast and often accurate in domains where the person has significant experience, because the pattern library is real and useful. The breakdown points are specific: intuition fails in genuinely novel situations (no matching pattern), in high-stakes low-base-rate decisions (intuition can't distinguish between rare true signals and common false ones), and when the gut feeling is being driven by anxiety or bias rather than pattern recognition. The meta-challenge for intuitive deciders is that accurate intuition and biased intuition feel identical from the inside — they both arrive as certainty.`,

    'deliberate': `Deliberate decision-making is a structured evaluation process: gather information, identify options, weigh criteria, decide. It's most powerful in complex decisions with clear variables, sufficient data, and enough time to execute the process properly. The algorithm genuinely outperforms intuition in these conditions. The breakdown points are also specific: it fails under time pressure (the process can't complete), in situations where the relevant variables are irreducibly subjective (the spreadsheet can't capture the feeling), and in a particularly painful failure mode — analysis paralysis, where the desire for certainty before deciding produces an infinite deferral loop. Deliberate deciders also have an optimization bias: they can spend more time on the decision than the decision warrants, and can mistake thoroughness for accuracy in situations where more analysis doesn't actually reduce uncertainty.`,
  },

  // ─── MODULE 11: PERSONAL LEVERAGE ────────────────────────────────────────
  // Primary driver: strengths[0] (top VIA strength)
  // The leverage point of this strength and what it costs if overused.
  personal_leverage: {
    'Creativity': `Creativity as a top strength is an engine for novel solutions — the brain naturally finds the unexpected angle, the unorthodox combination, the approach that other people didn't see. The leverage point is highest in early-stage problem solving and in domains where conventional approaches have stopped working. Used well, it's a competitive advantage that's genuinely hard to replicate. The cost of overuse is real: creativity can become a way of avoiding the boring work of executing a good idea, since the next new idea is always more interesting than the current one in its implementation phase. It can also produce a social cost — creative approaches sometimes make people uncomfortable, and creative people can read that discomfort as a failure of the audience rather than a failure of communication. The strength is most powerful when paired with the discipline to finish things.`,

    'Curiosity': `Curiosity as a top strength is an extraordinary learning accelerator — the brain intrinsically rewards exploration, which means the person compounds knowledge and perspective at a rate that most people don't. The leverage point is highest in knowledge-gathering phases, in creative synthesis across domains, and in any work that benefits from seeing the problem from multiple angles. The cost of overuse is a scattering problem: curiosity without discrimination leads to knowing a lot about a lot of things and going deep on none of them, which produces breadth without mastery. There's also a relational cost in focused contexts — following curiosity during a meeting that has a specific agenda, derailing conversations with interesting tangents — that the curious person often doesn't register because the exploration feels obviously valuable from the inside.`,

    'Judgment': `Judgment as a top strength is a quality control mechanism operating on reasoning itself: the ability to examine evidence carefully, identify flaws in arguments (including their own), and arrive at well-calibrated conclusions. The leverage point is highest in high-stakes decisions, in adversarial contexts where bad arguments need to be identified, and in any role where the cost of being wrong is significant. The cost of overuse is skepticism that reads as negativity: the same capacity that identifies flaws in bad arguments also identifies flaws in good ones, and excessive criticism of otherwise-adequate proposals can slow decision-making and demoralize people who feel perpetually scrutinized. There's also an interpersonal cost — highly analytical people often experience their judgment as neutral observation while others experience it as judgment of them.`,

    'Perspective': `Perspective as a top strength is a rare ability to hold multiple viewpoints simultaneously and synthesize them into something that's useful to other people — wisdom in the practical sense. The leverage point is highest in advisory roles, conflict mediation, and in complex situations where different stakeholders have genuinely incompatible-looking needs. People with this strength often become the person others come to for guidance, because their framing tends to recontextualize problems in ways that make them solvable. The cost of overuse is a self-application problem: the same zoomed-out view that makes them exceptional at helping others can make them frustratingly patient with their own dysfunction. When everything can be understood and contextualized, it becomes very easy to understand-and-contextualize situations that should actually be changed.`,

    'Bravery': `Bravery as a top strength is not the absence of fear — it's the consistent capacity to act despite fear, to hold a position despite social pressure, to be honest when dishonesty would be easier. The leverage point is highest in situations that require someone to be the first, to say the thing nobody's saying, or to take the risk others won't. Used well, this strength functions as a social good as much as a personal one. The cost of overuse is a nuance problem: bravery applied without calibration becomes recklessness or stubbornness, and the same person who's admirably willing to say hard truths can become someone who confuses directness with bluntness and force with strength. There's also a risk-assessment gap — people high in bravery sometimes underweight actual danger because fear is not functioning as a reliable signal.`,

    'Honesty': `Honesty as a top strength is an integrity-first operating system: the person is constitutionally disinclined to deceive, perform, or misrepresent — and others tend to trust them because of it, often without being able to articulate why. The leverage point is highest in relationships and roles where trust is the primary currency and where the temptation to manage impressions is strong. The cost of overuse is a social friction problem. Honesty without tact is just truth-telling that hasn't accounted for timing, relationship, or what the other person can actually hear — and people high in honesty can sometimes experience the social blowback of their directness as evidence that the world punishes truth rather than as evidence that delivery matters. There's also a rigidity risk: treating honesty as a virtue rather than a value can make the person inflexible in situations that genuinely call for discretion.`,

    'Kindness': `Kindness as a top strength is a genuine orientation toward other people's wellbeing that manifests in consistent, often unremarkable acts of care — the kind that accumulates trust and goodwill in ways that the person often doesn't fully track. The leverage point is highest in team environments, in caregiving roles, and in any context where trust and psychological safety are prerequisites for performance. The cost of overuse is a boundary and resentment problem: kindness extended without limits becomes self-abnegation, and the person can find themselves unable to say no, unable to hold others accountable, and quietly accumulating a resentment they don't feel entitled to because being kind is supposed to feel good. The strength is most powerful when the person extends it to themselves with the same generosity they extend to everyone else.`,

    'Perseverance': `Perseverance as a top strength is a consistency engine: the capacity to keep going when motivation has flagged, when the result isn't visible, when the work is grinding and unpleasant. This is a genuine competitive advantage in any long-horizon endeavor because most people quit here, and the person high in perseverance doesn't. The leverage point is highest in efforts that require sustained effort over long timescales where initial enthusiasm is long gone. The cost of overuse is sunk-cost adherence — the same mechanism that says "keep going when it's hard" can also say "keep going when you should stop," and distinguishing between the two is genuinely difficult when you've built your identity around not quitting. There's also a rest-resistance problem: people high in perseverance can be bad at recovery, at strategic withdrawal, at the kind of stopping that's actually part of long-term performance.`,

    'Leadership': `Leadership as a top strength is a natural pull toward organizing people around a shared direction — not dominance, but a functional comfort with being the one who sets the frame, carries the vision, and takes responsibility for collective outcomes. The leverage point is highest in ambiguous, early-stage situations where someone needs to define what "we're doing" before anyone else can move. The cost of overuse is a control problem: the same instinct that makes someone good at providing direction can make them bad at receiving it, at distributing authority, at creating conditions where other people can lead. There's also an identity-capture risk — people who've built leadership into their core identity can have significant difficulty with situations that require followership, deference, or being the person who doesn't have the answer.`,

    'Fairness': `Fairness as a top strength is a principled commitment to consistency and equity that shows up as reliable, impartial behavior even when partial treatment would be easier or more personally advantageous. The leverage point is highest in institutional contexts, team dynamics, and any situation where people need to trust that the rules apply uniformly. The cost of overuse is a rigidity problem: strict application of principles to messy situations can produce outcomes that are technically fair but contextually wrong. There's also an emotional accessibility issue — people who lead with fairness principles can sometimes feel cold in contexts that are calling for compassion rather than equity, where what someone needs isn't to be treated the same as everyone else but to be treated like them specifically. The strength is most powerful when paired with the flexibility to know when a situation calls for discretion rather than rule application.`,

    'Gratitude': `Gratitude as a top strength is a genuine attentional orientation toward what's working, what's been given, and who's contributed — not performed positivity, but a real capacity to notice and appreciate the good in their experience. The leverage point is highest in high-stress environments where the ability to access what's working serves as a cognitive and emotional anchor, and in relationships where the person's genuine appreciation has a sustaining effect on connection. The cost of overuse is a tolerance-of-bad-situations problem: the same orientation that finds genuine good in difficult circumstances can become a rationalization for staying in circumstances that should be left. There's also a subtle social dynamic — people high in gratitude sometimes feel guilty about wanting more or doing better, because wanting implies the present isn't enough.`,

    'Humility': `Humility as a top strength is not self-deprecation — it's accurate self-assessment, a genuine interest in other people's perspectives, and a comfort with not being the most important presence in the room. The leverage point is highest in collaborative contexts where ego-protection behaviors in others are already creating friction, and in learning environments where the willingness to not-know is the prerequisite for growth. The cost of overuse is an underestimation problem: people high in humility often under-advocate for themselves, understate their contributions, and defer to others in situations where their own judgment is actually better. There's also a social-navigation cost in environments that reward confidence and visibility — the person's actual competence remains partially invisible because they're not performing it, and the performance of confidence often matters for how competence gets recognized.`,
  },

  // ─── MODULE 12: LIFE AS GAME ─────────────────────────────────────────────
  // Primary driver: enneagram.primary (1-9)
  // Game mechanics: stats (OP/weak), boss enemy, main quest.
  life_as_game: {
    '1': `Stats: Maxed integrity, discipline, and pattern recognition — they spot flaws in systems instantly and have exceptional follow-through on commitments. Weak stats: flexibility, self-compassion, and the ability to release a problem once identified. Boss enemy: The Inner Critic — an unkillable NPC that respawns immediately after every defeat, voices every standard the One has internalized, and makes the win condition a permanently moving target. The main quest is not to improve the world (they're already doing that) — it's to complete the quest labeled "You Are Enough" without first achieving perfect. Most Ones die at a high level without ever starting that quest, because they're convinced it unlocks only after one more thing is fixed.`,

    '2': `Stats: Maxed empathy, social intelligence, and relational repair — they can read a room, tend a wound, and build loyalty that other types can only envy. Weak stats: self-advocacy, receiving care without deflecting, and knowing what they want when no one needs anything. Boss enemy: The Invisible Ledger — a hidden accounting system that tracks every gift given and every return not received, and which the Two insists doesn't exist right up until it produces a catastrophic resentment event. The main quest is to want something for themselves — specifically, to locate what that is and ask for it without first framing it as what's best for everyone else. It's a simple quest. It's the hardest quest.`,

    '3': `Stats: Maxed adaptability, execution speed, and social calibration — they can become whoever succeeds in this environment and make it look natural. Weak stats: stillness, genuine emotional access, and doing things that won't be seen or rewarded. Boss enemy: The Empty Room — the existential encounter with themselves when the audience is gone, the achievements are accounted for, and what's left is just the question of whether any of it was actually wanted. The main quest is labeled "Be Somebody" but the real main quest, accessible only through a hidden questline, is "Find Out Who You Are When Nobody's Watching." Most Threes find this questline in midlife. It's the only one with a real ending.`,

    '4': `Stats: Maxed depth, aesthetic intelligence, and emotional range — they can feel the full spectrum of human experience and translate it into something others can recognize themselves in. Weak stats: equanimity, the ability to let good things be enough, and functional operation during the low cycles. Boss enemy: The Idealized Elsewhere — a shape-shifting antagonist that represents everything the Four doesn't have, everything that would make them whole if only they had it. It can appear as a person, a life, an era, a past self. It cannot be defeated, only recognized. The main quest is called "Be Here" and it requires putting down an inventory item the Four has been carrying since the beginning: the story that they are fundamentally missing something the world forgot to give them.`,

    '5': `Stats: Maxed analysis, independent thinking, and the ability to synthesize complex systems — they can see structural patterns that other people miss entirely. Weak stats: presence, vulnerability in real time, and sustained social engagement without a controlled exit. Boss enemy: The Resource Monitor — an internal process that tracks energy, privacy, and cognitive bandwidth as finite resources under constant threat of depletion, and triggers a withdrawal response at the earliest signs of demand. It is very good at its job. It is also causing the loneliness. The main quest is not to know everything (they're progressing well on that one) — it's to be known, which requires letting the Resource Monitor's alerts exist without always acting on them. The loot for this quest is connection. It respawns.`,

    '6': `Stats: Maxed loyalty, scenario planning, and the ability to identify the flaw in any system before anyone else does. Weak stats: self-trust, the ability to act without external validation, and enjoying things without scanning them for threat. Boss enemy: The Certainty Gap — the distance between the reassurance they need to feel safe and the reassurance that's actually available, which is always less. It cannot be closed by accumulating more information or more loyal allies. It can only be navigated. The main quest is labeled "Find The Right Authority To Trust" but the real main quest is "Become Your Own Authority" — which requires the terrifying experiment of making a call, being wrong, surviving it, and updating the belief that surviving being wrong is impossible.`,

    '7': `Stats: Maxed possibility thinking, resilience, and the ability to generate excitement and momentum in themselves and others. Weak stats: grief processing, sustained attention after the novelty window closes, and the willingness to let something fully disappoint them. Boss enemy: The Exit Portal — an always-available escape hatch that appears whenever a situation demands prolonged discomfort, depth, or the specific kind of presence required for commitment. It is disguised as better options, exciting ideas, and reframes that convert pain into learning before the pain has finished teaching. The main quest is called "Experience Everything" and it's going beautifully. The hidden main quest, which unlocks only when the Seven stops running long enough to read their quest log, is "Let One Thing Be Enough." The rewards are peace and depth and the end of the chase.`,

    '8': `Stats: Maxed willpower, decisive action, and the ability to move a situation by sheer force of presence — they create reality rather than reacting to it. Weak stats: receptivity, the experience of being comforted, and situations that can't be solved by force. Boss enemy: The Surrender Encounter — a mandatory late-game event where the Eight must put down the weapons and let something matter enough to be vulnerable about. It appears in forms like grief, illness, love, and the realization that control was always partial. It cannot be beaten. It can only be entered. The main quest is labeled "Build Something Powerful" and they are exceptional at it. The hidden questline, which contains the final boss, is called "Let Someone In." It requires unequipping the armor. All of it.`,

    '9': `Stats: Maxed conflict mediation, synthetic thinking, and the ability to hold multiple perspectives without collapsing — they are the people who can genuinely see all sides. Weak stats: self-prioritization, urgency, and the ability to locate what they want before it's too late to matter. Boss enemy: The Inertia Field — a passive force that makes the status quo feel like the only real option, that makes every action feel slightly more effortful than it needs to be, that converts "I'll do it eventually" into a permanent holding pattern. It doesn't attack. It just makes everything a little harder to start. The main quest is labeled "Keep The Peace" and they are completing it in record time. The real main quest — the one with the good ending — is called "Show Up." It requires equipping the item they've been carrying but never using: their own voice.`,
  },

};
